(* autogenerated from k8s.io/kubernetes/pkg/controller/simplreplicaset *)

From New.golang Require Import defn.
Definition simplreplicaset : go_string := "k8s.io/kubernetes/pkg/controller/simplreplicaset".

Module simplreplicaset.

Module Pod. Definition id : go_string := "k8s.io/kubernetes/pkg/controller/simplreplicaset.Pod"%go. End Pod.

Section code.
Context `{ffi_syntax}.


Definition Pod : go_type := structT [
  "Namespace" :: stringT;
  "Name" :: stringT
].
#[global] Typeclasses Opaque Pod.
#[global] Opaque Pod.

Definition PodKey : go_string := "k8s.io/kubernetes/pkg/controller/simplreplicaset.PodKey"%go.

(* go: replica_set.go:8:6 *)
Definition PodKeyⁱᵐᵖˡ : val :=
  λ: "pod",
    exception_do (let: "pod" := (mem.alloc "pod") in
    return: (((![#stringT] (struct.field_ref #Pod #"Namespace"%go (![#ptrT] "pod"))) + #"/"%go) + (![#stringT] (struct.field_ref #Pod #"Name"%go (![#ptrT] "pod"))))).

Definition getPodKeys : go_string := "k8s.io/kubernetes/pkg/controller/simplreplicaset.getPodKeys"%go.

(* go: replica_set.go:12:6 *)
Definition getPodKeysⁱᵐᵖˡ : val :=
  λ: "pods",
    exception_do (let: "pods" := (mem.alloc "pods") in
    let: "podKeys" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$r0" := (slice.make3 #stringT #(W64 0) (let: "$a0" := (![#sliceT] "pods") in
    slice.len "$a0")) in
    do:  ("podKeys" <-[#sliceT] "$r0");;;
    let: "$range" := (![#sliceT] "pods") in
    (let: "pod" := (mem.alloc (type.zero_val #ptrT)) in
    slice.for_range #ptrT "$range" (λ: "$key" "$value",
      do:  ("pod" <-[#ptrT] "$value");;;
      do:  "$key";;;
      let: "$r0" := (let: "$a0" := (![#sliceT] "podKeys") in
      let: "$a1" := ((let: "$sl0" := (let: "$a0" := (![#ptrT] "pod") in
      (func_call #PodKey) "$a0") in
      slice.literal #stringT ["$sl0"])) in
      (slice.append #stringT) "$a0" "$a1") in
      do:  ("podKeys" <-[#sliceT] "$r0")));;;
    return: (![#sliceT] "podKeys")).

Definition vars' : list (go_string * go_type) := [].

Definition functions' : list (go_string * val) := [(PodKey, PodKeyⁱᵐᵖˡ); (getPodKeys, getPodKeysⁱᵐᵖˡ)].

Definition msets' : list (go_string * (list (go_string * val))) := [(Pod.id, []); (ptrT.id Pod.id, [])].

#[global] Instance info' : PkgInfo simplreplicaset.simplreplicaset :=
  {|
    pkg_vars := vars';
    pkg_functions := functions';
    pkg_msets := msets';
    pkg_imported_pkgs := [];
  |}.

Definition initialize' : val :=
  λ: <>,
    package.init #simplreplicaset.simplreplicaset (λ: <>,
      exception_do (do:  (package.alloc simplreplicaset.simplreplicaset #()))
      ).

End code.
End simplreplicaset.
