rocq = "src"
go_path = "./kubernetes/"
packages = [
    "regexp",
    "./pkg/api/legacyscheme",
    "./pkg/api/v1/pod",
    "./pkg/apis/apps",
    "./pkg/apis/apps/install",
    "./pkg/apis/apps/v1",
    "./pkg/apis/apps/validation",
    "./pkg/apis/core",
    "./pkg/apis/core/v1",
    "./pkg/apis/core/validation",
    "./pkg/apis/rbac",
    "./pkg/apis/rbac/install",
    "./pkg/controller",
    # "./pkg/controller/replicaset",
    # "./pkg/controller/replicaset/metrics",
    "./pkg/features",
    "./pkg/registry/apps/deployment",
    "./pkg/registry/apps/replicaset",
    "./pkg/registry/apps/statefulset",
    "./pkg/registry/core/persistentvolumeclaim",
    "./pkg/registry/core/pod",
    "./pkg/registry/core/serviceaccount",
    "./pkg/registry/rbac/clusterrole",
    "./staging/src/k8s.io/api/core/v1",
    "./staging/src/k8s.io/api/apps/v1",
    "./staging/src/k8s.io/api/rbac/v1",
    "./staging/src/k8s.io/apimachinery/pkg/api/equality",
    "./staging/src/k8s.io/apimachinery/pkg/api/errors",
    "./staging/src/k8s.io/apimachinery/pkg/api/meta",
    "./staging/src/k8s.io/apimachinery/pkg/api/resource",
    "./staging/src/k8s.io/apimachinery/pkg/api/validation",
    "./staging/src/k8s.io/apimachinery/pkg/apis/meta/v1",
    "./staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/validation",
    "./staging/src/k8s.io/apimachinery/pkg/conversion",
    "./staging/src/k8s.io/apimachinery/pkg/labels",
    "./staging/src/k8s.io/apimachinery/pkg/selection",
    "./staging/src/k8s.io/apimachinery/pkg/runtime",
    "./staging/src/k8s.io/apimachinery/pkg/runtime/schema",
    "./staging/src/k8s.io/apimachinery/pkg/types",
    "./staging/src/k8s.io/apimachinery/pkg/util/intstr",
    "./staging/src/k8s.io/apimachinery/pkg/util/errors",
    "./staging/src/k8s.io/apimachinery/pkg/util/runtime",
    "./staging/src/k8s.io/apimachinery/pkg/util/validation",
    "./staging/src/k8s.io/apimachinery/pkg/watch",
    "./staging/src/k8s.io/apimachinery/pkg/util/uuid",
    "./staging/src/k8s.io/apimachinery/pkg/util/validation/field",
    "./staging/src/k8s.io/apiserver/pkg/endpoints/request",
    "./staging/src/k8s.io/apiserver/pkg/registry/generic/registry",
    "./staging/src/k8s.io/apiserver/pkg/registry/rest",
    "./staging/src/k8s.io/apiserver/pkg/util/feature",
    "./staging/src/k8s.io/client-go/kubernetes",
    "./staging/src/k8s.io/client-go/applyconfigurations/core/v1",
    "./staging/src/k8s.io/client-go/gentype",
    "./staging/src/k8s.io/client-go/kubernetes/typed/apps/v1",
    "./staging/src/k8s.io/client-go/kubernetes/typed/core/v1",
    "./staging/src/k8s.io/client-go/listers/apps/v1",
    "./staging/src/k8s.io/client-go/listers/core/v1",
    "./staging/src/k8s.io/client-go/rest",
    "./staging/src/k8s.io/client-go/tools/cache",
    "./staging/src/k8s.io/client-go/util/apply",
    # "./staging/src/k8s.io/client-go/util/workqueue",
    "./staging/src/k8s.io/component-base/featuregate",
    "./staging/src/k8s.io/component-base/metrics",
    "./vendor/github.com/go-logr/logr",
    "./vendor/k8s.io/klog/v2",
    "./vendor/k8s.io/utils/clock",
    "./vendor/k8s.io/utils/ptr",
]
