opam-version: "2.0"
license: "MIT"
maintainer: "Xudong Sun"
authors: "kubernetes-verification authors"
homepage: "https://github.com/marshtompsxd/kubernetes-verification"
bug-reports: "https://github.com/marshtompsxd/kubernetes-verification/issues"
dev-repo: "git+https://github.com/marshtompsxd/kubernetes-verification.git"
version: "dev"
synopsis: "Specs and proofs for Kubernetes controllers"

depends: [
  "perennial"
]

pin-depends: [
  ["perennial.dev"             "git+https://github.com/mit-pdos/perennial#c456aa2e494321eaf9ee931b44619ca986531608"]

  ## begin indirect
  ["coq-coqutil.dev"           "git+https://github.com/mit-plv/coqutil#6644c132300a4da5fb1a4ce5c3860f60c135b2fa"]
  ["coq-record-update.dev"     "git+https://github.com/tchajed/coq-record-update#7b2645210331c3ec4ed75fa5ad0840a723f25151"]
  ["rocq-stdpp.dev"            "git+https://gitlab.mpi-sws.org/iris/stdpp#0989202c46f352854feb5f96b6c3a1f4f91f886a"]
  ["rocq-iris.dev"             "git+https://gitlab.mpi-sws.org/iris/iris#b762dd2428a60a88d84373b34629b3c200be248e"]
  ["iris-named-props.dev"      "git+https://github.com/tchajed/iris-named-props#c388714a93b1c043ed42a3f446280abd5113d26f"]
  ## end
]

build: [make "-j%{jobs}%"]
install: ["go" "tool" "perennial-cli" "install"]
build-env: [
  [GOCACHE = "%{build}%/_build/.gocache"]
]
