(* autogenerated from k8s.io/utils/ptr *)
From New.golang Require Import defn.
Module pkg_id.
Definition ptr : go_string := "k8s.io/utils/ptr".

End pkg_id.
Export pkg_id.
Module ptr.

Definition AllPtrFieldsNil {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/utils/ptr.AllPtrFieldsNil"%go.

Definition To {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/utils/ptr.To"%go.

Definition Deref {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/utils/ptr.Deref"%go.

Definition Equal {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/utils/ptr.Equal"%go.

(* To returns a pointer to the given value.

   go: ptr.go:50:6 *)
Definition Toⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} (T : go.type) : val :=
  λ: "v",
    exception_do (let: "v" := (GoAlloc T "v") in
    return: ("v")).

#[global] Instance info' : PkgInfo pkg_id.ptr :=
{|
  pkg_imported_pkgs := []
|}.

Axiom _'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.ptr (λ: <>,
      exception_do (do:  #())
      ).

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] To_unfold T :: FuncUnfold To [T] (Toⁱᵐᵖˡ T);
}.
End ptr.
