(* autogenerated from k8s.io/client-go/kubernetes/typed/apps/v1 *)
From New.golang Require Import defn.
Module pkg_id.
Definition v1 : go_string := "k8s.io/client-go/kubernetes/typed/apps/v1".

End pkg_id.
Export pkg_id.
Module v1.

Definition AppsV1Interface {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.AppsV1Interface"%go [].

#[global] Opaque AppsV1Interface.

Definition AppsV1Client {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.AppsV1Client"%go [].

#[global] Opaque AppsV1Client.

Definition ControllerRevisionsGetter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.ControllerRevisionsGetter"%go [].

#[global] Opaque ControllerRevisionsGetter.

Definition ControllerRevisionInterface {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.ControllerRevisionInterface"%go [].

#[global] Opaque ControllerRevisionInterface.

Definition controllerRevisions {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.controllerRevisions"%go [].

#[global] Opaque controllerRevisions.

Definition DaemonSetsGetter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.DaemonSetsGetter"%go [].

#[global] Opaque DaemonSetsGetter.

Definition DaemonSetInterface {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.DaemonSetInterface"%go [].

#[global] Opaque DaemonSetInterface.

Definition daemonSets {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.daemonSets"%go [].

#[global] Opaque daemonSets.

Definition DeploymentsGetter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.DeploymentsGetter"%go [].

#[global] Opaque DeploymentsGetter.

Definition DeploymentInterface {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.DeploymentInterface"%go [].

#[global] Opaque DeploymentInterface.

Definition deployments {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.deployments"%go [].

#[global] Opaque deployments.

Definition ControllerRevisionExpansion {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.ControllerRevisionExpansion"%go [].

#[global] Opaque ControllerRevisionExpansion.

Definition DaemonSetExpansion {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.DaemonSetExpansion"%go [].

#[global] Opaque DaemonSetExpansion.

Definition DeploymentExpansion {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.DeploymentExpansion"%go [].

#[global] Opaque DeploymentExpansion.

Definition ReplicaSetExpansion {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.ReplicaSetExpansion"%go [].

#[global] Opaque ReplicaSetExpansion.

Definition StatefulSetExpansion {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.StatefulSetExpansion"%go [].

#[global] Opaque StatefulSetExpansion.

Definition ReplicaSetsGetter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.ReplicaSetsGetter"%go [].

#[global] Opaque ReplicaSetsGetter.

Definition ReplicaSetInterface {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.ReplicaSetInterface"%go [].

#[global] Opaque ReplicaSetInterface.

Definition replicaSets {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.replicaSets"%go [].

#[global] Opaque replicaSets.

Definition StatefulSetsGetter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.StatefulSetsGetter"%go [].

#[global] Opaque StatefulSetsGetter.

Definition StatefulSetInterface {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.StatefulSetInterface"%go [].

#[global] Opaque StatefulSetInterface.

Definition statefulSets {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes/typed/apps/v1.statefulSets"%go [].

#[global] Opaque statefulSets.

Axiom AppsV1Interfaceⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom AppsV1Clientⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom ControllerRevisionsGetterⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom ControllerRevisionInterfaceⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom controllerRevisionsⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom DaemonSetsGetterⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom DaemonSetInterfaceⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom daemonSetsⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom DeploymentsGetterⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom DeploymentInterfaceⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom deploymentsⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom ControllerRevisionExpansionⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom DaemonSetExpansionⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom DeploymentExpansionⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom ReplicaSetExpansionⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom StatefulSetExpansionⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom ReplicaSetsGetterⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom ReplicaSetInterfaceⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom replicaSetsⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom StatefulSetsGetterⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom StatefulSetInterfaceⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom statefulSetsⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Definition NewForConfig {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/kubernetes/typed/apps/v1.NewForConfig"%go.

Definition NewForConfigAndClient {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/kubernetes/typed/apps/v1.NewForConfigAndClient"%go.

Definition NewForConfigOrDie {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/kubernetes/typed/apps/v1.NewForConfigOrDie"%go.

Definition New {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/kubernetes/typed/apps/v1.New"%go.

Definition setConfigDefaults {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/kubernetes/typed/apps/v1.setConfigDefaults"%go.

Definition newControllerRevisions {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/kubernetes/typed/apps/v1.newControllerRevisions"%go.

Definition newDaemonSets {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/kubernetes/typed/apps/v1.newDaemonSets"%go.

Definition newDeployments {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/kubernetes/typed/apps/v1.newDeployments"%go.

Definition newReplicaSets {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/kubernetes/typed/apps/v1.newReplicaSets"%go.

Definition newStatefulSets {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/kubernetes/typed/apps/v1.newStatefulSets"%go.

#[global] Instance info' : PkgInfo pkg_id.v1 :=
{|
  pkg_imported_pkgs := []
|}.

Axiom _'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.v1 (λ: <>,
      exception_do (do:  #())
      ).

Module AppsV1Interface.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End AppsV1Interface.

Class AppsV1Interface_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] AppsV1Interface_type_repr  :: go.TypeReprUnderlying AppsV1Interfaceⁱᵐᵖˡ AppsV1Interface.t;
  #[global] AppsV1Interface_underlying :: (AppsV1Interface) <u (AppsV1Interfaceⁱᵐᵖˡ);
  #[global] AppsV1Interfaceⁱᵐᵖˡ_underlying :: (AppsV1Interfaceⁱᵐᵖˡ) ↓u (AppsV1Interfaceⁱᵐᵖˡ);
}.

Module AppsV1Client.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End AppsV1Client.

Class AppsV1Client_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] AppsV1Client_type_repr  :: go.TypeReprUnderlying AppsV1Clientⁱᵐᵖˡ AppsV1Client.t;
  #[global] AppsV1Client_underlying :: (AppsV1Client) <u (AppsV1Clientⁱᵐᵖˡ);
  #[global] AppsV1Clientⁱᵐᵖˡ_underlying :: (AppsV1Clientⁱᵐᵖˡ) ↓u (AppsV1Clientⁱᵐᵖˡ);
}.

Module ControllerRevisionsGetter.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End ControllerRevisionsGetter.

Class ControllerRevisionsGetter_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] ControllerRevisionsGetter_type_repr  :: go.TypeReprUnderlying ControllerRevisionsGetterⁱᵐᵖˡ ControllerRevisionsGetter.t;
  #[global] ControllerRevisionsGetter_underlying :: (ControllerRevisionsGetter) <u (ControllerRevisionsGetterⁱᵐᵖˡ);
  #[global] ControllerRevisionsGetterⁱᵐᵖˡ_underlying :: (ControllerRevisionsGetterⁱᵐᵖˡ) ↓u (ControllerRevisionsGetterⁱᵐᵖˡ);
}.

Module ControllerRevisionInterface.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End ControllerRevisionInterface.

Class ControllerRevisionInterface_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] ControllerRevisionInterface_type_repr  :: go.TypeReprUnderlying ControllerRevisionInterfaceⁱᵐᵖˡ ControllerRevisionInterface.t;
  #[global] ControllerRevisionInterface_underlying :: (ControllerRevisionInterface) <u (ControllerRevisionInterfaceⁱᵐᵖˡ);
  #[global] ControllerRevisionInterfaceⁱᵐᵖˡ_underlying :: (ControllerRevisionInterfaceⁱᵐᵖˡ) ↓u (ControllerRevisionInterfaceⁱᵐᵖˡ);
}.

Module controllerRevisions.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End controllerRevisions.

Class controllerRevisions_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] controllerRevisions_type_repr  :: go.TypeReprUnderlying controllerRevisionsⁱᵐᵖˡ controllerRevisions.t;
  #[global] controllerRevisions_underlying :: (controllerRevisions) <u (controllerRevisionsⁱᵐᵖˡ);
  #[global] controllerRevisionsⁱᵐᵖˡ_underlying :: (controllerRevisionsⁱᵐᵖˡ) ↓u (controllerRevisionsⁱᵐᵖˡ);
}.

Module DaemonSetsGetter.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End DaemonSetsGetter.

Class DaemonSetsGetter_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] DaemonSetsGetter_type_repr  :: go.TypeReprUnderlying DaemonSetsGetterⁱᵐᵖˡ DaemonSetsGetter.t;
  #[global] DaemonSetsGetter_underlying :: (DaemonSetsGetter) <u (DaemonSetsGetterⁱᵐᵖˡ);
  #[global] DaemonSetsGetterⁱᵐᵖˡ_underlying :: (DaemonSetsGetterⁱᵐᵖˡ) ↓u (DaemonSetsGetterⁱᵐᵖˡ);
}.

Module DaemonSetInterface.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End DaemonSetInterface.

Class DaemonSetInterface_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] DaemonSetInterface_type_repr  :: go.TypeReprUnderlying DaemonSetInterfaceⁱᵐᵖˡ DaemonSetInterface.t;
  #[global] DaemonSetInterface_underlying :: (DaemonSetInterface) <u (DaemonSetInterfaceⁱᵐᵖˡ);
  #[global] DaemonSetInterfaceⁱᵐᵖˡ_underlying :: (DaemonSetInterfaceⁱᵐᵖˡ) ↓u (DaemonSetInterfaceⁱᵐᵖˡ);
}.

Module daemonSets.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End daemonSets.

Class daemonSets_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] daemonSets_type_repr  :: go.TypeReprUnderlying daemonSetsⁱᵐᵖˡ daemonSets.t;
  #[global] daemonSets_underlying :: (daemonSets) <u (daemonSetsⁱᵐᵖˡ);
  #[global] daemonSetsⁱᵐᵖˡ_underlying :: (daemonSetsⁱᵐᵖˡ) ↓u (daemonSetsⁱᵐᵖˡ);
}.

Module DeploymentsGetter.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End DeploymentsGetter.

Class DeploymentsGetter_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] DeploymentsGetter_type_repr  :: go.TypeReprUnderlying DeploymentsGetterⁱᵐᵖˡ DeploymentsGetter.t;
  #[global] DeploymentsGetter_underlying :: (DeploymentsGetter) <u (DeploymentsGetterⁱᵐᵖˡ);
  #[global] DeploymentsGetterⁱᵐᵖˡ_underlying :: (DeploymentsGetterⁱᵐᵖˡ) ↓u (DeploymentsGetterⁱᵐᵖˡ);
}.

Module DeploymentInterface.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End DeploymentInterface.

Class DeploymentInterface_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] DeploymentInterface_type_repr  :: go.TypeReprUnderlying DeploymentInterfaceⁱᵐᵖˡ DeploymentInterface.t;
  #[global] DeploymentInterface_underlying :: (DeploymentInterface) <u (DeploymentInterfaceⁱᵐᵖˡ);
  #[global] DeploymentInterfaceⁱᵐᵖˡ_underlying :: (DeploymentInterfaceⁱᵐᵖˡ) ↓u (DeploymentInterfaceⁱᵐᵖˡ);
}.

Module deployments.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End deployments.

Class deployments_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] deployments_type_repr  :: go.TypeReprUnderlying deploymentsⁱᵐᵖˡ deployments.t;
  #[global] deployments_underlying :: (deployments) <u (deploymentsⁱᵐᵖˡ);
  #[global] deploymentsⁱᵐᵖˡ_underlying :: (deploymentsⁱᵐᵖˡ) ↓u (deploymentsⁱᵐᵖˡ);
}.

Module ControllerRevisionExpansion.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End ControllerRevisionExpansion.

Class ControllerRevisionExpansion_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] ControllerRevisionExpansion_type_repr  :: go.TypeReprUnderlying ControllerRevisionExpansionⁱᵐᵖˡ ControllerRevisionExpansion.t;
  #[global] ControllerRevisionExpansion_underlying :: (ControllerRevisionExpansion) <u (ControllerRevisionExpansionⁱᵐᵖˡ);
  #[global] ControllerRevisionExpansionⁱᵐᵖˡ_underlying :: (ControllerRevisionExpansionⁱᵐᵖˡ) ↓u (ControllerRevisionExpansionⁱᵐᵖˡ);
}.

Module DaemonSetExpansion.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End DaemonSetExpansion.

Class DaemonSetExpansion_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] DaemonSetExpansion_type_repr  :: go.TypeReprUnderlying DaemonSetExpansionⁱᵐᵖˡ DaemonSetExpansion.t;
  #[global] DaemonSetExpansion_underlying :: (DaemonSetExpansion) <u (DaemonSetExpansionⁱᵐᵖˡ);
  #[global] DaemonSetExpansionⁱᵐᵖˡ_underlying :: (DaemonSetExpansionⁱᵐᵖˡ) ↓u (DaemonSetExpansionⁱᵐᵖˡ);
}.

Module DeploymentExpansion.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End DeploymentExpansion.

Class DeploymentExpansion_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] DeploymentExpansion_type_repr  :: go.TypeReprUnderlying DeploymentExpansionⁱᵐᵖˡ DeploymentExpansion.t;
  #[global] DeploymentExpansion_underlying :: (DeploymentExpansion) <u (DeploymentExpansionⁱᵐᵖˡ);
  #[global] DeploymentExpansionⁱᵐᵖˡ_underlying :: (DeploymentExpansionⁱᵐᵖˡ) ↓u (DeploymentExpansionⁱᵐᵖˡ);
}.

Module ReplicaSetExpansion.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End ReplicaSetExpansion.

Class ReplicaSetExpansion_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] ReplicaSetExpansion_type_repr  :: go.TypeReprUnderlying ReplicaSetExpansionⁱᵐᵖˡ ReplicaSetExpansion.t;
  #[global] ReplicaSetExpansion_underlying :: (ReplicaSetExpansion) <u (ReplicaSetExpansionⁱᵐᵖˡ);
  #[global] ReplicaSetExpansionⁱᵐᵖˡ_underlying :: (ReplicaSetExpansionⁱᵐᵖˡ) ↓u (ReplicaSetExpansionⁱᵐᵖˡ);
}.

Module StatefulSetExpansion.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End StatefulSetExpansion.

Class StatefulSetExpansion_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] StatefulSetExpansion_type_repr  :: go.TypeReprUnderlying StatefulSetExpansionⁱᵐᵖˡ StatefulSetExpansion.t;
  #[global] StatefulSetExpansion_underlying :: (StatefulSetExpansion) <u (StatefulSetExpansionⁱᵐᵖˡ);
  #[global] StatefulSetExpansionⁱᵐᵖˡ_underlying :: (StatefulSetExpansionⁱᵐᵖˡ) ↓u (StatefulSetExpansionⁱᵐᵖˡ);
}.

Module ReplicaSetsGetter.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End ReplicaSetsGetter.

Class ReplicaSetsGetter_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] ReplicaSetsGetter_type_repr  :: go.TypeReprUnderlying ReplicaSetsGetterⁱᵐᵖˡ ReplicaSetsGetter.t;
  #[global] ReplicaSetsGetter_underlying :: (ReplicaSetsGetter) <u (ReplicaSetsGetterⁱᵐᵖˡ);
  #[global] ReplicaSetsGetterⁱᵐᵖˡ_underlying :: (ReplicaSetsGetterⁱᵐᵖˡ) ↓u (ReplicaSetsGetterⁱᵐᵖˡ);
}.

Module ReplicaSetInterface.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End ReplicaSetInterface.

Class ReplicaSetInterface_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] ReplicaSetInterface_type_repr  :: go.TypeReprUnderlying ReplicaSetInterfaceⁱᵐᵖˡ ReplicaSetInterface.t;
  #[global] ReplicaSetInterface_underlying :: (ReplicaSetInterface) <u (ReplicaSetInterfaceⁱᵐᵖˡ);
  #[global] ReplicaSetInterfaceⁱᵐᵖˡ_underlying :: (ReplicaSetInterfaceⁱᵐᵖˡ) ↓u (ReplicaSetInterfaceⁱᵐᵖˡ);
}.

Module replicaSets.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End replicaSets.

Class replicaSets_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] replicaSets_type_repr  :: go.TypeReprUnderlying replicaSetsⁱᵐᵖˡ replicaSets.t;
  #[global] replicaSets_underlying :: (replicaSets) <u (replicaSetsⁱᵐᵖˡ);
  #[global] replicaSetsⁱᵐᵖˡ_underlying :: (replicaSetsⁱᵐᵖˡ) ↓u (replicaSetsⁱᵐᵖˡ);
}.

Module StatefulSetsGetter.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End StatefulSetsGetter.

Class StatefulSetsGetter_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] StatefulSetsGetter_type_repr  :: go.TypeReprUnderlying StatefulSetsGetterⁱᵐᵖˡ StatefulSetsGetter.t;
  #[global] StatefulSetsGetter_underlying :: (StatefulSetsGetter) <u (StatefulSetsGetterⁱᵐᵖˡ);
  #[global] StatefulSetsGetterⁱᵐᵖˡ_underlying :: (StatefulSetsGetterⁱᵐᵖˡ) ↓u (StatefulSetsGetterⁱᵐᵖˡ);
}.

Module StatefulSetInterface.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End StatefulSetInterface.

Class StatefulSetInterface_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] StatefulSetInterface_type_repr  :: go.TypeReprUnderlying StatefulSetInterfaceⁱᵐᵖˡ StatefulSetInterface.t;
  #[global] StatefulSetInterface_underlying :: (StatefulSetInterface) <u (StatefulSetInterfaceⁱᵐᵖˡ);
  #[global] StatefulSetInterfaceⁱᵐᵖˡ_underlying :: (StatefulSetInterfaceⁱᵐᵖˡ) ↓u (StatefulSetInterfaceⁱᵐᵖˡ);
}.

Module statefulSets.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End statefulSets.

Class statefulSets_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] statefulSets_type_repr  :: go.TypeReprUnderlying statefulSetsⁱᵐᵖˡ statefulSets.t;
  #[global] statefulSets_underlying :: (statefulSets) <u (statefulSetsⁱᵐᵖˡ);
  #[global] statefulSetsⁱᵐᵖˡ_underlying :: (statefulSetsⁱᵐᵖˡ) ↓u (statefulSetsⁱᵐᵖˡ);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] AppsV1Interface_instance :: AppsV1Interface_Assumptions;
  #[global] AppsV1Client_instance :: AppsV1Client_Assumptions;
  #[global] ControllerRevisionsGetter_instance :: ControllerRevisionsGetter_Assumptions;
  #[global] ControllerRevisionInterface_instance :: ControllerRevisionInterface_Assumptions;
  #[global] controllerRevisions_instance :: controllerRevisions_Assumptions;
  #[global] DaemonSetsGetter_instance :: DaemonSetsGetter_Assumptions;
  #[global] DaemonSetInterface_instance :: DaemonSetInterface_Assumptions;
  #[global] daemonSets_instance :: daemonSets_Assumptions;
  #[global] DeploymentsGetter_instance :: DeploymentsGetter_Assumptions;
  #[global] DeploymentInterface_instance :: DeploymentInterface_Assumptions;
  #[global] deployments_instance :: deployments_Assumptions;
  #[global] ControllerRevisionExpansion_instance :: ControllerRevisionExpansion_Assumptions;
  #[global] DaemonSetExpansion_instance :: DaemonSetExpansion_Assumptions;
  #[global] DeploymentExpansion_instance :: DeploymentExpansion_Assumptions;
  #[global] ReplicaSetExpansion_instance :: ReplicaSetExpansion_Assumptions;
  #[global] StatefulSetExpansion_instance :: StatefulSetExpansion_Assumptions;
  #[global] ReplicaSetsGetter_instance :: ReplicaSetsGetter_Assumptions;
  #[global] ReplicaSetInterface_instance :: ReplicaSetInterface_Assumptions;
  #[global] replicaSets_instance :: replicaSets_Assumptions;
  #[global] StatefulSetsGetter_instance :: StatefulSetsGetter_Assumptions;
  #[global] StatefulSetInterface_instance :: StatefulSetInterface_Assumptions;
  #[global] statefulSets_instance :: statefulSets_Assumptions;
}.
End v1.
