translate = [
    "AppsV1Interface",
    "ReplicaSetsGetter",
    "ReplicaSetInterface",
]

imports = [
    "context",
    "k8s.io/api/apps/v1",
    "k8s.io/api/autoscaling/v1",
    "k8s.io/apimachinery/pkg/apis/meta/v1",
    "k8s.io/apimachinery/pkg/types",
    "k8s.io/apimachinery/pkg/watch",
    "k8s.io/client-go/applyconfigurations/apps/v1",
    "k8s.io/client-go/applyconfigurations/autoscaling/v1",
    "k8s.io/client-go/rest",
]

trusted = [
    "AppsV1Client.ReplicaSets",
]
