(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.golang.theory.

Require Export New.code.k8s_io.apimachinery.pkg.api.errors.

Set Default Proof Using "Type".

Module errors.

(* type errors.StatusError *)
Module StatusError.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End StatusError.

Global Instance bounded_size_StatusError : BoundedTypeSize errors.StatusError.
Admitted.

Global Instance into_val_StatusError `{ffi_syntax} : IntoVal StatusError.t.
Admitted.

Global Instance into_val_typed_StatusError `{ffi_syntax} : IntoValTyped StatusError.t errors.StatusError.
Admitted.

(* type errors.APIStatus *)
Module APIStatus.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End APIStatus.

Global Instance bounded_size_APIStatus : BoundedTypeSize errors.APIStatus.
Admitted.

Global Instance into_val_APIStatus `{ffi_syntax} : IntoVal APIStatus.t.
Admitted.

Global Instance into_val_typed_APIStatus `{ffi_syntax} : IntoValTyped APIStatus.t errors.APIStatus.
Admitted.

(* type errors.UnexpectedObjectError *)
Module UnexpectedObjectError.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End UnexpectedObjectError.

Global Instance bounded_size_UnexpectedObjectError : BoundedTypeSize errors.UnexpectedObjectError.
Admitted.

Global Instance into_val_UnexpectedObjectError `{ffi_syntax} : IntoVal UnexpectedObjectError.t.
Admitted.

Global Instance into_val_typed_UnexpectedObjectError `{ffi_syntax} : IntoValTyped UnexpectedObjectError.t errors.UnexpectedObjectError.
Admitted.

(* type errors.ErrorReporter *)
Module ErrorReporter.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End ErrorReporter.

Global Instance bounded_size_ErrorReporter : BoundedTypeSize errors.ErrorReporter.
Admitted.

Global Instance into_val_ErrorReporter `{ffi_syntax} : IntoVal ErrorReporter.t.
Admitted.

Global Instance into_val_typed_ErrorReporter `{ffi_syntax} : IntoValTyped ErrorReporter.t errors.ErrorReporter.
Admitted.

Section names.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context `{!globalsGS Σ}.
Context {go_ctx : GoContext}.
#[local] Transparent is_pkg_defined is_pkg_defined_pure.

Global Instance is_pkg_defined_pure_errors : IsPkgDefinedPure errors :=
  {|
    is_pkg_defined_pure_def go_ctx :=
      is_pkg_defined_pure_single errors;
  |}.

#[local] Transparent is_pkg_defined_single is_pkg_defined_pure_single.
Global Program Instance is_pkg_defined_errors : IsPkgDefined errors :=
  {|
    is_pkg_defined_def go_ctx :=
      (is_pkg_defined_single errors)%I
  |}.
Final Obligation. iIntros. iFrame "#%". Qed.
#[local] Opaque is_pkg_defined_single is_pkg_defined_pure_single.

End names.
End errors.
