(* autogenerated from k8s.io/apimachinery/pkg/api/resource *)
From New.golang Require Import defn.
Module pkg_id.
Definition resource : go_string := "k8s.io/apimachinery/pkg/api/resource".

End pkg_id.
Export pkg_id.
Module resource.

Definition Scale {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apimachinery/pkg/api/resource.Scale"%go [].

#[global] Opaque Scale.

Definition int64Amount {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apimachinery/pkg/api/resource.int64Amount"%go [].

#[global] Opaque int64Amount.

Definition infDecAmount {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apimachinery/pkg/api/resource.infDecAmount"%go [].

#[global] Opaque infDecAmount.

Definition Quantity {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apimachinery/pkg/api/resource.Quantity"%go [].

#[global] Opaque Quantity.

Definition CanonicalValue {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apimachinery/pkg/api/resource.CanonicalValue"%go [].

#[global] Opaque CanonicalValue.

Definition Format {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apimachinery/pkg/api/resource.Format"%go [].

#[global] Opaque Format.

Definition QuantityValue {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apimachinery/pkg/api/resource.QuantityValue"%go [].

#[global] Opaque QuantityValue.

Definition suffix {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apimachinery/pkg/api/resource.suffix"%go [].

#[global] Opaque suffix.

Definition suffixer {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apimachinery/pkg/api/resource.suffixer"%go [].

#[global] Opaque suffixer.

Definition bePair {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apimachinery/pkg/api/resource.bePair"%go [].

#[global] Opaque bePair.

Definition listSuffixer {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apimachinery/pkg/api/resource.listSuffixer"%go [].

#[global] Opaque listSuffixer.

Definition suffixHandler {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apimachinery/pkg/api/resource.suffixHandler"%go [].

#[global] Opaque suffixHandler.

Definition fastLookup {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apimachinery/pkg/api/resource.fastLookup"%go [].

#[global] Opaque fastLookup.

Axiom Scaleⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom int64Amountⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom infDecAmountⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom CanonicalValueⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Formatⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom QuantityValueⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom suffixⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom suffixerⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom bePairⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom listSuffixerⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom suffixHandlerⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom fastLookupⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Nano : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom Micro : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom Milli : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom Kilo : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom Mega : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom Giga : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom Tera : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom Peta : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom Exa : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom maxInt64Factors : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom mostNegative : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom mostPositive : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom DecimalExponent : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom BinarySI : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom DecimalSI : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom splitREString : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom int64QuantityExpectedBytes : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition Zero {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.Zero"%go.

Axiom Zero'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition zeroBytes {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.zeroBytes"%go.

Axiom zeroBytes'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition xxx_messageInfo_Quantity {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.xxx_messageInfo_Quantity"%go.

Definition xxx_messageInfo_QuantityValue {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.xxx_messageInfo_QuantityValue"%go.

Definition fileDescriptor_7288c78ff45111e9 {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.fileDescriptor_7288c78ff45111e9"%go.

Axiom fileDescriptor_7288c78ff45111e9'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition bigTen {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.bigTen"%go.

Axiom bigTen'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition bigZero {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.bigZero"%go.

Axiom bigZero'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition bigOne {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.bigOne"%go.

Axiom bigOne'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition bigThousand {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.bigThousand"%go.

Axiom bigThousand'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition big1024 {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.big1024"%go.

Axiom big1024'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition decZero {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.decZero"%go.

Axiom decZero'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition decOne {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.decOne"%go.

Axiom decOne'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition maxAllowed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.maxAllowed"%go.

Axiom maxAllowed'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition MaxMilliValue {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.MaxMilliValue"%go.

Axiom MaxMilliValue'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition ErrFormatWrong {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.ErrFormatWrong"%go.

Axiom ErrFormatWrong'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition ErrNumeric {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.ErrNumeric"%go.

Axiom ErrNumeric'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition ErrSuffix {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.ErrSuffix"%go.

Axiom ErrSuffix'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition ErrInvalidLengthGenerated {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.ErrInvalidLengthGenerated"%go.

Axiom ErrInvalidLengthGenerated'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition ErrIntOverflowGenerated {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.ErrIntOverflowGenerated"%go.

Axiom ErrIntOverflowGenerated'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition intPool {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.intPool"%go.

Definition maxInt64 {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.maxInt64"%go.

Axiom maxInt64'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition quantitySuffixer {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.quantitySuffixer"%go.

Axiom quantitySuffixer'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition int64Add {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.int64Add"%go.

Definition int64Multiply {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.int64Multiply"%go.

Definition int64MultiplyScale {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.int64MultiplyScale"%go.

Definition int64MultiplyScale10 {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.int64MultiplyScale10"%go.

Definition int64MultiplyScale100 {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.int64MultiplyScale100"%go.

Definition int64MultiplyScale1000 {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.int64MultiplyScale1000"%go.

Definition positiveScaleInt64 {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.positiveScaleInt64"%go.

Definition negativeScaleInt64 {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.negativeScaleInt64"%go.

Definition pow10Int64 {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.pow10Int64"%go.

Definition divideByScaleInt64 {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.divideByScaleInt64"%go.

Definition removeInt64Factors {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.removeInt64Factors"%go.

Definition removeBigIntFactors {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.removeBigIntFactors"%go.

Definition MustParse {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.MustParse"%go.

Definition parseQuantityString {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.parseQuantityString"%go.

Definition ParseQuantity {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.ParseQuantity"%go.

Definition NewDecimalQuantity {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.NewDecimalQuantity"%go.

Definition NewQuantity {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.NewQuantity"%go.

Definition NewMilliQuantity {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.NewMilliQuantity"%go.

Definition NewScaledQuantity {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.NewScaledQuantity"%go.

Definition encodeVarintGenerated {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.encodeVarintGenerated"%go.

Definition sovGenerated {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.sovGenerated"%go.

Definition skipGenerated {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.skipGenerated"%go.

Definition scaledValue {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.scaledValue"%go.

Definition newSuffixer {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apimachinery/pkg/api/resource.newSuffixer"%go.

#[global] Instance info' : PkgInfo pkg_id.resource :=
{|
  pkg_imported_pkgs := []
|}.

Axiom _'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.resource (λ: <>,
      exception_do (do:  (Zero'init #());;;
      do:  (zeroBytes'init #());;;
      do:  (_'init #());;;
      do:  (_'init #());;;
      do:  (_'init #());;;
      do:  (fileDescriptor_7288c78ff45111e9'init #());;;
      do:  (bigTen'init #());;;
      do:  (bigZero'init #());;;
      do:  (bigOne'init #());;;
      do:  (bigThousand'init #());;;
      do:  (big1024'init #());;;
      do:  (decZero'init #());;;
      do:  (decOne'init #());;;
      do:  (maxAllowed'init #());;;
      do:  (MaxMilliValue'init #());;;
      do:  (ErrFormatWrong'init #());;;
      do:  (ErrNumeric'init #());;;
      do:  (ErrSuffix'init #());;;
      do:  (_'init #());;;
      do:  (ErrInvalidLengthGenerated'init #());;;
      do:  (ErrIntOverflowGenerated'init #());;;
      do:  (maxInt64'init #());;;
      do:  (quantitySuffixer'init #()))
      ).

Module Scale.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Scale.

Class Scale_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Scale_type_repr  :: go.TypeReprUnderlying Scaleⁱᵐᵖˡ Scale.t;
  #[global] Scale_underlying :: (Scale) <u (Scaleⁱᵐᵖˡ);
  #[global] Scaleⁱᵐᵖˡ_underlying :: (Scaleⁱᵐᵖˡ) ↓u (Scaleⁱᵐᵖˡ);
}.

Module int64Amount.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End int64Amount.

Class int64Amount_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] int64Amount_type_repr  :: go.TypeReprUnderlying int64Amountⁱᵐᵖˡ int64Amount.t;
  #[global] int64Amount_underlying :: (int64Amount) <u (int64Amountⁱᵐᵖˡ);
  #[global] int64Amountⁱᵐᵖˡ_underlying :: (int64Amountⁱᵐᵖˡ) ↓u (int64Amountⁱᵐᵖˡ);
}.

Module infDecAmount.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End infDecAmount.

Class infDecAmount_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] infDecAmount_type_repr  :: go.TypeReprUnderlying infDecAmountⁱᵐᵖˡ infDecAmount.t;
  #[global] infDecAmount_underlying :: (infDecAmount) <u (infDecAmountⁱᵐᵖˡ);
  #[global] infDecAmountⁱᵐᵖˡ_underlying :: (infDecAmountⁱᵐᵖˡ) ↓u (infDecAmountⁱᵐᵖˡ);
}.

Module Format.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Format.

Class Format_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Format_type_repr  :: go.TypeReprUnderlying Formatⁱᵐᵖˡ Format.t;
  #[global] Format_underlying :: (Format) <u (Formatⁱᵐᵖˡ);
  #[global] Formatⁱᵐᵖˡ_underlying :: (Formatⁱᵐᵖˡ) ↓u (Formatⁱᵐᵖˡ);
}.

Module Quantity.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  i' : resource.int64Amount.t;
  d' : resource.infDecAmount.t;
  s' : go_string;
  Format' : resource.Format.t;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _) (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.
End Quantity.

Definition Quantity'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "i"%go int64Amount);
  (go.FieldDecl "d"%go infDecAmount);
  (go.FieldDecl "s"%go go.string);
  (go.EmbeddedField "Format"%go Format)
].
Program Definition Quantity'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (Quantity'fds_unsealed).
Global Instance equals_unfold_Quantity {ext : ffi_syntax} {go_gctx : GoGlobalContext} : Quantity'fds =→ Quantity'fds_unsealed.
Proof. rewrite /Quantity'fds seal_eq //. Qed.

Definition Quantityⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (Quantity'fds).

Class Quantity_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Quantity_type_repr  :: go.TypeReprUnderlying Quantityⁱᵐᵖˡ Quantity.t;
  #[global] Quantity_underlying :: (Quantity) <u (Quantityⁱᵐᵖˡ);
  #[global] Quantity_get_i (x : Quantity.t) :: ⟦StructFieldGet (Quantityⁱᵐᵖˡ) "i", #x⟧ ⤳[under] #x.(Quantity.i');
  #[global] Quantity_set_i (x : Quantity.t) y :: ⟦StructFieldSet (Quantityⁱᵐᵖˡ) "i", (#x, #y)⟧ ⤳[under] #(x <|Quantity.i' := y|>);
  #[global] Quantity_get_d (x : Quantity.t) :: ⟦StructFieldGet (Quantityⁱᵐᵖˡ) "d", #x⟧ ⤳[under] #x.(Quantity.d');
  #[global] Quantity_set_d (x : Quantity.t) y :: ⟦StructFieldSet (Quantityⁱᵐᵖˡ) "d", (#x, #y)⟧ ⤳[under] #(x <|Quantity.d' := y|>);
  #[global] Quantity_get_s (x : Quantity.t) :: ⟦StructFieldGet (Quantityⁱᵐᵖˡ) "s", #x⟧ ⤳[under] #x.(Quantity.s');
  #[global] Quantity_set_s (x : Quantity.t) y :: ⟦StructFieldSet (Quantityⁱᵐᵖˡ) "s", (#x, #y)⟧ ⤳[under] #(x <|Quantity.s' := y|>);
  #[global] Quantity_get_Format (x : Quantity.t) :: ⟦StructFieldGet (Quantityⁱᵐᵖˡ) "Format", #x⟧ ⤳[under] #x.(Quantity.Format');
  #[global] Quantity_set_Format (x : Quantity.t) y :: ⟦StructFieldSet (Quantityⁱᵐᵖˡ) "Format", (#x, #y)⟧ ⤳[under] #(x <|Quantity.Format' := y|>);
}.

Module CanonicalValue.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End CanonicalValue.

Class CanonicalValue_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] CanonicalValue_type_repr  :: go.TypeReprUnderlying CanonicalValueⁱᵐᵖˡ CanonicalValue.t;
  #[global] CanonicalValue_underlying :: (CanonicalValue) <u (CanonicalValueⁱᵐᵖˡ);
  #[global] CanonicalValueⁱᵐᵖˡ_underlying :: (CanonicalValueⁱᵐᵖˡ) ↓u (CanonicalValueⁱᵐᵖˡ);
}.

Module QuantityValue.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End QuantityValue.

Class QuantityValue_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] QuantityValue_type_repr  :: go.TypeReprUnderlying QuantityValueⁱᵐᵖˡ QuantityValue.t;
  #[global] QuantityValue_underlying :: (QuantityValue) <u (QuantityValueⁱᵐᵖˡ);
  #[global] QuantityValueⁱᵐᵖˡ_underlying :: (QuantityValueⁱᵐᵖˡ) ↓u (QuantityValueⁱᵐᵖˡ);
}.

Module suffix.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End suffix.

Class suffix_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] suffix_type_repr  :: go.TypeReprUnderlying suffixⁱᵐᵖˡ suffix.t;
  #[global] suffix_underlying :: (suffix) <u (suffixⁱᵐᵖˡ);
  #[global] suffixⁱᵐᵖˡ_underlying :: (suffixⁱᵐᵖˡ) ↓u (suffixⁱᵐᵖˡ);
}.

Module suffixer.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End suffixer.

Class suffixer_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] suffixer_type_repr  :: go.TypeReprUnderlying suffixerⁱᵐᵖˡ suffixer.t;
  #[global] suffixer_underlying :: (suffixer) <u (suffixerⁱᵐᵖˡ);
  #[global] suffixerⁱᵐᵖˡ_underlying :: (suffixerⁱᵐᵖˡ) ↓u (suffixerⁱᵐᵖˡ);
}.

Module bePair.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End bePair.

Class bePair_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] bePair_type_repr  :: go.TypeReprUnderlying bePairⁱᵐᵖˡ bePair.t;
  #[global] bePair_underlying :: (bePair) <u (bePairⁱᵐᵖˡ);
  #[global] bePairⁱᵐᵖˡ_underlying :: (bePairⁱᵐᵖˡ) ↓u (bePairⁱᵐᵖˡ);
}.

Module listSuffixer.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End listSuffixer.

Class listSuffixer_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] listSuffixer_type_repr  :: go.TypeReprUnderlying listSuffixerⁱᵐᵖˡ listSuffixer.t;
  #[global] listSuffixer_underlying :: (listSuffixer) <u (listSuffixerⁱᵐᵖˡ);
  #[global] listSuffixerⁱᵐᵖˡ_underlying :: (listSuffixerⁱᵐᵖˡ) ↓u (listSuffixerⁱᵐᵖˡ);
}.

Module suffixHandler.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End suffixHandler.

Class suffixHandler_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] suffixHandler_type_repr  :: go.TypeReprUnderlying suffixHandlerⁱᵐᵖˡ suffixHandler.t;
  #[global] suffixHandler_underlying :: (suffixHandler) <u (suffixHandlerⁱᵐᵖˡ);
  #[global] suffixHandlerⁱᵐᵖˡ_underlying :: (suffixHandlerⁱᵐᵖˡ) ↓u (suffixHandlerⁱᵐᵖˡ);
}.

Module fastLookup.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End fastLookup.

Class fastLookup_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] fastLookup_type_repr  :: go.TypeReprUnderlying fastLookupⁱᵐᵖˡ fastLookup.t;
  #[global] fastLookup_underlying :: (fastLookup) <u (fastLookupⁱᵐᵖˡ);
  #[global] fastLookupⁱᵐᵖˡ_underlying :: (fastLookupⁱᵐᵖˡ) ↓u (fastLookupⁱᵐᵖˡ);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Scale_instance :: Scale_Assumptions;
  #[global] int64Amount_instance :: int64Amount_Assumptions;
  #[global] infDecAmount_instance :: infDecAmount_Assumptions;
  #[global] Quantity_instance :: Quantity_Assumptions;
  #[global] CanonicalValue_instance :: CanonicalValue_Assumptions;
  #[global] Format_instance :: Format_Assumptions;
  #[global] QuantityValue_instance :: QuantityValue_Assumptions;
  #[global] suffix_instance :: suffix_Assumptions;
  #[global] suffixer_instance :: suffixer_Assumptions;
  #[global] bePair_instance :: bePair_Assumptions;
  #[global] listSuffixer_instance :: listSuffixer_Assumptions;
  #[global] suffixHandler_instance :: suffixHandler_Assumptions;
  #[global] fastLookup_instance :: fastLookup_Assumptions;
}.
End resource.
