translate = [
    "ReplicaSet",
    "ReplicaSetSpec",
    "ReplicaSetStatus",
    "ReplicaSetCondition",
    "ReplicaSetConditionType",
]

imports = [
    "k8s.io/apimachinery/pkg/apis/meta/v1",
    "k8s.io/api/core/v1",
]
