translate = [
    "state'init",
    "_'init",
    "KKey",
    "IndexFunc",
    "Indexers",
    "NamespaceIndex",
    "PodControllerUIDIndex",
    "OrphanPodIndexKey",
    "State",
    "Init",
    "namespaceIndex",
    "podControllerUIDIndex",
    "OrphanPodIndexKeyForNamespace",
    "Get",
    "List",
    "filterByLabelSelector",
    "ListBySelector",
    "Index",
    "ByIndex",
    "Create",
    "Update",
    "Delete",
    "PodGet",
    "PodDelete",
]
