(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.k8s_io.apimachinery.pkg.runtime.schema.
Require Export New.generatedproof.k8s_io.apimachinery.pkg.types.
Require Export New.generatedproof.k8s_io.utils.ptr.
Require Export New.generatedproof.time.
Require Export New.golang.theory.
Require Export New.code.k8s_io.apimachinery.pkg.apis.meta.v1.

Set Default Proof Using "Type".

Module v1.
Module Duration.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Duration_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.Duration.t). Admitted.

#[global] Instance Duration_into_val_typed
   :
  IntoValTypedUnderlying (v1.Duration.t) (v1.Durationⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Duration.

Module GroupResource.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance GroupResource_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.GroupResource.t). Admitted.

#[global] Instance GroupResource_into_val_typed
   :
  IntoValTypedUnderlying (v1.GroupResource.t) (v1.GroupResourceⁱᵐᵖˡ).
Proof. Admitted.

End def.
End GroupResource.

Module GroupVersionResource.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance GroupVersionResource_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.GroupVersionResource.t). Admitted.

#[global] Instance GroupVersionResource_into_val_typed
   :
  IntoValTypedUnderlying (v1.GroupVersionResource.t) (v1.GroupVersionResourceⁱᵐᵖˡ).
Proof. Admitted.

End def.
End GroupVersionResource.

Module GroupKind.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance GroupKind_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.GroupKind.t). Admitted.

#[global] Instance GroupKind_into_val_typed
   :
  IntoValTypedUnderlying (v1.GroupKind.t) (v1.GroupKindⁱᵐᵖˡ).
Proof. Admitted.

End def.
End GroupKind.

Module GroupVersionKind.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance GroupVersionKind_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.GroupVersionKind.t). Admitted.

#[global] Instance GroupVersionKind_into_val_typed
   :
  IntoValTypedUnderlying (v1.GroupVersionKind.t) (v1.GroupVersionKindⁱᵐᵖˡ).
Proof. Admitted.

End def.
End GroupVersionKind.

Module GroupVersion.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance GroupVersion_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.GroupVersion.t). Admitted.

#[global] Instance GroupVersion_into_val_typed
   :
  IntoValTypedUnderlying (v1.GroupVersion.t) (v1.GroupVersionⁱᵐᵖˡ).
Proof. Admitted.

End def.
End GroupVersion.

Module ObjectMetaAccessor.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance ObjectMetaAccessor_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.ObjectMetaAccessor.t). Admitted.

#[global] Instance ObjectMetaAccessor_into_val_typed
   :
  IntoValTypedUnderlying (v1.ObjectMetaAccessor.t) (v1.ObjectMetaAccessorⁱᵐᵖˡ).
Proof. Admitted.

End def.
End ObjectMetaAccessor.

Module ListMetaAccessor.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance ListMetaAccessor_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.ListMetaAccessor.t). Admitted.

#[global] Instance ListMetaAccessor_into_val_typed
   :
  IntoValTypedUnderlying (v1.ListMetaAccessor.t) (v1.ListMetaAccessorⁱᵐᵖˡ).
Proof. Admitted.

End def.
End ListMetaAccessor.

Module Common.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Common_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.Common.t). Admitted.

#[global] Instance Common_into_val_typed
   :
  IntoValTypedUnderlying (v1.Common.t) (v1.Commonⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Common.

Module ListInterface.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance ListInterface_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.ListInterface.t). Admitted.

#[global] Instance ListInterface_into_val_typed
   :
  IntoValTypedUnderlying (v1.ListInterface.t) (v1.ListInterfaceⁱᵐᵖˡ).
Proof. Admitted.

End def.
End ListInterface.

Module Type'.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Type'_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.Type'.t). Admitted.

#[global] Instance Type'_into_val_typed
   :
  IntoValTypedUnderlying (v1.Type'.t) (v1.Type'ⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Type'.

Module MicroTime.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance MicroTime_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.MicroTime.t). Admitted.

#[global] Instance MicroTime_into_val_typed
   :
  IntoValTypedUnderlying (v1.MicroTime.t) (v1.MicroTimeⁱᵐᵖˡ).
Proof. Admitted.

End def.
End MicroTime.

Module Time.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance Time_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.Time.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "Time" ∷ l.[(v1.Time.t), "Time"] ↦{dq} v.(v1.Time.Time') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance Time_into_val_typed
   :
  IntoValTypedUnderlying (v1.Time.t) (v1.Timeⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance Time_access_load_Time l (v : (v1.Time.t)) dq :
  AccessStrict
    (l.[(v1.Time.t), "Time"] ↦{dq} (v.(v1.Time.Time')))
    (l.[(v1.Time.t), "Time"] ↦{dq} (v.(v1.Time.Time')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Time_access_store_Time l (v : (v1.Time.t)) Time' :
  AccessStrict
    (l.[(v1.Time.t), "Time"] ↦ (v.(v1.Time.Time')))
    (l.[(v1.Time.t), "Time"] ↦ Time')
    (l ↦ v) (l ↦ (v <|(v1.Time.Time') := Time'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End Time.

Module Timestamp.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Timestamp_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.Timestamp.t). Admitted.

#[global] Instance Timestamp_into_val_typed
   :
  IntoValTypedUnderlying (v1.Timestamp.t) (v1.Timestampⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Timestamp.

Module TypeMeta.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance TypeMeta_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.TypeMeta.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "Kind" ∷ l.[(v1.TypeMeta.t), "Kind"] ↦{dq} v.(v1.TypeMeta.Kind') ∗
      "APIVersion" ∷ l.[(v1.TypeMeta.t), "APIVersion"] ↦{dq} v.(v1.TypeMeta.APIVersion') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance TypeMeta_into_val_typed
   :
  IntoValTypedUnderlying (v1.TypeMeta.t) (v1.TypeMetaⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance TypeMeta_access_load_Kind l (v : (v1.TypeMeta.t)) dq :
  AccessStrict
    (l.[(v1.TypeMeta.t), "Kind"] ↦{dq} (v.(v1.TypeMeta.Kind')))
    (l.[(v1.TypeMeta.t), "Kind"] ↦{dq} (v.(v1.TypeMeta.Kind')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance TypeMeta_access_store_Kind l (v : (v1.TypeMeta.t)) Kind' :
  AccessStrict
    (l.[(v1.TypeMeta.t), "Kind"] ↦ (v.(v1.TypeMeta.Kind')))
    (l.[(v1.TypeMeta.t), "Kind"] ↦ Kind')
    (l ↦ v) (l ↦ (v <|(v1.TypeMeta.Kind') := Kind'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance TypeMeta_access_load_APIVersion l (v : (v1.TypeMeta.t)) dq :
  AccessStrict
    (l.[(v1.TypeMeta.t), "APIVersion"] ↦{dq} (v.(v1.TypeMeta.APIVersion')))
    (l.[(v1.TypeMeta.t), "APIVersion"] ↦{dq} (v.(v1.TypeMeta.APIVersion')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance TypeMeta_access_store_APIVersion l (v : (v1.TypeMeta.t)) APIVersion' :
  AccessStrict
    (l.[(v1.TypeMeta.t), "APIVersion"] ↦ (v.(v1.TypeMeta.APIVersion')))
    (l.[(v1.TypeMeta.t), "APIVersion"] ↦ APIVersion')
    (l ↦ v) (l ↦ (v <|(v1.TypeMeta.APIVersion') := APIVersion'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End TypeMeta.

Module ListMeta.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance ListMeta_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.ListMeta.t). Admitted.

#[global] Instance ListMeta_into_val_typed
   :
  IntoValTypedUnderlying (v1.ListMeta.t) (v1.ListMetaⁱᵐᵖˡ).
Proof. Admitted.

End def.
End ListMeta.

Module ObjectMeta.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance ObjectMeta_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.ObjectMeta.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "Name" ∷ l.[(v1.ObjectMeta.t), "Name"] ↦{dq} v.(v1.ObjectMeta.Name') ∗
      "GenerateName" ∷ l.[(v1.ObjectMeta.t), "GenerateName"] ↦{dq} v.(v1.ObjectMeta.GenerateName') ∗
      "Namespace" ∷ l.[(v1.ObjectMeta.t), "Namespace"] ↦{dq} v.(v1.ObjectMeta.Namespace') ∗
      "SelfLink" ∷ l.[(v1.ObjectMeta.t), "SelfLink"] ↦{dq} v.(v1.ObjectMeta.SelfLink') ∗
      "UID" ∷ l.[(v1.ObjectMeta.t), "UID"] ↦{dq} v.(v1.ObjectMeta.UID') ∗
      "ResourceVersion" ∷ l.[(v1.ObjectMeta.t), "ResourceVersion"] ↦{dq} v.(v1.ObjectMeta.ResourceVersion') ∗
      "Generation" ∷ l.[(v1.ObjectMeta.t), "Generation"] ↦{dq} v.(v1.ObjectMeta.Generation') ∗
      "CreationTimestamp" ∷ l.[(v1.ObjectMeta.t), "CreationTimestamp"] ↦{dq} v.(v1.ObjectMeta.CreationTimestamp') ∗
      "DeletionTimestamp" ∷ l.[(v1.ObjectMeta.t), "DeletionTimestamp"] ↦{dq} v.(v1.ObjectMeta.DeletionTimestamp') ∗
      "DeletionGracePeriodSeconds" ∷ l.[(v1.ObjectMeta.t), "DeletionGracePeriodSeconds"] ↦{dq} v.(v1.ObjectMeta.DeletionGracePeriodSeconds') ∗
      "Labels" ∷ l.[(v1.ObjectMeta.t), "Labels"] ↦{dq} v.(v1.ObjectMeta.Labels') ∗
      "Annotations" ∷ l.[(v1.ObjectMeta.t), "Annotations"] ↦{dq} v.(v1.ObjectMeta.Annotations') ∗
      "OwnerReferences" ∷ l.[(v1.ObjectMeta.t), "OwnerReferences"] ↦{dq} v.(v1.ObjectMeta.OwnerReferences') ∗
      "Finalizers" ∷ l.[(v1.ObjectMeta.t), "Finalizers"] ↦{dq} v.(v1.ObjectMeta.Finalizers') ∗
      "ManagedFields" ∷ l.[(v1.ObjectMeta.t), "ManagedFields"] ↦{dq} v.(v1.ObjectMeta.ManagedFields') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance ObjectMeta_into_val_typed
   :
  IntoValTypedUnderlying (v1.ObjectMeta.t) (v1.ObjectMetaⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance ObjectMeta_access_load_Name l (v : (v1.ObjectMeta.t)) dq :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "Name"] ↦{dq} (v.(v1.ObjectMeta.Name')))
    (l.[(v1.ObjectMeta.t), "Name"] ↦{dq} (v.(v1.ObjectMeta.Name')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ObjectMeta_access_store_Name l (v : (v1.ObjectMeta.t)) Name' :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "Name"] ↦ (v.(v1.ObjectMeta.Name')))
    (l.[(v1.ObjectMeta.t), "Name"] ↦ Name')
    (l ↦ v) (l ↦ (v <|(v1.ObjectMeta.Name') := Name'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ObjectMeta_access_load_GenerateName l (v : (v1.ObjectMeta.t)) dq :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "GenerateName"] ↦{dq} (v.(v1.ObjectMeta.GenerateName')))
    (l.[(v1.ObjectMeta.t), "GenerateName"] ↦{dq} (v.(v1.ObjectMeta.GenerateName')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ObjectMeta_access_store_GenerateName l (v : (v1.ObjectMeta.t)) GenerateName' :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "GenerateName"] ↦ (v.(v1.ObjectMeta.GenerateName')))
    (l.[(v1.ObjectMeta.t), "GenerateName"] ↦ GenerateName')
    (l ↦ v) (l ↦ (v <|(v1.ObjectMeta.GenerateName') := GenerateName'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ObjectMeta_access_load_Namespace l (v : (v1.ObjectMeta.t)) dq :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "Namespace"] ↦{dq} (v.(v1.ObjectMeta.Namespace')))
    (l.[(v1.ObjectMeta.t), "Namespace"] ↦{dq} (v.(v1.ObjectMeta.Namespace')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ObjectMeta_access_store_Namespace l (v : (v1.ObjectMeta.t)) Namespace' :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "Namespace"] ↦ (v.(v1.ObjectMeta.Namespace')))
    (l.[(v1.ObjectMeta.t), "Namespace"] ↦ Namespace')
    (l ↦ v) (l ↦ (v <|(v1.ObjectMeta.Namespace') := Namespace'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ObjectMeta_access_load_SelfLink l (v : (v1.ObjectMeta.t)) dq :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "SelfLink"] ↦{dq} (v.(v1.ObjectMeta.SelfLink')))
    (l.[(v1.ObjectMeta.t), "SelfLink"] ↦{dq} (v.(v1.ObjectMeta.SelfLink')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ObjectMeta_access_store_SelfLink l (v : (v1.ObjectMeta.t)) SelfLink' :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "SelfLink"] ↦ (v.(v1.ObjectMeta.SelfLink')))
    (l.[(v1.ObjectMeta.t), "SelfLink"] ↦ SelfLink')
    (l ↦ v) (l ↦ (v <|(v1.ObjectMeta.SelfLink') := SelfLink'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ObjectMeta_access_load_UID l (v : (v1.ObjectMeta.t)) dq :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "UID"] ↦{dq} (v.(v1.ObjectMeta.UID')))
    (l.[(v1.ObjectMeta.t), "UID"] ↦{dq} (v.(v1.ObjectMeta.UID')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ObjectMeta_access_store_UID l (v : (v1.ObjectMeta.t)) UID' :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "UID"] ↦ (v.(v1.ObjectMeta.UID')))
    (l.[(v1.ObjectMeta.t), "UID"] ↦ UID')
    (l ↦ v) (l ↦ (v <|(v1.ObjectMeta.UID') := UID'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ObjectMeta_access_load_ResourceVersion l (v : (v1.ObjectMeta.t)) dq :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "ResourceVersion"] ↦{dq} (v.(v1.ObjectMeta.ResourceVersion')))
    (l.[(v1.ObjectMeta.t), "ResourceVersion"] ↦{dq} (v.(v1.ObjectMeta.ResourceVersion')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ObjectMeta_access_store_ResourceVersion l (v : (v1.ObjectMeta.t)) ResourceVersion' :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "ResourceVersion"] ↦ (v.(v1.ObjectMeta.ResourceVersion')))
    (l.[(v1.ObjectMeta.t), "ResourceVersion"] ↦ ResourceVersion')
    (l ↦ v) (l ↦ (v <|(v1.ObjectMeta.ResourceVersion') := ResourceVersion'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ObjectMeta_access_load_Generation l (v : (v1.ObjectMeta.t)) dq :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "Generation"] ↦{dq} (v.(v1.ObjectMeta.Generation')))
    (l.[(v1.ObjectMeta.t), "Generation"] ↦{dq} (v.(v1.ObjectMeta.Generation')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ObjectMeta_access_store_Generation l (v : (v1.ObjectMeta.t)) Generation' :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "Generation"] ↦ (v.(v1.ObjectMeta.Generation')))
    (l.[(v1.ObjectMeta.t), "Generation"] ↦ Generation')
    (l ↦ v) (l ↦ (v <|(v1.ObjectMeta.Generation') := Generation'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ObjectMeta_access_load_CreationTimestamp l (v : (v1.ObjectMeta.t)) dq :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "CreationTimestamp"] ↦{dq} (v.(v1.ObjectMeta.CreationTimestamp')))
    (l.[(v1.ObjectMeta.t), "CreationTimestamp"] ↦{dq} (v.(v1.ObjectMeta.CreationTimestamp')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ObjectMeta_access_store_CreationTimestamp l (v : (v1.ObjectMeta.t)) CreationTimestamp' :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "CreationTimestamp"] ↦ (v.(v1.ObjectMeta.CreationTimestamp')))
    (l.[(v1.ObjectMeta.t), "CreationTimestamp"] ↦ CreationTimestamp')
    (l ↦ v) (l ↦ (v <|(v1.ObjectMeta.CreationTimestamp') := CreationTimestamp'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ObjectMeta_access_load_DeletionTimestamp l (v : (v1.ObjectMeta.t)) dq :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "DeletionTimestamp"] ↦{dq} (v.(v1.ObjectMeta.DeletionTimestamp')))
    (l.[(v1.ObjectMeta.t), "DeletionTimestamp"] ↦{dq} (v.(v1.ObjectMeta.DeletionTimestamp')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ObjectMeta_access_store_DeletionTimestamp l (v : (v1.ObjectMeta.t)) DeletionTimestamp' :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "DeletionTimestamp"] ↦ (v.(v1.ObjectMeta.DeletionTimestamp')))
    (l.[(v1.ObjectMeta.t), "DeletionTimestamp"] ↦ DeletionTimestamp')
    (l ↦ v) (l ↦ (v <|(v1.ObjectMeta.DeletionTimestamp') := DeletionTimestamp'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ObjectMeta_access_load_DeletionGracePeriodSeconds l (v : (v1.ObjectMeta.t)) dq :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "DeletionGracePeriodSeconds"] ↦{dq} (v.(v1.ObjectMeta.DeletionGracePeriodSeconds')))
    (l.[(v1.ObjectMeta.t), "DeletionGracePeriodSeconds"] ↦{dq} (v.(v1.ObjectMeta.DeletionGracePeriodSeconds')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ObjectMeta_access_store_DeletionGracePeriodSeconds l (v : (v1.ObjectMeta.t)) DeletionGracePeriodSeconds' :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "DeletionGracePeriodSeconds"] ↦ (v.(v1.ObjectMeta.DeletionGracePeriodSeconds')))
    (l.[(v1.ObjectMeta.t), "DeletionGracePeriodSeconds"] ↦ DeletionGracePeriodSeconds')
    (l ↦ v) (l ↦ (v <|(v1.ObjectMeta.DeletionGracePeriodSeconds') := DeletionGracePeriodSeconds'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ObjectMeta_access_load_Labels l (v : (v1.ObjectMeta.t)) dq :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "Labels"] ↦{dq} (v.(v1.ObjectMeta.Labels')))
    (l.[(v1.ObjectMeta.t), "Labels"] ↦{dq} (v.(v1.ObjectMeta.Labels')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ObjectMeta_access_store_Labels l (v : (v1.ObjectMeta.t)) Labels' :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "Labels"] ↦ (v.(v1.ObjectMeta.Labels')))
    (l.[(v1.ObjectMeta.t), "Labels"] ↦ Labels')
    (l ↦ v) (l ↦ (v <|(v1.ObjectMeta.Labels') := Labels'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ObjectMeta_access_load_Annotations l (v : (v1.ObjectMeta.t)) dq :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "Annotations"] ↦{dq} (v.(v1.ObjectMeta.Annotations')))
    (l.[(v1.ObjectMeta.t), "Annotations"] ↦{dq} (v.(v1.ObjectMeta.Annotations')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ObjectMeta_access_store_Annotations l (v : (v1.ObjectMeta.t)) Annotations' :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "Annotations"] ↦ (v.(v1.ObjectMeta.Annotations')))
    (l.[(v1.ObjectMeta.t), "Annotations"] ↦ Annotations')
    (l ↦ v) (l ↦ (v <|(v1.ObjectMeta.Annotations') := Annotations'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ObjectMeta_access_load_OwnerReferences l (v : (v1.ObjectMeta.t)) dq :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "OwnerReferences"] ↦{dq} (v.(v1.ObjectMeta.OwnerReferences')))
    (l.[(v1.ObjectMeta.t), "OwnerReferences"] ↦{dq} (v.(v1.ObjectMeta.OwnerReferences')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ObjectMeta_access_store_OwnerReferences l (v : (v1.ObjectMeta.t)) OwnerReferences' :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "OwnerReferences"] ↦ (v.(v1.ObjectMeta.OwnerReferences')))
    (l.[(v1.ObjectMeta.t), "OwnerReferences"] ↦ OwnerReferences')
    (l ↦ v) (l ↦ (v <|(v1.ObjectMeta.OwnerReferences') := OwnerReferences'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ObjectMeta_access_load_Finalizers l (v : (v1.ObjectMeta.t)) dq :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "Finalizers"] ↦{dq} (v.(v1.ObjectMeta.Finalizers')))
    (l.[(v1.ObjectMeta.t), "Finalizers"] ↦{dq} (v.(v1.ObjectMeta.Finalizers')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ObjectMeta_access_store_Finalizers l (v : (v1.ObjectMeta.t)) Finalizers' :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "Finalizers"] ↦ (v.(v1.ObjectMeta.Finalizers')))
    (l.[(v1.ObjectMeta.t), "Finalizers"] ↦ Finalizers')
    (l ↦ v) (l ↦ (v <|(v1.ObjectMeta.Finalizers') := Finalizers'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ObjectMeta_access_load_ManagedFields l (v : (v1.ObjectMeta.t)) dq :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "ManagedFields"] ↦{dq} (v.(v1.ObjectMeta.ManagedFields')))
    (l.[(v1.ObjectMeta.t), "ManagedFields"] ↦{dq} (v.(v1.ObjectMeta.ManagedFields')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ObjectMeta_access_store_ManagedFields l (v : (v1.ObjectMeta.t)) ManagedFields' :
  AccessStrict
    (l.[(v1.ObjectMeta.t), "ManagedFields"] ↦ (v.(v1.ObjectMeta.ManagedFields')))
    (l.[(v1.ObjectMeta.t), "ManagedFields"] ↦ ManagedFields')
    (l ↦ v) (l ↦ (v <|(v1.ObjectMeta.ManagedFields') := ManagedFields'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End ObjectMeta.

Module OwnerReference.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance OwnerReference_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.OwnerReference.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "APIVersion" ∷ l.[(v1.OwnerReference.t), "APIVersion"] ↦{dq} v.(v1.OwnerReference.APIVersion') ∗
      "Kind" ∷ l.[(v1.OwnerReference.t), "Kind"] ↦{dq} v.(v1.OwnerReference.Kind') ∗
      "Name" ∷ l.[(v1.OwnerReference.t), "Name"] ↦{dq} v.(v1.OwnerReference.Name') ∗
      "UID" ∷ l.[(v1.OwnerReference.t), "UID"] ↦{dq} v.(v1.OwnerReference.UID') ∗
      "Controller" ∷ l.[(v1.OwnerReference.t), "Controller"] ↦{dq} v.(v1.OwnerReference.Controller') ∗
      "BlockOwnerDeletion" ∷ l.[(v1.OwnerReference.t), "BlockOwnerDeletion"] ↦{dq} v.(v1.OwnerReference.BlockOwnerDeletion') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance OwnerReference_into_val_typed
   :
  IntoValTypedUnderlying (v1.OwnerReference.t) (v1.OwnerReferenceⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance OwnerReference_access_load_APIVersion l (v : (v1.OwnerReference.t)) dq :
  AccessStrict
    (l.[(v1.OwnerReference.t), "APIVersion"] ↦{dq} (v.(v1.OwnerReference.APIVersion')))
    (l.[(v1.OwnerReference.t), "APIVersion"] ↦{dq} (v.(v1.OwnerReference.APIVersion')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance OwnerReference_access_store_APIVersion l (v : (v1.OwnerReference.t)) APIVersion' :
  AccessStrict
    (l.[(v1.OwnerReference.t), "APIVersion"] ↦ (v.(v1.OwnerReference.APIVersion')))
    (l.[(v1.OwnerReference.t), "APIVersion"] ↦ APIVersion')
    (l ↦ v) (l ↦ (v <|(v1.OwnerReference.APIVersion') := APIVersion'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance OwnerReference_access_load_Kind l (v : (v1.OwnerReference.t)) dq :
  AccessStrict
    (l.[(v1.OwnerReference.t), "Kind"] ↦{dq} (v.(v1.OwnerReference.Kind')))
    (l.[(v1.OwnerReference.t), "Kind"] ↦{dq} (v.(v1.OwnerReference.Kind')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance OwnerReference_access_store_Kind l (v : (v1.OwnerReference.t)) Kind' :
  AccessStrict
    (l.[(v1.OwnerReference.t), "Kind"] ↦ (v.(v1.OwnerReference.Kind')))
    (l.[(v1.OwnerReference.t), "Kind"] ↦ Kind')
    (l ↦ v) (l ↦ (v <|(v1.OwnerReference.Kind') := Kind'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance OwnerReference_access_load_Name l (v : (v1.OwnerReference.t)) dq :
  AccessStrict
    (l.[(v1.OwnerReference.t), "Name"] ↦{dq} (v.(v1.OwnerReference.Name')))
    (l.[(v1.OwnerReference.t), "Name"] ↦{dq} (v.(v1.OwnerReference.Name')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance OwnerReference_access_store_Name l (v : (v1.OwnerReference.t)) Name' :
  AccessStrict
    (l.[(v1.OwnerReference.t), "Name"] ↦ (v.(v1.OwnerReference.Name')))
    (l.[(v1.OwnerReference.t), "Name"] ↦ Name')
    (l ↦ v) (l ↦ (v <|(v1.OwnerReference.Name') := Name'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance OwnerReference_access_load_UID l (v : (v1.OwnerReference.t)) dq :
  AccessStrict
    (l.[(v1.OwnerReference.t), "UID"] ↦{dq} (v.(v1.OwnerReference.UID')))
    (l.[(v1.OwnerReference.t), "UID"] ↦{dq} (v.(v1.OwnerReference.UID')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance OwnerReference_access_store_UID l (v : (v1.OwnerReference.t)) UID' :
  AccessStrict
    (l.[(v1.OwnerReference.t), "UID"] ↦ (v.(v1.OwnerReference.UID')))
    (l.[(v1.OwnerReference.t), "UID"] ↦ UID')
    (l ↦ v) (l ↦ (v <|(v1.OwnerReference.UID') := UID'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance OwnerReference_access_load_Controller l (v : (v1.OwnerReference.t)) dq :
  AccessStrict
    (l.[(v1.OwnerReference.t), "Controller"] ↦{dq} (v.(v1.OwnerReference.Controller')))
    (l.[(v1.OwnerReference.t), "Controller"] ↦{dq} (v.(v1.OwnerReference.Controller')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance OwnerReference_access_store_Controller l (v : (v1.OwnerReference.t)) Controller' :
  AccessStrict
    (l.[(v1.OwnerReference.t), "Controller"] ↦ (v.(v1.OwnerReference.Controller')))
    (l.[(v1.OwnerReference.t), "Controller"] ↦ Controller')
    (l ↦ v) (l ↦ (v <|(v1.OwnerReference.Controller') := Controller'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance OwnerReference_access_load_BlockOwnerDeletion l (v : (v1.OwnerReference.t)) dq :
  AccessStrict
    (l.[(v1.OwnerReference.t), "BlockOwnerDeletion"] ↦{dq} (v.(v1.OwnerReference.BlockOwnerDeletion')))
    (l.[(v1.OwnerReference.t), "BlockOwnerDeletion"] ↦{dq} (v.(v1.OwnerReference.BlockOwnerDeletion')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance OwnerReference_access_store_BlockOwnerDeletion l (v : (v1.OwnerReference.t)) BlockOwnerDeletion' :
  AccessStrict
    (l.[(v1.OwnerReference.t), "BlockOwnerDeletion"] ↦ (v.(v1.OwnerReference.BlockOwnerDeletion')))
    (l.[(v1.OwnerReference.t), "BlockOwnerDeletion"] ↦ BlockOwnerDeletion')
    (l ↦ v) (l ↦ (v <|(v1.OwnerReference.BlockOwnerDeletion') := BlockOwnerDeletion'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End OwnerReference.

Module ListOptions.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance ListOptions_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.ListOptions.t). Admitted.

#[global] Instance ListOptions_into_val_typed
   :
  IntoValTypedUnderlying (v1.ListOptions.t) (v1.ListOptionsⁱᵐᵖˡ).
Proof. Admitted.

End def.
End ListOptions.

Module ResourceVersionMatch.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance ResourceVersionMatch_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.ResourceVersionMatch.t). Admitted.

#[global] Instance ResourceVersionMatch_into_val_typed
   :
  IntoValTypedUnderlying (v1.ResourceVersionMatch.t) (v1.ResourceVersionMatchⁱᵐᵖˡ).
Proof. Admitted.

End def.
End ResourceVersionMatch.

Module GetOptions.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance GetOptions_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.GetOptions.t). Admitted.

#[global] Instance GetOptions_into_val_typed
   :
  IntoValTypedUnderlying (v1.GetOptions.t) (v1.GetOptionsⁱᵐᵖˡ).
Proof. Admitted.

End def.
End GetOptions.

Module DeletionPropagation.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance DeletionPropagation_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.DeletionPropagation.t). Admitted.

#[global] Instance DeletionPropagation_into_val_typed
   :
  IntoValTypedUnderlying (v1.DeletionPropagation.t) (v1.DeletionPropagationⁱᵐᵖˡ).
Proof. Admitted.

End def.
End DeletionPropagation.

Module DeleteOptions.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance DeleteOptions_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.DeleteOptions.t). Admitted.

#[global] Instance DeleteOptions_into_val_typed
   :
  IntoValTypedUnderlying (v1.DeleteOptions.t) (v1.DeleteOptionsⁱᵐᵖˡ).
Proof. Admitted.

End def.
End DeleteOptions.

Module CreateOptions.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance CreateOptions_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.CreateOptions.t). Admitted.

#[global] Instance CreateOptions_into_val_typed
   :
  IntoValTypedUnderlying (v1.CreateOptions.t) (v1.CreateOptionsⁱᵐᵖˡ).
Proof. Admitted.

End def.
End CreateOptions.

Module PatchOptions.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance PatchOptions_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.PatchOptions.t). Admitted.

#[global] Instance PatchOptions_into_val_typed
   :
  IntoValTypedUnderlying (v1.PatchOptions.t) (v1.PatchOptionsⁱᵐᵖˡ).
Proof. Admitted.

End def.
End PatchOptions.

Module ApplyOptions.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance ApplyOptions_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.ApplyOptions.t). Admitted.

#[global] Instance ApplyOptions_into_val_typed
   :
  IntoValTypedUnderlying (v1.ApplyOptions.t) (v1.ApplyOptionsⁱᵐᵖˡ).
Proof. Admitted.

End def.
End ApplyOptions.

Module UpdateOptions.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance UpdateOptions_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.UpdateOptions.t). Admitted.

#[global] Instance UpdateOptions_into_val_typed
   :
  IntoValTypedUnderlying (v1.UpdateOptions.t) (v1.UpdateOptionsⁱᵐᵖˡ).
Proof. Admitted.

End def.
End UpdateOptions.

Module Preconditions.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Preconditions_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.Preconditions.t). Admitted.

#[global] Instance Preconditions_into_val_typed
   :
  IntoValTypedUnderlying (v1.Preconditions.t) (v1.Preconditionsⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Preconditions.

Module Status.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Status_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.Status.t). Admitted.

#[global] Instance Status_into_val_typed
   :
  IntoValTypedUnderlying (v1.Status.t) (v1.Statusⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Status.

Module StatusDetails.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance StatusDetails_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.StatusDetails.t). Admitted.

#[global] Instance StatusDetails_into_val_typed
   :
  IntoValTypedUnderlying (v1.StatusDetails.t) (v1.StatusDetailsⁱᵐᵖˡ).
Proof. Admitted.

End def.
End StatusDetails.

Module StatusReason.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance StatusReason_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.StatusReason.t). Admitted.

#[global] Instance StatusReason_into_val_typed
   :
  IntoValTypedUnderlying (v1.StatusReason.t) (v1.StatusReasonⁱᵐᵖˡ).
Proof. Admitted.

End def.
End StatusReason.

Module StatusCause.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance StatusCause_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.StatusCause.t). Admitted.

#[global] Instance StatusCause_into_val_typed
   :
  IntoValTypedUnderlying (v1.StatusCause.t) (v1.StatusCauseⁱᵐᵖˡ).
Proof. Admitted.

End def.
End StatusCause.

Module CauseType.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance CauseType_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.CauseType.t). Admitted.

#[global] Instance CauseType_into_val_typed
   :
  IntoValTypedUnderlying (v1.CauseType.t) (v1.CauseTypeⁱᵐᵖˡ).
Proof. Admitted.

End def.
End CauseType.

Module List.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance List_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.List.t). Admitted.

#[global] Instance List_into_val_typed
   :
  IntoValTypedUnderlying (v1.List.t) (v1.Listⁱᵐᵖˡ).
Proof. Admitted.

End def.
End List.

Module APIVersions.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance APIVersions_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.APIVersions.t). Admitted.

#[global] Instance APIVersions_into_val_typed
   :
  IntoValTypedUnderlying (v1.APIVersions.t) (v1.APIVersionsⁱᵐᵖˡ).
Proof. Admitted.

End def.
End APIVersions.

Module APIGroupList.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance APIGroupList_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.APIGroupList.t). Admitted.

#[global] Instance APIGroupList_into_val_typed
   :
  IntoValTypedUnderlying (v1.APIGroupList.t) (v1.APIGroupListⁱᵐᵖˡ).
Proof. Admitted.

End def.
End APIGroupList.

Module APIGroup.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance APIGroup_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.APIGroup.t). Admitted.

#[global] Instance APIGroup_into_val_typed
   :
  IntoValTypedUnderlying (v1.APIGroup.t) (v1.APIGroupⁱᵐᵖˡ).
Proof. Admitted.

End def.
End APIGroup.

Module ServerAddressByClientCIDR.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance ServerAddressByClientCIDR_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.ServerAddressByClientCIDR.t). Admitted.

#[global] Instance ServerAddressByClientCIDR_into_val_typed
   :
  IntoValTypedUnderlying (v1.ServerAddressByClientCIDR.t) (v1.ServerAddressByClientCIDRⁱᵐᵖˡ).
Proof. Admitted.

End def.
End ServerAddressByClientCIDR.

Module GroupVersionForDiscovery.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance GroupVersionForDiscovery_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.GroupVersionForDiscovery.t). Admitted.

#[global] Instance GroupVersionForDiscovery_into_val_typed
   :
  IntoValTypedUnderlying (v1.GroupVersionForDiscovery.t) (v1.GroupVersionForDiscoveryⁱᵐᵖˡ).
Proof. Admitted.

End def.
End GroupVersionForDiscovery.

Module APIResource.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance APIResource_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.APIResource.t). Admitted.

#[global] Instance APIResource_into_val_typed
   :
  IntoValTypedUnderlying (v1.APIResource.t) (v1.APIResourceⁱᵐᵖˡ).
Proof. Admitted.

End def.
End APIResource.

Module Verbs.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Verbs_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.Verbs.t). Admitted.

#[global] Instance Verbs_into_val_typed
   :
  IntoValTypedUnderlying (v1.Verbs.t) (v1.Verbsⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Verbs.

Module APIResourceList.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance APIResourceList_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.APIResourceList.t). Admitted.

#[global] Instance APIResourceList_into_val_typed
   :
  IntoValTypedUnderlying (v1.APIResourceList.t) (v1.APIResourceListⁱᵐᵖˡ).
Proof. Admitted.

End def.
End APIResourceList.

Module RootPaths.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance RootPaths_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.RootPaths.t). Admitted.

#[global] Instance RootPaths_into_val_typed
   :
  IntoValTypedUnderlying (v1.RootPaths.t) (v1.RootPathsⁱᵐᵖˡ).
Proof. Admitted.

End def.
End RootPaths.

Module Patch.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Patch_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.Patch.t). Admitted.

#[global] Instance Patch_into_val_typed
   :
  IntoValTypedUnderlying (v1.Patch.t) (v1.Patchⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Patch.

Module LabelSelector.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance LabelSelector_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.LabelSelector.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "MatchLabels" ∷ l.[(v1.LabelSelector.t), "MatchLabels"] ↦{dq} v.(v1.LabelSelector.MatchLabels') ∗
      "MatchExpressions" ∷ l.[(v1.LabelSelector.t), "MatchExpressions"] ↦{dq} v.(v1.LabelSelector.MatchExpressions') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance LabelSelector_into_val_typed
   :
  IntoValTypedUnderlying (v1.LabelSelector.t) (v1.LabelSelectorⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance LabelSelector_access_load_MatchLabels l (v : (v1.LabelSelector.t)) dq :
  AccessStrict
    (l.[(v1.LabelSelector.t), "MatchLabels"] ↦{dq} (v.(v1.LabelSelector.MatchLabels')))
    (l.[(v1.LabelSelector.t), "MatchLabels"] ↦{dq} (v.(v1.LabelSelector.MatchLabels')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance LabelSelector_access_store_MatchLabels l (v : (v1.LabelSelector.t)) MatchLabels' :
  AccessStrict
    (l.[(v1.LabelSelector.t), "MatchLabels"] ↦ (v.(v1.LabelSelector.MatchLabels')))
    (l.[(v1.LabelSelector.t), "MatchLabels"] ↦ MatchLabels')
    (l ↦ v) (l ↦ (v <|(v1.LabelSelector.MatchLabels') := MatchLabels'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance LabelSelector_access_load_MatchExpressions l (v : (v1.LabelSelector.t)) dq :
  AccessStrict
    (l.[(v1.LabelSelector.t), "MatchExpressions"] ↦{dq} (v.(v1.LabelSelector.MatchExpressions')))
    (l.[(v1.LabelSelector.t), "MatchExpressions"] ↦{dq} (v.(v1.LabelSelector.MatchExpressions')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance LabelSelector_access_store_MatchExpressions l (v : (v1.LabelSelector.t)) MatchExpressions' :
  AccessStrict
    (l.[(v1.LabelSelector.t), "MatchExpressions"] ↦ (v.(v1.LabelSelector.MatchExpressions')))
    (l.[(v1.LabelSelector.t), "MatchExpressions"] ↦ MatchExpressions')
    (l ↦ v) (l ↦ (v <|(v1.LabelSelector.MatchExpressions') := MatchExpressions'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End LabelSelector.

Module LabelSelectorRequirement.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance LabelSelectorRequirement_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.LabelSelectorRequirement.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "Key" ∷ l.[(v1.LabelSelectorRequirement.t), "Key"] ↦{dq} v.(v1.LabelSelectorRequirement.Key') ∗
      "Operator" ∷ l.[(v1.LabelSelectorRequirement.t), "Operator"] ↦{dq} v.(v1.LabelSelectorRequirement.Operator') ∗
      "Values" ∷ l.[(v1.LabelSelectorRequirement.t), "Values"] ↦{dq} v.(v1.LabelSelectorRequirement.Values') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance LabelSelectorRequirement_into_val_typed
   :
  IntoValTypedUnderlying (v1.LabelSelectorRequirement.t) (v1.LabelSelectorRequirementⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance LabelSelectorRequirement_access_load_Key l (v : (v1.LabelSelectorRequirement.t)) dq :
  AccessStrict
    (l.[(v1.LabelSelectorRequirement.t), "Key"] ↦{dq} (v.(v1.LabelSelectorRequirement.Key')))
    (l.[(v1.LabelSelectorRequirement.t), "Key"] ↦{dq} (v.(v1.LabelSelectorRequirement.Key')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance LabelSelectorRequirement_access_store_Key l (v : (v1.LabelSelectorRequirement.t)) Key' :
  AccessStrict
    (l.[(v1.LabelSelectorRequirement.t), "Key"] ↦ (v.(v1.LabelSelectorRequirement.Key')))
    (l.[(v1.LabelSelectorRequirement.t), "Key"] ↦ Key')
    (l ↦ v) (l ↦ (v <|(v1.LabelSelectorRequirement.Key') := Key'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance LabelSelectorRequirement_access_load_Operator l (v : (v1.LabelSelectorRequirement.t)) dq :
  AccessStrict
    (l.[(v1.LabelSelectorRequirement.t), "Operator"] ↦{dq} (v.(v1.LabelSelectorRequirement.Operator')))
    (l.[(v1.LabelSelectorRequirement.t), "Operator"] ↦{dq} (v.(v1.LabelSelectorRequirement.Operator')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance LabelSelectorRequirement_access_store_Operator l (v : (v1.LabelSelectorRequirement.t)) Operator' :
  AccessStrict
    (l.[(v1.LabelSelectorRequirement.t), "Operator"] ↦ (v.(v1.LabelSelectorRequirement.Operator')))
    (l.[(v1.LabelSelectorRequirement.t), "Operator"] ↦ Operator')
    (l ↦ v) (l ↦ (v <|(v1.LabelSelectorRequirement.Operator') := Operator'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance LabelSelectorRequirement_access_load_Values l (v : (v1.LabelSelectorRequirement.t)) dq :
  AccessStrict
    (l.[(v1.LabelSelectorRequirement.t), "Values"] ↦{dq} (v.(v1.LabelSelectorRequirement.Values')))
    (l.[(v1.LabelSelectorRequirement.t), "Values"] ↦{dq} (v.(v1.LabelSelectorRequirement.Values')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance LabelSelectorRequirement_access_store_Values l (v : (v1.LabelSelectorRequirement.t)) Values' :
  AccessStrict
    (l.[(v1.LabelSelectorRequirement.t), "Values"] ↦ (v.(v1.LabelSelectorRequirement.Values')))
    (l.[(v1.LabelSelectorRequirement.t), "Values"] ↦ Values')
    (l ↦ v) (l ↦ (v <|(v1.LabelSelectorRequirement.Values') := Values'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End LabelSelectorRequirement.

Module FieldSelectorRequirement.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance FieldSelectorRequirement_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.FieldSelectorRequirement.t). Admitted.

#[global] Instance FieldSelectorRequirement_into_val_typed
   :
  IntoValTypedUnderlying (v1.FieldSelectorRequirement.t) (v1.FieldSelectorRequirementⁱᵐᵖˡ).
Proof. Admitted.

End def.
End FieldSelectorRequirement.

Module FieldSelectorOperator.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance FieldSelectorOperator_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.FieldSelectorOperator.t). Admitted.

#[global] Instance FieldSelectorOperator_into_val_typed
   :
  IntoValTypedUnderlying (v1.FieldSelectorOperator.t) (v1.FieldSelectorOperatorⁱᵐᵖˡ).
Proof. Admitted.

End def.
End FieldSelectorOperator.

Module ManagedFieldsOperationType.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance ManagedFieldsOperationType_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.ManagedFieldsOperationType.t). Admitted.

#[global] Instance ManagedFieldsOperationType_into_val_typed
   :
  IntoValTypedUnderlying (v1.ManagedFieldsOperationType.t) (v1.ManagedFieldsOperationTypeⁱᵐᵖˡ).
Proof. Admitted.

End def.
End ManagedFieldsOperationType.

Module ManagedFieldsEntry.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance ManagedFieldsEntry_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.ManagedFieldsEntry.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "Manager" ∷ l.[(v1.ManagedFieldsEntry.t), "Manager"] ↦{dq} v.(v1.ManagedFieldsEntry.Manager') ∗
      "Operation" ∷ l.[(v1.ManagedFieldsEntry.t), "Operation"] ↦{dq} v.(v1.ManagedFieldsEntry.Operation') ∗
      "APIVersion" ∷ l.[(v1.ManagedFieldsEntry.t), "APIVersion"] ↦{dq} v.(v1.ManagedFieldsEntry.APIVersion') ∗
      "Time" ∷ l.[(v1.ManagedFieldsEntry.t), "Time"] ↦{dq} v.(v1.ManagedFieldsEntry.Time') ∗
      "FieldsType" ∷ l.[(v1.ManagedFieldsEntry.t), "FieldsType"] ↦{dq} v.(v1.ManagedFieldsEntry.FieldsType') ∗
      "FieldsV1" ∷ l.[(v1.ManagedFieldsEntry.t), "FieldsV1"] ↦{dq} v.(v1.ManagedFieldsEntry.FieldsV1') ∗
      "Subresource" ∷ l.[(v1.ManagedFieldsEntry.t), "Subresource"] ↦{dq} v.(v1.ManagedFieldsEntry.Subresource') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance ManagedFieldsEntry_into_val_typed
   :
  IntoValTypedUnderlying (v1.ManagedFieldsEntry.t) (v1.ManagedFieldsEntryⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance ManagedFieldsEntry_access_load_Manager l (v : (v1.ManagedFieldsEntry.t)) dq :
  AccessStrict
    (l.[(v1.ManagedFieldsEntry.t), "Manager"] ↦{dq} (v.(v1.ManagedFieldsEntry.Manager')))
    (l.[(v1.ManagedFieldsEntry.t), "Manager"] ↦{dq} (v.(v1.ManagedFieldsEntry.Manager')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ManagedFieldsEntry_access_store_Manager l (v : (v1.ManagedFieldsEntry.t)) Manager' :
  AccessStrict
    (l.[(v1.ManagedFieldsEntry.t), "Manager"] ↦ (v.(v1.ManagedFieldsEntry.Manager')))
    (l.[(v1.ManagedFieldsEntry.t), "Manager"] ↦ Manager')
    (l ↦ v) (l ↦ (v <|(v1.ManagedFieldsEntry.Manager') := Manager'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ManagedFieldsEntry_access_load_Operation l (v : (v1.ManagedFieldsEntry.t)) dq :
  AccessStrict
    (l.[(v1.ManagedFieldsEntry.t), "Operation"] ↦{dq} (v.(v1.ManagedFieldsEntry.Operation')))
    (l.[(v1.ManagedFieldsEntry.t), "Operation"] ↦{dq} (v.(v1.ManagedFieldsEntry.Operation')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ManagedFieldsEntry_access_store_Operation l (v : (v1.ManagedFieldsEntry.t)) Operation' :
  AccessStrict
    (l.[(v1.ManagedFieldsEntry.t), "Operation"] ↦ (v.(v1.ManagedFieldsEntry.Operation')))
    (l.[(v1.ManagedFieldsEntry.t), "Operation"] ↦ Operation')
    (l ↦ v) (l ↦ (v <|(v1.ManagedFieldsEntry.Operation') := Operation'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ManagedFieldsEntry_access_load_APIVersion l (v : (v1.ManagedFieldsEntry.t)) dq :
  AccessStrict
    (l.[(v1.ManagedFieldsEntry.t), "APIVersion"] ↦{dq} (v.(v1.ManagedFieldsEntry.APIVersion')))
    (l.[(v1.ManagedFieldsEntry.t), "APIVersion"] ↦{dq} (v.(v1.ManagedFieldsEntry.APIVersion')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ManagedFieldsEntry_access_store_APIVersion l (v : (v1.ManagedFieldsEntry.t)) APIVersion' :
  AccessStrict
    (l.[(v1.ManagedFieldsEntry.t), "APIVersion"] ↦ (v.(v1.ManagedFieldsEntry.APIVersion')))
    (l.[(v1.ManagedFieldsEntry.t), "APIVersion"] ↦ APIVersion')
    (l ↦ v) (l ↦ (v <|(v1.ManagedFieldsEntry.APIVersion') := APIVersion'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ManagedFieldsEntry_access_load_Time l (v : (v1.ManagedFieldsEntry.t)) dq :
  AccessStrict
    (l.[(v1.ManagedFieldsEntry.t), "Time"] ↦{dq} (v.(v1.ManagedFieldsEntry.Time')))
    (l.[(v1.ManagedFieldsEntry.t), "Time"] ↦{dq} (v.(v1.ManagedFieldsEntry.Time')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ManagedFieldsEntry_access_store_Time l (v : (v1.ManagedFieldsEntry.t)) Time' :
  AccessStrict
    (l.[(v1.ManagedFieldsEntry.t), "Time"] ↦ (v.(v1.ManagedFieldsEntry.Time')))
    (l.[(v1.ManagedFieldsEntry.t), "Time"] ↦ Time')
    (l ↦ v) (l ↦ (v <|(v1.ManagedFieldsEntry.Time') := Time'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ManagedFieldsEntry_access_load_FieldsType l (v : (v1.ManagedFieldsEntry.t)) dq :
  AccessStrict
    (l.[(v1.ManagedFieldsEntry.t), "FieldsType"] ↦{dq} (v.(v1.ManagedFieldsEntry.FieldsType')))
    (l.[(v1.ManagedFieldsEntry.t), "FieldsType"] ↦{dq} (v.(v1.ManagedFieldsEntry.FieldsType')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ManagedFieldsEntry_access_store_FieldsType l (v : (v1.ManagedFieldsEntry.t)) FieldsType' :
  AccessStrict
    (l.[(v1.ManagedFieldsEntry.t), "FieldsType"] ↦ (v.(v1.ManagedFieldsEntry.FieldsType')))
    (l.[(v1.ManagedFieldsEntry.t), "FieldsType"] ↦ FieldsType')
    (l ↦ v) (l ↦ (v <|(v1.ManagedFieldsEntry.FieldsType') := FieldsType'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ManagedFieldsEntry_access_load_FieldsV1 l (v : (v1.ManagedFieldsEntry.t)) dq :
  AccessStrict
    (l.[(v1.ManagedFieldsEntry.t), "FieldsV1"] ↦{dq} (v.(v1.ManagedFieldsEntry.FieldsV1')))
    (l.[(v1.ManagedFieldsEntry.t), "FieldsV1"] ↦{dq} (v.(v1.ManagedFieldsEntry.FieldsV1')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ManagedFieldsEntry_access_store_FieldsV1 l (v : (v1.ManagedFieldsEntry.t)) FieldsV1' :
  AccessStrict
    (l.[(v1.ManagedFieldsEntry.t), "FieldsV1"] ↦ (v.(v1.ManagedFieldsEntry.FieldsV1')))
    (l.[(v1.ManagedFieldsEntry.t), "FieldsV1"] ↦ FieldsV1')
    (l ↦ v) (l ↦ (v <|(v1.ManagedFieldsEntry.FieldsV1') := FieldsV1'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ManagedFieldsEntry_access_load_Subresource l (v : (v1.ManagedFieldsEntry.t)) dq :
  AccessStrict
    (l.[(v1.ManagedFieldsEntry.t), "Subresource"] ↦{dq} (v.(v1.ManagedFieldsEntry.Subresource')))
    (l.[(v1.ManagedFieldsEntry.t), "Subresource"] ↦{dq} (v.(v1.ManagedFieldsEntry.Subresource')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ManagedFieldsEntry_access_store_Subresource l (v : (v1.ManagedFieldsEntry.t)) Subresource' :
  AccessStrict
    (l.[(v1.ManagedFieldsEntry.t), "Subresource"] ↦ (v.(v1.ManagedFieldsEntry.Subresource')))
    (l.[(v1.ManagedFieldsEntry.t), "Subresource"] ↦ Subresource')
    (l ↦ v) (l ↦ (v <|(v1.ManagedFieldsEntry.Subresource') := Subresource'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End ManagedFieldsEntry.

Module FieldsV1.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance FieldsV1_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.FieldsV1.t). Admitted.

#[global] Instance FieldsV1_into_val_typed
   :
  IntoValTypedUnderlying (v1.FieldsV1.t) (v1.FieldsV1ⁱᵐᵖˡ).
Proof. Admitted.

End def.
End FieldsV1.

Module Table.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Table_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.Table.t). Admitted.

#[global] Instance Table_into_val_typed
   :
  IntoValTypedUnderlying (v1.Table.t) (v1.Tableⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Table.

Module TableColumnDefinition.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance TableColumnDefinition_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.TableColumnDefinition.t). Admitted.

#[global] Instance TableColumnDefinition_into_val_typed
   :
  IntoValTypedUnderlying (v1.TableColumnDefinition.t) (v1.TableColumnDefinitionⁱᵐᵖˡ).
Proof. Admitted.

End def.
End TableColumnDefinition.

Module TableRow.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance TableRow_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.TableRow.t). Admitted.

#[global] Instance TableRow_into_val_typed
   :
  IntoValTypedUnderlying (v1.TableRow.t) (v1.TableRowⁱᵐᵖˡ).
Proof. Admitted.

End def.
End TableRow.

Module TableRowCondition.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance TableRowCondition_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.TableRowCondition.t). Admitted.

#[global] Instance TableRowCondition_into_val_typed
   :
  IntoValTypedUnderlying (v1.TableRowCondition.t) (v1.TableRowConditionⁱᵐᵖˡ).
Proof. Admitted.

End def.
End TableRowCondition.

Module RowConditionType.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance RowConditionType_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.RowConditionType.t). Admitted.

#[global] Instance RowConditionType_into_val_typed
   :
  IntoValTypedUnderlying (v1.RowConditionType.t) (v1.RowConditionTypeⁱᵐᵖˡ).
Proof. Admitted.

End def.
End RowConditionType.

Module ConditionStatus.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance ConditionStatus_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.ConditionStatus.t). Admitted.

#[global] Instance ConditionStatus_into_val_typed
   :
  IntoValTypedUnderlying (v1.ConditionStatus.t) (v1.ConditionStatusⁱᵐᵖˡ).
Proof. Admitted.

End def.
End ConditionStatus.

Module IncludeObjectPolicy.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance IncludeObjectPolicy_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.IncludeObjectPolicy.t). Admitted.

#[global] Instance IncludeObjectPolicy_into_val_typed
   :
  IntoValTypedUnderlying (v1.IncludeObjectPolicy.t) (v1.IncludeObjectPolicyⁱᵐᵖˡ).
Proof. Admitted.

End def.
End IncludeObjectPolicy.

Module TableOptions.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance TableOptions_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.TableOptions.t). Admitted.

#[global] Instance TableOptions_into_val_typed
   :
  IntoValTypedUnderlying (v1.TableOptions.t) (v1.TableOptionsⁱᵐᵖˡ).
Proof. Admitted.

End def.
End TableOptions.

Module PartialObjectMetadata.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance PartialObjectMetadata_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.PartialObjectMetadata.t). Admitted.

#[global] Instance PartialObjectMetadata_into_val_typed
   :
  IntoValTypedUnderlying (v1.PartialObjectMetadata.t) (v1.PartialObjectMetadataⁱᵐᵖˡ).
Proof. Admitted.

End def.
End PartialObjectMetadata.

Module PartialObjectMetadataList.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance PartialObjectMetadataList_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.PartialObjectMetadataList.t). Admitted.

#[global] Instance PartialObjectMetadataList_into_val_typed
   :
  IntoValTypedUnderlying (v1.PartialObjectMetadataList.t) (v1.PartialObjectMetadataListⁱᵐᵖˡ).
Proof. Admitted.

End def.
End PartialObjectMetadataList.

Module Condition.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Condition_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.Condition.t). Admitted.

#[global] Instance Condition_into_val_typed
   :
  IntoValTypedUnderlying (v1.Condition.t) (v1.Conditionⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Condition.

Module WatchEvent.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance WatchEvent_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.WatchEvent.t). Admitted.

#[global] Instance WatchEvent_into_val_typed
   :
  IntoValTypedUnderlying (v1.WatchEvent.t) (v1.WatchEventⁱᵐᵖˡ).
Proof. Admitted.

End def.
End WatchEvent.

Module InternalEvent.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : v1.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance InternalEvent_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (v1.InternalEvent.t). Admitted.

#[global] Instance InternalEvent_into_val_typed
   :
  IntoValTypedUnderlying (v1.InternalEvent.t) (v1.InternalEventⁱᵐᵖˡ).
Proof. Admitted.

End def.
End InternalEvent.

End v1.
