(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.golang.theory.
Require Export New.code.net.url.

Set Default Proof Using "Type".

Module url.
Module encoding.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : url.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance encoding_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (url.encoding.t). Admitted.

#[global] Instance encoding_into_val_typed
   :
  IntoValTypedUnderlying (url.encoding.t) (url.encodingⁱᵐᵖˡ).
Proof. Admitted.

End def.
End encoding.

Module Error.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : url.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Error_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (url.Error.t). Admitted.

#[global] Instance Error_into_val_typed
   :
  IntoValTypedUnderlying (url.Error.t) (url.Errorⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Error.

Module EscapeError.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : url.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance EscapeError_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (url.EscapeError.t). Admitted.

#[global] Instance EscapeError_into_val_typed
   :
  IntoValTypedUnderlying (url.EscapeError.t) (url.EscapeErrorⁱᵐᵖˡ).
Proof. Admitted.

End def.
End EscapeError.

Module InvalidHostError.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : url.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance InvalidHostError_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (url.InvalidHostError.t). Admitted.

#[global] Instance InvalidHostError_into_val_typed
   :
  IntoValTypedUnderlying (url.InvalidHostError.t) (url.InvalidHostErrorⁱᵐᵖˡ).
Proof. Admitted.

End def.
End InvalidHostError.

Module URL.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : url.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance URL_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (url.URL.t). Admitted.

#[global] Instance URL_into_val_typed
   :
  IntoValTypedUnderlying (url.URL.t) (url.URLⁱᵐᵖˡ).
Proof. Admitted.

End def.
End URL.

Module Userinfo.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : url.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Userinfo_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (url.Userinfo.t). Admitted.

#[global] Instance Userinfo_into_val_typed
   :
  IntoValTypedUnderlying (url.Userinfo.t) (url.Userinfoⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Userinfo.

End url.
