(* autogenerated from k8s.io/kubernetes/pkg/api/legacyscheme *)

From New.golang Require Import defn.
Definition legacyscheme : go_string := "k8s.io/kubernetes/pkg/api/legacyscheme".

Module legacyscheme.

Section code.
Context `{ffi_syntax}.


Definition Scheme : go_string := "k8s.io/kubernetes/pkg/api/legacyscheme.Scheme"%go.

Axiom Scheme'init : val.

Definition Codecs : go_string := "k8s.io/kubernetes/pkg/api/legacyscheme.Codecs"%go.

Axiom Codecs'init : val.

Definition ParameterCodec : go_string := "k8s.io/kubernetes/pkg/api/legacyscheme.ParameterCodec"%go.

Axiom ParameterCodec'init : val.

Definition vars' : list (go_string * go_type) := [].

Definition functions' : list (go_string * val) := [].

Definition msets' : list (go_string * (list (go_string * val))) := [].

#[global] Instance info' : PkgInfo legacyscheme.legacyscheme :=
  {|
    pkg_vars := vars';
    pkg_functions := functions';
    pkg_msets := msets';
    pkg_imported_pkgs := [];
  |}.

Axiom _'init : val.

Definition initialize' : val :=
  λ: <>,
    package.init #legacyscheme.legacyscheme (λ: <>,
      exception_do (do:  (package.alloc legacyscheme.legacyscheme #());;;
      do:  (Scheme'init #());;;
      do:  (Codecs'init #());;;
      do:  (ParameterCodec'init #()))
      ).

End code.
End legacyscheme.
