(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.golang.theory.

Require Export New.code.k8s_io.client_go.gentype.

Set Default Proof Using "Type".

Module gentype.

(* type gentype.FakeClient *)
Module FakeClient.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End FakeClient.

Global Instance bounded_size_FakeClient : BoundedTypeSize gentype.FakeClient.
Admitted.

Global Instance into_val_FakeClient `{ffi_syntax} : IntoVal FakeClient.t.
Admitted.

Global Instance into_val_typed_FakeClient `{ffi_syntax} : IntoValTyped FakeClient.t gentype.FakeClient.
Admitted.

(* type gentype.FakeClientWithList *)
Module FakeClientWithList.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End FakeClientWithList.

Global Instance bounded_size_FakeClientWithList : BoundedTypeSize gentype.FakeClientWithList.
Admitted.

Global Instance into_val_FakeClientWithList `{ffi_syntax} : IntoVal FakeClientWithList.t.
Admitted.

Global Instance into_val_typed_FakeClientWithList `{ffi_syntax} : IntoValTyped FakeClientWithList.t gentype.FakeClientWithList.
Admitted.

(* type gentype.FakeClientWithApply *)
Module FakeClientWithApply.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End FakeClientWithApply.

Global Instance bounded_size_FakeClientWithApply : BoundedTypeSize gentype.FakeClientWithApply.
Admitted.

Global Instance into_val_FakeClientWithApply `{ffi_syntax} : IntoVal FakeClientWithApply.t.
Admitted.

Global Instance into_val_typed_FakeClientWithApply `{ffi_syntax} : IntoValTyped FakeClientWithApply.t gentype.FakeClientWithApply.
Admitted.

(* type gentype.FakeClientWithListAndApply *)
Module FakeClientWithListAndApply.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End FakeClientWithListAndApply.

Global Instance bounded_size_FakeClientWithListAndApply : BoundedTypeSize gentype.FakeClientWithListAndApply.
Admitted.

Global Instance into_val_FakeClientWithListAndApply `{ffi_syntax} : IntoVal FakeClientWithListAndApply.t.
Admitted.

Global Instance into_val_typed_FakeClientWithListAndApply `{ffi_syntax} : IntoValTyped FakeClientWithListAndApply.t gentype.FakeClientWithListAndApply.
Admitted.

(* type gentype.alsoFakeLister *)
Module alsoFakeLister.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End alsoFakeLister.

Global Instance bounded_size_alsoFakeLister : BoundedTypeSize gentype.alsoFakeLister.
Admitted.

Global Instance into_val_alsoFakeLister `{ffi_syntax} : IntoVal alsoFakeLister.t.
Admitted.

Global Instance into_val_typed_alsoFakeLister `{ffi_syntax} : IntoValTyped alsoFakeLister.t gentype.alsoFakeLister.
Admitted.

(* type gentype.alsoFakeApplier *)
Module alsoFakeApplier.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End alsoFakeApplier.

Global Instance bounded_size_alsoFakeApplier : BoundedTypeSize gentype.alsoFakeApplier.
Admitted.

Global Instance into_val_alsoFakeApplier `{ffi_syntax} : IntoVal alsoFakeApplier.t.
Admitted.

Global Instance into_val_typed_alsoFakeApplier `{ffi_syntax} : IntoValTyped alsoFakeApplier.t gentype.alsoFakeApplier.
Admitted.

(* type gentype.objectWithMeta *)
Module objectWithMeta.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End objectWithMeta.

Global Instance bounded_size_objectWithMeta : BoundedTypeSize gentype.objectWithMeta.
Admitted.

Global Instance into_val_objectWithMeta `{ffi_syntax} : IntoVal objectWithMeta.t.
Admitted.

Global Instance into_val_typed_objectWithMeta `{ffi_syntax} : IntoValTyped objectWithMeta.t gentype.objectWithMeta.
Admitted.

(* type gentype.namedObject *)
Module namedObject.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End namedObject.

Global Instance bounded_size_namedObject : BoundedTypeSize gentype.namedObject.
Admitted.

Global Instance into_val_namedObject `{ffi_syntax} : IntoVal namedObject.t.
Admitted.

Global Instance into_val_typed_namedObject `{ffi_syntax} : IntoValTyped namedObject.t gentype.namedObject.
Admitted.

(* type gentype.Client *)
Module Client.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End Client.

Global Instance bounded_size_Client : BoundedTypeSize gentype.Client.
Admitted.

Global Instance into_val_Client `{ffi_syntax} : IntoVal Client.t.
Admitted.

Global Instance into_val_typed_Client `{ffi_syntax} : IntoValTyped Client.t gentype.Client.
Admitted.

(* type gentype.ClientWithList *)
Module ClientWithList.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End ClientWithList.

Global Instance bounded_size_ClientWithList : BoundedTypeSize gentype.ClientWithList.
Admitted.

Global Instance into_val_ClientWithList `{ffi_syntax} : IntoVal ClientWithList.t.
Admitted.

Global Instance into_val_typed_ClientWithList `{ffi_syntax} : IntoValTyped ClientWithList.t gentype.ClientWithList.
Admitted.

(* type gentype.ClientWithApply *)
Module ClientWithApply.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End ClientWithApply.

Global Instance bounded_size_ClientWithApply : BoundedTypeSize gentype.ClientWithApply.
Admitted.

Global Instance into_val_ClientWithApply `{ffi_syntax} : IntoVal ClientWithApply.t.
Admitted.

Global Instance into_val_typed_ClientWithApply `{ffi_syntax} : IntoValTyped ClientWithApply.t gentype.ClientWithApply.
Admitted.

(* type gentype.ClientWithListAndApply *)
Module ClientWithListAndApply.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End ClientWithListAndApply.

Global Instance bounded_size_ClientWithListAndApply : BoundedTypeSize gentype.ClientWithListAndApply.
Admitted.

Global Instance into_val_ClientWithListAndApply `{ffi_syntax} : IntoVal ClientWithListAndApply.t.
Admitted.

Global Instance into_val_typed_ClientWithListAndApply `{ffi_syntax} : IntoValTyped ClientWithListAndApply.t gentype.ClientWithListAndApply.
Admitted.

(* type gentype.alsoLister *)
Module alsoLister.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End alsoLister.

Global Instance bounded_size_alsoLister : BoundedTypeSize gentype.alsoLister.
Admitted.

Global Instance into_val_alsoLister `{ffi_syntax} : IntoVal alsoLister.t.
Admitted.

Global Instance into_val_typed_alsoLister `{ffi_syntax} : IntoValTyped alsoLister.t gentype.alsoLister.
Admitted.

(* type gentype.alsoApplier *)
Module alsoApplier.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End alsoApplier.

Global Instance bounded_size_alsoApplier : BoundedTypeSize gentype.alsoApplier.
Admitted.

Global Instance into_val_alsoApplier `{ffi_syntax} : IntoVal alsoApplier.t.
Admitted.

Global Instance into_val_typed_alsoApplier `{ffi_syntax} : IntoValTyped alsoApplier.t gentype.alsoApplier.
Admitted.

(* type gentype.Option *)
Module Option.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End Option.

Global Instance bounded_size_Option : BoundedTypeSize gentype.Option.
Admitted.

Global Instance into_val_Option `{ffi_syntax} : IntoVal Option.t.
Admitted.

Global Instance into_val_typed_Option `{ffi_syntax} : IntoValTyped Option.t gentype.Option.
Admitted.

Section names.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context `{!globalsGS Σ}.
Context {go_ctx : GoContext}.
#[local] Transparent is_pkg_defined is_pkg_defined_pure.

Global Instance is_pkg_defined_pure_gentype : IsPkgDefinedPure gentype :=
  {|
    is_pkg_defined_pure_def go_ctx :=
      is_pkg_defined_pure_single gentype;
  |}.

#[local] Transparent is_pkg_defined_single is_pkg_defined_pure_single.
Global Program Instance is_pkg_defined_gentype : IsPkgDefined gentype :=
  {|
    is_pkg_defined_def go_ctx :=
      (is_pkg_defined_single gentype)%I
  |}.
Final Obligation. iIntros. iFrame "#%". Qed.
#[local] Opaque is_pkg_defined_single is_pkg_defined_pure_single.

End names.
End gentype.
