(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.golang.theory.

Require Export New.code.k8s_io.client_go.kubernetes.

Set Default Proof Using "Type".

Module kubernetes.

(* type kubernetes.Interface *)
Module Interface.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End Interface.

Global Instance bounded_size_Interface : BoundedTypeSize kubernetes.Interface.
Admitted.

Global Instance into_val_Interface `{ffi_syntax} : IntoVal Interface.t.
Admitted.

Global Instance into_val_typed_Interface `{ffi_syntax} : IntoValTyped Interface.t kubernetes.Interface.
Admitted.

(* type kubernetes.Clientset *)
Module Clientset.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End Clientset.

Global Instance bounded_size_Clientset : BoundedTypeSize kubernetes.Clientset.
Admitted.

Global Instance into_val_Clientset `{ffi_syntax} : IntoVal Clientset.t.
Admitted.

Global Instance into_val_typed_Clientset `{ffi_syntax} : IntoValTyped Clientset.t kubernetes.Clientset.
Admitted.

Section names.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context `{!globalsGS Σ}.
Context {go_ctx : GoContext}.
#[local] Transparent is_pkg_defined is_pkg_defined_pure.

Global Instance is_pkg_defined_pure_kubernetes : IsPkgDefinedPure kubernetes :=
  {|
    is_pkg_defined_pure_def go_ctx :=
      is_pkg_defined_pure_single kubernetes;
  |}.

#[local] Transparent is_pkg_defined_single is_pkg_defined_pure_single.
Global Program Instance is_pkg_defined_kubernetes : IsPkgDefined kubernetes :=
  {|
    is_pkg_defined_def go_ctx :=
      (is_pkg_defined_single kubernetes)%I
  |}.
Final Obligation. iIntros. iFrame "#%". Qed.
#[local] Opaque is_pkg_defined_single is_pkg_defined_pure_single.

End names.
End kubernetes.
