(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.golang.theory.
Require Export New.code.k8s_io.kubernetes.pkg.apis.apps.validation.

Set Default Proof Using "Type".

Module validation.
Module StatefulSetValidationOptions.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Local Set Default Proof Using "All".

#[global] Instance StatefulSetValidationOptions_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (validation.StatefulSetValidationOptions.t). Admitted.

#[global] Instance StatefulSetValidationOptions_into_val_typed
   :
  IntoValTypedUnderlying (validation.StatefulSetValidationOptions.t) (validation.StatefulSetValidationOptionsⁱᵐᵖˡ).
Proof. Admitted.

End def.
End StatefulSetValidationOptions.

End validation.
