translate = [
    "TypeMeta",
    "ObjectMeta",
    "OwnerReference",
    "ManagedFieldsEntry",
    "Time",
    "LabelSelector",
    "LabelSelectorRequirement",
    "LabelSelectorOperator",
    "Object",
    "ObjectMeta.GetNamespace",
    "ObjectMeta.SetNamespace",
    "ObjectMeta.GetName",
    "ObjectMeta.SetName",
    "ObjectMeta.GetGenerateName",
    "ObjectMeta.SetGenerateName",
    "ObjectMeta.GetUID",
    "ObjectMeta.SetUID",
    "ObjectMeta.GetResourceVersion",
    "ObjectMeta.SetResourceVersion",
    "ObjectMeta.GetGeneration",
    "ObjectMeta.SetGeneration",
    "ObjectMeta.GetSelfLink",
    "ObjectMeta.SetSelfLink",
    "ObjectMeta.GetCreationTimestamp",
    "ObjectMeta.SetCreationTimestamp",
    "ObjectMeta.GetDeletionTimestamp",
    "ObjectMeta.SetDeletionTimestamp",
    "ObjectMeta.GetDeletionGracePeriodSeconds",
    "ObjectMeta.SetDeletionGracePeriodSeconds",
    "ObjectMeta.GetLabels",
    "ObjectMeta.SetLabels",
    "ObjectMeta.GetAnnotations",
    "ObjectMeta.SetAnnotations",
    "ObjectMeta.GetFinalizers",
    "ObjectMeta.SetFinalizers",
    "ObjectMeta.GetOwnerReferences",
    "ObjectMeta.SetOwnerReferences",
    "ObjectMeta.GetManagedFields",
    "ObjectMeta.SetManagedFields",
    "NewControllerRef",
    "NamespaceDefault",
    "NamespaceAll",
    "NamespaceNone",
    "NamespaceSystem",
    "NamespacePublic",
    "DeleteOptions",
    "Preconditions",
    "DeletionPropagation",
]

imports = [
    "time",
    "k8s.io/apimachinery/pkg/types",
    "k8s.io/apimachinery/pkg/runtime/schema",
    "k8s.io/utils/ptr",
]
