translate = [
    "TypeMeta",
    "ObjectMeta",
    "OwnerReference",
    "ManagedFieldsEntry",
    "Time",
    "LabelSelector",
    "LabelSelectorRequirement",
    "LabelSelectorOperator",
]

imports = [
    "time",
    "k8s.io/apimachinery/pkg/types",
]
