(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.golang.theory.

Require Export New.code.k8s_io.apiserver.pkg.registry.rest.

Set Default Proof Using "Type".

Module rest.

(* type rest.RESTCreateStrategy *)
Module RESTCreateStrategy.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End RESTCreateStrategy.

Global Instance bounded_size_RESTCreateStrategy : BoundedTypeSize rest.RESTCreateStrategy.
Admitted.

Global Instance into_val_RESTCreateStrategy `{ffi_syntax} : IntoVal RESTCreateStrategy.t.
Admitted.

Global Instance into_val_typed_RESTCreateStrategy `{ffi_syntax} : IntoValTyped RESTCreateStrategy.t rest.RESTCreateStrategy.
Admitted.

(* type rest.NamespaceScopedStrategy *)
Module NamespaceScopedStrategy.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End NamespaceScopedStrategy.

Global Instance bounded_size_NamespaceScopedStrategy : BoundedTypeSize rest.NamespaceScopedStrategy.
Admitted.

Global Instance into_val_NamespaceScopedStrategy `{ffi_syntax} : IntoVal NamespaceScopedStrategy.t.
Admitted.

Global Instance into_val_typed_NamespaceScopedStrategy `{ffi_syntax} : IntoValTyped NamespaceScopedStrategy.t rest.NamespaceScopedStrategy.
Admitted.

(* type rest.RESTCreateUpdateStrategy *)
Module RESTCreateUpdateStrategy.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End RESTCreateUpdateStrategy.

Global Instance bounded_size_RESTCreateUpdateStrategy : BoundedTypeSize rest.RESTCreateUpdateStrategy.
Admitted.

Global Instance into_val_RESTCreateUpdateStrategy `{ffi_syntax} : IntoVal RESTCreateUpdateStrategy.t.
Admitted.

Global Instance into_val_typed_RESTCreateUpdateStrategy `{ffi_syntax} : IntoValTyped RESTCreateUpdateStrategy.t rest.RESTCreateUpdateStrategy.
Admitted.

(* type rest.RESTDeleteStrategy *)
Module RESTDeleteStrategy.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End RESTDeleteStrategy.

Global Instance bounded_size_RESTDeleteStrategy : BoundedTypeSize rest.RESTDeleteStrategy.
Admitted.

Global Instance into_val_RESTDeleteStrategy `{ffi_syntax} : IntoVal RESTDeleteStrategy.t.
Admitted.

Global Instance into_val_typed_RESTDeleteStrategy `{ffi_syntax} : IntoValTyped RESTDeleteStrategy.t rest.RESTDeleteStrategy.
Admitted.

(* type rest.GarbageCollectionPolicy *)
Module GarbageCollectionPolicy.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End GarbageCollectionPolicy.

Global Instance bounded_size_GarbageCollectionPolicy : BoundedTypeSize rest.GarbageCollectionPolicy.
Admitted.

Global Instance into_val_GarbageCollectionPolicy `{ffi_syntax} : IntoVal GarbageCollectionPolicy.t.
Admitted.

Global Instance into_val_typed_GarbageCollectionPolicy `{ffi_syntax} : IntoValTyped GarbageCollectionPolicy.t rest.GarbageCollectionPolicy.
Admitted.

(* type rest.GarbageCollectionDeleteStrategy *)
Module GarbageCollectionDeleteStrategy.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End GarbageCollectionDeleteStrategy.

Global Instance bounded_size_GarbageCollectionDeleteStrategy : BoundedTypeSize rest.GarbageCollectionDeleteStrategy.
Admitted.

Global Instance into_val_GarbageCollectionDeleteStrategy `{ffi_syntax} : IntoVal GarbageCollectionDeleteStrategy.t.
Admitted.

Global Instance into_val_typed_GarbageCollectionDeleteStrategy `{ffi_syntax} : IntoValTyped GarbageCollectionDeleteStrategy.t rest.GarbageCollectionDeleteStrategy.
Admitted.

(* type rest.RESTGracefulDeleteStrategy *)
Module RESTGracefulDeleteStrategy.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End RESTGracefulDeleteStrategy.

Global Instance bounded_size_RESTGracefulDeleteStrategy : BoundedTypeSize rest.RESTGracefulDeleteStrategy.
Admitted.

Global Instance into_val_RESTGracefulDeleteStrategy `{ffi_syntax} : IntoVal RESTGracefulDeleteStrategy.t.
Admitted.

Global Instance into_val_typed_RESTGracefulDeleteStrategy `{ffi_syntax} : IntoValTyped RESTGracefulDeleteStrategy.t rest.RESTGracefulDeleteStrategy.
Admitted.

(* type rest.Storage *)
Module Storage.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End Storage.

Global Instance bounded_size_Storage : BoundedTypeSize rest.Storage.
Admitted.

Global Instance into_val_Storage `{ffi_syntax} : IntoVal Storage.t.
Admitted.

Global Instance into_val_typed_Storage `{ffi_syntax} : IntoValTyped Storage.t rest.Storage.
Admitted.

(* type rest.StorageWithReadiness *)
Module StorageWithReadiness.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End StorageWithReadiness.

Global Instance bounded_size_StorageWithReadiness : BoundedTypeSize rest.StorageWithReadiness.
Admitted.

Global Instance into_val_StorageWithReadiness `{ffi_syntax} : IntoVal StorageWithReadiness.t.
Admitted.

Global Instance into_val_typed_StorageWithReadiness `{ffi_syntax} : IntoValTyped StorageWithReadiness.t rest.StorageWithReadiness.
Admitted.

(* type rest.Scoper *)
Module Scoper.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End Scoper.

Global Instance bounded_size_Scoper : BoundedTypeSize rest.Scoper.
Admitted.

Global Instance into_val_Scoper `{ffi_syntax} : IntoVal Scoper.t.
Admitted.

Global Instance into_val_typed_Scoper `{ffi_syntax} : IntoValTyped Scoper.t rest.Scoper.
Admitted.

(* type rest.KindProvider *)
Module KindProvider.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End KindProvider.

Global Instance bounded_size_KindProvider : BoundedTypeSize rest.KindProvider.
Admitted.

Global Instance into_val_KindProvider `{ffi_syntax} : IntoVal KindProvider.t.
Admitted.

Global Instance into_val_typed_KindProvider `{ffi_syntax} : IntoValTyped KindProvider.t rest.KindProvider.
Admitted.

(* type rest.ShortNamesProvider *)
Module ShortNamesProvider.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End ShortNamesProvider.

Global Instance bounded_size_ShortNamesProvider : BoundedTypeSize rest.ShortNamesProvider.
Admitted.

Global Instance into_val_ShortNamesProvider `{ffi_syntax} : IntoVal ShortNamesProvider.t.
Admitted.

Global Instance into_val_typed_ShortNamesProvider `{ffi_syntax} : IntoValTyped ShortNamesProvider.t rest.ShortNamesProvider.
Admitted.

(* type rest.CategoriesProvider *)
Module CategoriesProvider.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End CategoriesProvider.

Global Instance bounded_size_CategoriesProvider : BoundedTypeSize rest.CategoriesProvider.
Admitted.

Global Instance into_val_CategoriesProvider `{ffi_syntax} : IntoVal CategoriesProvider.t.
Admitted.

Global Instance into_val_typed_CategoriesProvider `{ffi_syntax} : IntoValTyped CategoriesProvider.t rest.CategoriesProvider.
Admitted.

(* type rest.SingularNameProvider *)
Module SingularNameProvider.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End SingularNameProvider.

Global Instance bounded_size_SingularNameProvider : BoundedTypeSize rest.SingularNameProvider.
Admitted.

Global Instance into_val_SingularNameProvider `{ffi_syntax} : IntoVal SingularNameProvider.t.
Admitted.

Global Instance into_val_typed_SingularNameProvider `{ffi_syntax} : IntoValTyped SingularNameProvider.t rest.SingularNameProvider.
Admitted.

(* type rest.GroupVersionKindProvider *)
Module GroupVersionKindProvider.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End GroupVersionKindProvider.

Global Instance bounded_size_GroupVersionKindProvider : BoundedTypeSize rest.GroupVersionKindProvider.
Admitted.

Global Instance into_val_GroupVersionKindProvider `{ffi_syntax} : IntoVal GroupVersionKindProvider.t.
Admitted.

Global Instance into_val_typed_GroupVersionKindProvider `{ffi_syntax} : IntoValTyped GroupVersionKindProvider.t rest.GroupVersionKindProvider.
Admitted.

(* type rest.GroupVersionAcceptor *)
Module GroupVersionAcceptor.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End GroupVersionAcceptor.

Global Instance bounded_size_GroupVersionAcceptor : BoundedTypeSize rest.GroupVersionAcceptor.
Admitted.

Global Instance into_val_GroupVersionAcceptor `{ffi_syntax} : IntoVal GroupVersionAcceptor.t.
Admitted.

Global Instance into_val_typed_GroupVersionAcceptor `{ffi_syntax} : IntoValTyped GroupVersionAcceptor.t rest.GroupVersionAcceptor.
Admitted.

(* type rest.Lister *)
Module Lister.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End Lister.

Global Instance bounded_size_Lister : BoundedTypeSize rest.Lister.
Admitted.

Global Instance into_val_Lister `{ffi_syntax} : IntoVal Lister.t.
Admitted.

Global Instance into_val_typed_Lister `{ffi_syntax} : IntoValTyped Lister.t rest.Lister.
Admitted.

(* type rest.Getter *)
Module Getter.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End Getter.

Global Instance bounded_size_Getter : BoundedTypeSize rest.Getter.
Admitted.

Global Instance into_val_Getter `{ffi_syntax} : IntoVal Getter.t.
Admitted.

Global Instance into_val_typed_Getter `{ffi_syntax} : IntoValTyped Getter.t rest.Getter.
Admitted.

(* type rest.GetterWithOptions *)
Module GetterWithOptions.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End GetterWithOptions.

Global Instance bounded_size_GetterWithOptions : BoundedTypeSize rest.GetterWithOptions.
Admitted.

Global Instance into_val_GetterWithOptions `{ffi_syntax} : IntoVal GetterWithOptions.t.
Admitted.

Global Instance into_val_typed_GetterWithOptions `{ffi_syntax} : IntoValTyped GetterWithOptions.t rest.GetterWithOptions.
Admitted.

(* type rest.TableConvertor *)
Module TableConvertor.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End TableConvertor.

Global Instance bounded_size_TableConvertor : BoundedTypeSize rest.TableConvertor.
Admitted.

Global Instance into_val_TableConvertor `{ffi_syntax} : IntoVal TableConvertor.t.
Admitted.

Global Instance into_val_typed_TableConvertor `{ffi_syntax} : IntoValTyped TableConvertor.t rest.TableConvertor.
Admitted.

(* type rest.GracefulDeleter *)
Module GracefulDeleter.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End GracefulDeleter.

Global Instance bounded_size_GracefulDeleter : BoundedTypeSize rest.GracefulDeleter.
Admitted.

Global Instance into_val_GracefulDeleter `{ffi_syntax} : IntoVal GracefulDeleter.t.
Admitted.

Global Instance into_val_typed_GracefulDeleter `{ffi_syntax} : IntoValTyped GracefulDeleter.t rest.GracefulDeleter.
Admitted.

(* type rest.MayReturnFullObjectDeleter *)
Module MayReturnFullObjectDeleter.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End MayReturnFullObjectDeleter.

Global Instance bounded_size_MayReturnFullObjectDeleter : BoundedTypeSize rest.MayReturnFullObjectDeleter.
Admitted.

Global Instance into_val_MayReturnFullObjectDeleter `{ffi_syntax} : IntoVal MayReturnFullObjectDeleter.t.
Admitted.

Global Instance into_val_typed_MayReturnFullObjectDeleter `{ffi_syntax} : IntoValTyped MayReturnFullObjectDeleter.t rest.MayReturnFullObjectDeleter.
Admitted.

(* type rest.CollectionDeleter *)
Module CollectionDeleter.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End CollectionDeleter.

Global Instance bounded_size_CollectionDeleter : BoundedTypeSize rest.CollectionDeleter.
Admitted.

Global Instance into_val_CollectionDeleter `{ffi_syntax} : IntoVal CollectionDeleter.t.
Admitted.

Global Instance into_val_typed_CollectionDeleter `{ffi_syntax} : IntoValTyped CollectionDeleter.t rest.CollectionDeleter.
Admitted.

(* type rest.Creater *)
Module Creater.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End Creater.

Global Instance bounded_size_Creater : BoundedTypeSize rest.Creater.
Admitted.

Global Instance into_val_Creater `{ffi_syntax} : IntoVal Creater.t.
Admitted.

Global Instance into_val_typed_Creater `{ffi_syntax} : IntoValTyped Creater.t rest.Creater.
Admitted.

(* type rest.NamedCreater *)
Module NamedCreater.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End NamedCreater.

Global Instance bounded_size_NamedCreater : BoundedTypeSize rest.NamedCreater.
Admitted.

Global Instance into_val_NamedCreater `{ffi_syntax} : IntoVal NamedCreater.t.
Admitted.

Global Instance into_val_typed_NamedCreater `{ffi_syntax} : IntoValTyped NamedCreater.t rest.NamedCreater.
Admitted.

(* type rest.SubresourceObjectMetaPreserver *)
Module SubresourceObjectMetaPreserver.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End SubresourceObjectMetaPreserver.

Global Instance bounded_size_SubresourceObjectMetaPreserver : BoundedTypeSize rest.SubresourceObjectMetaPreserver.
Admitted.

Global Instance into_val_SubresourceObjectMetaPreserver `{ffi_syntax} : IntoVal SubresourceObjectMetaPreserver.t.
Admitted.

Global Instance into_val_typed_SubresourceObjectMetaPreserver `{ffi_syntax} : IntoValTyped SubresourceObjectMetaPreserver.t rest.SubresourceObjectMetaPreserver.
Admitted.

(* type rest.UpdatedObjectInfo *)
Module UpdatedObjectInfo.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End UpdatedObjectInfo.

Global Instance bounded_size_UpdatedObjectInfo : BoundedTypeSize rest.UpdatedObjectInfo.
Admitted.

Global Instance into_val_UpdatedObjectInfo `{ffi_syntax} : IntoVal UpdatedObjectInfo.t.
Admitted.

Global Instance into_val_typed_UpdatedObjectInfo `{ffi_syntax} : IntoValTyped UpdatedObjectInfo.t rest.UpdatedObjectInfo.
Admitted.

(* type rest.ValidateObjectFunc *)
Module ValidateObjectFunc.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End ValidateObjectFunc.

Global Instance bounded_size_ValidateObjectFunc : BoundedTypeSize rest.ValidateObjectFunc.
Admitted.

Global Instance into_val_ValidateObjectFunc `{ffi_syntax} : IntoVal ValidateObjectFunc.t.
Admitted.

Global Instance into_val_typed_ValidateObjectFunc `{ffi_syntax} : IntoValTyped ValidateObjectFunc.t rest.ValidateObjectFunc.
Admitted.

(* type rest.ValidateObjectUpdateFunc *)
Module ValidateObjectUpdateFunc.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End ValidateObjectUpdateFunc.

Global Instance bounded_size_ValidateObjectUpdateFunc : BoundedTypeSize rest.ValidateObjectUpdateFunc.
Admitted.

Global Instance into_val_ValidateObjectUpdateFunc `{ffi_syntax} : IntoVal ValidateObjectUpdateFunc.t.
Admitted.

Global Instance into_val_typed_ValidateObjectUpdateFunc `{ffi_syntax} : IntoValTyped ValidateObjectUpdateFunc.t rest.ValidateObjectUpdateFunc.
Admitted.

(* type rest.Updater *)
Module Updater.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End Updater.

Global Instance bounded_size_Updater : BoundedTypeSize rest.Updater.
Admitted.

Global Instance into_val_Updater `{ffi_syntax} : IntoVal Updater.t.
Admitted.

Global Instance into_val_typed_Updater `{ffi_syntax} : IntoValTyped Updater.t rest.Updater.
Admitted.

(* type rest.CreaterUpdater *)
Module CreaterUpdater.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End CreaterUpdater.

Global Instance bounded_size_CreaterUpdater : BoundedTypeSize rest.CreaterUpdater.
Admitted.

Global Instance into_val_CreaterUpdater `{ffi_syntax} : IntoVal CreaterUpdater.t.
Admitted.

Global Instance into_val_typed_CreaterUpdater `{ffi_syntax} : IntoValTyped CreaterUpdater.t rest.CreaterUpdater.
Admitted.

(* type rest.Patcher *)
Module Patcher.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End Patcher.

Global Instance bounded_size_Patcher : BoundedTypeSize rest.Patcher.
Admitted.

Global Instance into_val_Patcher `{ffi_syntax} : IntoVal Patcher.t.
Admitted.

Global Instance into_val_typed_Patcher `{ffi_syntax} : IntoValTyped Patcher.t rest.Patcher.
Admitted.

(* type rest.Watcher *)
Module Watcher.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End Watcher.

Global Instance bounded_size_Watcher : BoundedTypeSize rest.Watcher.
Admitted.

Global Instance into_val_Watcher `{ffi_syntax} : IntoVal Watcher.t.
Admitted.

Global Instance into_val_typed_Watcher `{ffi_syntax} : IntoValTyped Watcher.t rest.Watcher.
Admitted.

(* type rest.StandardStorage *)
Module StandardStorage.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End StandardStorage.

Global Instance bounded_size_StandardStorage : BoundedTypeSize rest.StandardStorage.
Admitted.

Global Instance into_val_StandardStorage `{ffi_syntax} : IntoVal StandardStorage.t.
Admitted.

Global Instance into_val_typed_StandardStorage `{ffi_syntax} : IntoValTyped StandardStorage.t rest.StandardStorage.
Admitted.

(* type rest.Redirector *)
Module Redirector.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End Redirector.

Global Instance bounded_size_Redirector : BoundedTypeSize rest.Redirector.
Admitted.

Global Instance into_val_Redirector `{ffi_syntax} : IntoVal Redirector.t.
Admitted.

Global Instance into_val_typed_Redirector `{ffi_syntax} : IntoValTyped Redirector.t rest.Redirector.
Admitted.

(* type rest.Responder *)
Module Responder.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End Responder.

Global Instance bounded_size_Responder : BoundedTypeSize rest.Responder.
Admitted.

Global Instance into_val_Responder `{ffi_syntax} : IntoVal Responder.t.
Admitted.

Global Instance into_val_typed_Responder `{ffi_syntax} : IntoValTyped Responder.t rest.Responder.
Admitted.

(* type rest.Connecter *)
Module Connecter.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End Connecter.

Global Instance bounded_size_Connecter : BoundedTypeSize rest.Connecter.
Admitted.

Global Instance into_val_Connecter `{ffi_syntax} : IntoVal Connecter.t.
Admitted.

Global Instance into_val_typed_Connecter `{ffi_syntax} : IntoValTyped Connecter.t rest.Connecter.
Admitted.

(* type rest.ResourceStreamer *)
Module ResourceStreamer.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End ResourceStreamer.

Global Instance bounded_size_ResourceStreamer : BoundedTypeSize rest.ResourceStreamer.
Admitted.

Global Instance into_val_ResourceStreamer `{ffi_syntax} : IntoVal ResourceStreamer.t.
Admitted.

Global Instance into_val_typed_ResourceStreamer `{ffi_syntax} : IntoValTyped ResourceStreamer.t rest.ResourceStreamer.
Admitted.

(* type rest.StorageMetadata *)
Module StorageMetadata.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End StorageMetadata.

Global Instance bounded_size_StorageMetadata : BoundedTypeSize rest.StorageMetadata.
Admitted.

Global Instance into_val_StorageMetadata `{ffi_syntax} : IntoVal StorageMetadata.t.
Admitted.

Global Instance into_val_typed_StorageMetadata `{ffi_syntax} : IntoValTyped StorageMetadata.t rest.StorageMetadata.
Admitted.

(* type rest.StorageVersionProvider *)
Module StorageVersionProvider.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End StorageVersionProvider.

Global Instance bounded_size_StorageVersionProvider : BoundedTypeSize rest.StorageVersionProvider.
Admitted.

Global Instance into_val_StorageVersionProvider `{ffi_syntax} : IntoVal StorageVersionProvider.t.
Admitted.

Global Instance into_val_typed_StorageVersionProvider `{ffi_syntax} : IntoValTyped StorageVersionProvider.t rest.StorageVersionProvider.
Admitted.

(* type rest.ResetFieldsStrategy *)
Module ResetFieldsStrategy.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End ResetFieldsStrategy.

Global Instance bounded_size_ResetFieldsStrategy : BoundedTypeSize rest.ResetFieldsStrategy.
Admitted.

Global Instance into_val_ResetFieldsStrategy `{ffi_syntax} : IntoVal ResetFieldsStrategy.t.
Admitted.

Global Instance into_val_typed_ResetFieldsStrategy `{ffi_syntax} : IntoValTyped ResetFieldsStrategy.t rest.ResetFieldsStrategy.
Admitted.

(* type rest.ResetFieldsFilterStrategy *)
Module ResetFieldsFilterStrategy.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End ResetFieldsFilterStrategy.

Global Instance bounded_size_ResetFieldsFilterStrategy : BoundedTypeSize rest.ResetFieldsFilterStrategy.
Admitted.

Global Instance into_val_ResetFieldsFilterStrategy `{ffi_syntax} : IntoVal ResetFieldsFilterStrategy.t.
Admitted.

Global Instance into_val_typed_ResetFieldsFilterStrategy `{ffi_syntax} : IntoValTyped ResetFieldsFilterStrategy.t rest.ResetFieldsFilterStrategy.
Admitted.

(* type rest.CreateUpdateResetFieldsStrategy *)
Module CreateUpdateResetFieldsStrategy.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End CreateUpdateResetFieldsStrategy.

Global Instance bounded_size_CreateUpdateResetFieldsStrategy : BoundedTypeSize rest.CreateUpdateResetFieldsStrategy.
Admitted.

Global Instance into_val_CreateUpdateResetFieldsStrategy `{ffi_syntax} : IntoVal CreateUpdateResetFieldsStrategy.t.
Admitted.

Global Instance into_val_typed_CreateUpdateResetFieldsStrategy `{ffi_syntax} : IntoValTyped CreateUpdateResetFieldsStrategy.t rest.CreateUpdateResetFieldsStrategy.
Admitted.

(* type rest.UpdateResetFieldsStrategy *)
Module UpdateResetFieldsStrategy.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End UpdateResetFieldsStrategy.

Global Instance bounded_size_UpdateResetFieldsStrategy : BoundedTypeSize rest.UpdateResetFieldsStrategy.
Admitted.

Global Instance into_val_UpdateResetFieldsStrategy `{ffi_syntax} : IntoVal UpdateResetFieldsStrategy.t.
Admitted.

Global Instance into_val_typed_UpdateResetFieldsStrategy `{ffi_syntax} : IntoValTyped UpdateResetFieldsStrategy.t rest.UpdateResetFieldsStrategy.
Admitted.

(* type rest.CorruptObjectDeleterProvider *)
Module CorruptObjectDeleterProvider.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End CorruptObjectDeleterProvider.

Global Instance bounded_size_CorruptObjectDeleterProvider : BoundedTypeSize rest.CorruptObjectDeleterProvider.
Admitted.

Global Instance into_val_CorruptObjectDeleterProvider `{ffi_syntax} : IntoVal CorruptObjectDeleterProvider.t.
Admitted.

Global Instance into_val_typed_CorruptObjectDeleterProvider `{ffi_syntax} : IntoValTyped CorruptObjectDeleterProvider.t rest.CorruptObjectDeleterProvider.
Admitted.

(* type rest.defaultTableConvertor *)
Module defaultTableConvertor.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End defaultTableConvertor.

Global Instance bounded_size_defaultTableConvertor : BoundedTypeSize rest.defaultTableConvertor.
Admitted.

Global Instance into_val_defaultTableConvertor `{ffi_syntax} : IntoVal defaultTableConvertor.t.
Admitted.

Global Instance into_val_typed_defaultTableConvertor `{ffi_syntax} : IntoValTyped defaultTableConvertor.t rest.defaultTableConvertor.
Admitted.

(* type rest.errNotAcceptable *)
Module errNotAcceptable.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End errNotAcceptable.

Global Instance bounded_size_errNotAcceptable : BoundedTypeSize rest.errNotAcceptable.
Admitted.

Global Instance into_val_errNotAcceptable `{ffi_syntax} : IntoVal errNotAcceptable.t.
Admitted.

Global Instance into_val_typed_errNotAcceptable `{ffi_syntax} : IntoValTyped errNotAcceptable.t rest.errNotAcceptable.
Admitted.

(* type rest.RESTUpdateStrategy *)
Module RESTUpdateStrategy.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End RESTUpdateStrategy.

Global Instance bounded_size_RESTUpdateStrategy : BoundedTypeSize rest.RESTUpdateStrategy.
Admitted.

Global Instance into_val_RESTUpdateStrategy `{ffi_syntax} : IntoVal RESTUpdateStrategy.t.
Admitted.

Global Instance into_val_typed_RESTUpdateStrategy `{ffi_syntax} : IntoValTyped RESTUpdateStrategy.t rest.RESTUpdateStrategy.
Admitted.

(* type rest.TransformFunc *)
Module TransformFunc.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End TransformFunc.

Global Instance bounded_size_TransformFunc : BoundedTypeSize rest.TransformFunc.
Admitted.

Global Instance into_val_TransformFunc `{ffi_syntax} : IntoVal TransformFunc.t.
Admitted.

Global Instance into_val_typed_TransformFunc `{ffi_syntax} : IntoValTyped TransformFunc.t rest.TransformFunc.
Admitted.

(* type rest.defaultUpdatedObjectInfo *)
Module defaultUpdatedObjectInfo.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End defaultUpdatedObjectInfo.

Global Instance bounded_size_defaultUpdatedObjectInfo : BoundedTypeSize rest.defaultUpdatedObjectInfo.
Admitted.

Global Instance into_val_defaultUpdatedObjectInfo `{ffi_syntax} : IntoVal defaultUpdatedObjectInfo.t.
Admitted.

Global Instance into_val_typed_defaultUpdatedObjectInfo `{ffi_syntax} : IntoValTyped defaultUpdatedObjectInfo.t rest.defaultUpdatedObjectInfo.
Admitted.

(* type rest.wrappedUpdatedObjectInfo *)
Module wrappedUpdatedObjectInfo.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End wrappedUpdatedObjectInfo.

Global Instance bounded_size_wrappedUpdatedObjectInfo : BoundedTypeSize rest.wrappedUpdatedObjectInfo.
Admitted.

Global Instance into_val_wrappedUpdatedObjectInfo `{ffi_syntax} : IntoVal wrappedUpdatedObjectInfo.t.
Admitted.

Global Instance into_val_typed_wrappedUpdatedObjectInfo `{ffi_syntax} : IntoValTyped wrappedUpdatedObjectInfo.t rest.wrappedUpdatedObjectInfo.
Admitted.

(* type rest.ValidationConfig *)
Module ValidationConfig.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End ValidationConfig.

Global Instance bounded_size_ValidationConfig : BoundedTypeSize rest.ValidationConfig.
Admitted.

Global Instance into_val_ValidationConfig `{ffi_syntax} : IntoVal ValidationConfig.t.
Admitted.

Global Instance into_val_typed_ValidationConfig `{ffi_syntax} : IntoValTyped ValidationConfig.t rest.ValidationConfig.
Admitted.

(* type rest.validationConfigOption *)
Module validationConfigOption.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End validationConfigOption.

Global Instance bounded_size_validationConfigOption : BoundedTypeSize rest.validationConfigOption.
Admitted.

Global Instance into_val_validationConfigOption `{ffi_syntax} : IntoVal validationConfigOption.t.
Admitted.

Global Instance into_val_typed_validationConfigOption `{ffi_syntax} : IntoValTyped validationConfigOption.t rest.validationConfigOption.
Admitted.

Section names.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context `{!globalsGS Σ}.
Context {go_ctx : GoContext}.
#[local] Transparent is_pkg_defined is_pkg_defined_pure.

Global Instance is_pkg_defined_pure_rest : IsPkgDefinedPure rest :=
  {|
    is_pkg_defined_pure_def go_ctx :=
      is_pkg_defined_pure_single rest;
  |}.

#[local] Transparent is_pkg_defined_single is_pkg_defined_pure_single.
Global Program Instance is_pkg_defined_rest : IsPkgDefined rest :=
  {|
    is_pkg_defined_def go_ctx :=
      (is_pkg_defined_single rest)%I
  |}.
Final Obligation. iIntros. iFrame "#%". Qed.
#[local] Opaque is_pkg_defined_single is_pkg_defined_pure_single.

End names.
End rest.
