(* autogenerated from k8s.io/client-go/kubernetes *)
From New.golang Require Import defn.
Module pkg_id.
Definition kubernetes : go_string := "k8s.io/client-go/kubernetes".

End pkg_id.
Export pkg_id.
Module kubernetes.

Definition Interface {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes.Interface"%go [].

#[global] Opaque Interface.

Definition Clientset {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/kubernetes.Clientset"%go [].

#[global] Opaque Clientset.

Axiom Interfaceⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Clientsetⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Definition NewForConfig {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/kubernetes.NewForConfig"%go.

Definition NewForConfigAndClient {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/kubernetes.NewForConfigAndClient"%go.

Definition NewForConfigOrDie {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/kubernetes.NewForConfigOrDie"%go.

Definition New {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/kubernetes.New"%go.

#[global] Instance info' : PkgInfo pkg_id.kubernetes :=
{|
  pkg_imported_pkgs := []
|}.

Axiom _'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.kubernetes (λ: <>,
      exception_do (do:  #())
      ).

Module Interface.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Interface.

Class Interface_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Interface_type_repr  :: go.TypeReprUnderlying Interfaceⁱᵐᵖˡ Interface.t;
  #[global] Interface_underlying :: (Interface) <u (Interfaceⁱᵐᵖˡ);
  #[global] Interfaceⁱᵐᵖˡ_underlying :: (Interfaceⁱᵐᵖˡ) ↓u (Interfaceⁱᵐᵖˡ);
}.

Module Clientset.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Clientset.

Class Clientset_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Clientset_type_repr  :: go.TypeReprUnderlying Clientsetⁱᵐᵖˡ Clientset.t;
  #[global] Clientset_underlying :: (Clientset) <u (Clientsetⁱᵐᵖˡ);
  #[global] Clientsetⁱᵐᵖˡ_underlying :: (Clientsetⁱᵐᵖˡ) ↓u (Clientsetⁱᵐᵖˡ);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Interface_instance :: Interface_Assumptions;
  #[global] Clientset_instance :: Clientset_Assumptions;
}.
End kubernetes.
