(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.golang.theory.

Require Export New.code.k8s_io.kubernetes.pkg.api.v1.pod.

Set Default Proof Using "Type".

Module pod.

(* type pod.ContainerType *)
Module ContainerType.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End ContainerType.

Global Instance bounded_size_ContainerType : BoundedTypeSize pod.ContainerType.
Admitted.

Global Instance into_val_ContainerType `{ffi_syntax} : IntoVal ContainerType.t.
Admitted.

Global Instance into_val_typed_ContainerType `{ffi_syntax} : IntoValTyped ContainerType.t pod.ContainerType.
Admitted.

(* type pod.ContainerVisitor *)
Module ContainerVisitor.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End ContainerVisitor.

Global Instance bounded_size_ContainerVisitor : BoundedTypeSize pod.ContainerVisitor.
Admitted.

Global Instance into_val_ContainerVisitor `{ffi_syntax} : IntoVal ContainerVisitor.t.
Admitted.

Global Instance into_val_typed_ContainerVisitor `{ffi_syntax} : IntoValTyped ContainerVisitor.t pod.ContainerVisitor.
Admitted.

(* type pod.Visitor *)
Module Visitor.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End Visitor.

Global Instance bounded_size_Visitor : BoundedTypeSize pod.Visitor.
Admitted.

Global Instance into_val_Visitor `{ffi_syntax} : IntoVal Visitor.t.
Admitted.

Global Instance into_val_typed_Visitor `{ffi_syntax} : IntoValTyped Visitor.t pod.Visitor.
Admitted.

Section names.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context `{!globalsGS Σ}.
Context {go_ctx : GoContext}.
#[local] Transparent is_pkg_defined is_pkg_defined_pure.

Global Instance is_pkg_defined_pure_pod : IsPkgDefinedPure pod :=
  {|
    is_pkg_defined_pure_def go_ctx :=
      is_pkg_defined_pure_single pod;
  |}.

#[local] Transparent is_pkg_defined_single is_pkg_defined_pure_single.
Global Program Instance is_pkg_defined_pod : IsPkgDefined pod :=
  {|
    is_pkg_defined_def go_ctx :=
      (is_pkg_defined_single pod)%I
  |}.
Final Obligation. iIntros. iFrame "#%". Qed.
#[local] Opaque is_pkg_defined_single is_pkg_defined_pure_single.

End names.
End pod.
