(* autogenerated from k8s.io/apiserver/pkg/registry/rest *)

From New.golang Require Import defn.
Definition rest : go_string := "k8s.io/apiserver/pkg/registry/rest".

Module rest.

Module RESTCreateStrategy. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.RESTCreateStrategy"%go. End RESTCreateStrategy.
Module NamespaceScopedStrategy. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.NamespaceScopedStrategy"%go. End NamespaceScopedStrategy.
Module RESTCreateUpdateStrategy. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.RESTCreateUpdateStrategy"%go. End RESTCreateUpdateStrategy.
Module RESTDeleteStrategy. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.RESTDeleteStrategy"%go. End RESTDeleteStrategy.
Module GarbageCollectionPolicy. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.GarbageCollectionPolicy"%go. End GarbageCollectionPolicy.
Module GarbageCollectionDeleteStrategy. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.GarbageCollectionDeleteStrategy"%go. End GarbageCollectionDeleteStrategy.
Module RESTGracefulDeleteStrategy. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.RESTGracefulDeleteStrategy"%go. End RESTGracefulDeleteStrategy.
Module Storage. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.Storage"%go. End Storage.
Module StorageWithReadiness. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.StorageWithReadiness"%go. End StorageWithReadiness.
Module Scoper. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.Scoper"%go. End Scoper.
Module KindProvider. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.KindProvider"%go. End KindProvider.
Module ShortNamesProvider. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.ShortNamesProvider"%go. End ShortNamesProvider.
Module CategoriesProvider. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.CategoriesProvider"%go. End CategoriesProvider.
Module SingularNameProvider. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.SingularNameProvider"%go. End SingularNameProvider.
Module GroupVersionKindProvider. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.GroupVersionKindProvider"%go. End GroupVersionKindProvider.
Module GroupVersionAcceptor. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.GroupVersionAcceptor"%go. End GroupVersionAcceptor.
Module Lister. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.Lister"%go. End Lister.
Module Getter. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.Getter"%go. End Getter.
Module GetterWithOptions. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.GetterWithOptions"%go. End GetterWithOptions.
Module TableConvertor. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.TableConvertor"%go. End TableConvertor.
Module GracefulDeleter. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.GracefulDeleter"%go. End GracefulDeleter.
Module MayReturnFullObjectDeleter. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.MayReturnFullObjectDeleter"%go. End MayReturnFullObjectDeleter.
Module CollectionDeleter. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.CollectionDeleter"%go. End CollectionDeleter.
Module Creater. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.Creater"%go. End Creater.
Module NamedCreater. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.NamedCreater"%go. End NamedCreater.
Module SubresourceObjectMetaPreserver. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.SubresourceObjectMetaPreserver"%go. End SubresourceObjectMetaPreserver.
Module UpdatedObjectInfo. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.UpdatedObjectInfo"%go. End UpdatedObjectInfo.
Module ValidateObjectFunc. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.ValidateObjectFunc"%go. End ValidateObjectFunc.
Module ValidateObjectUpdateFunc. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.ValidateObjectUpdateFunc"%go. End ValidateObjectUpdateFunc.
Module Updater. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.Updater"%go. End Updater.
Module CreaterUpdater. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.CreaterUpdater"%go. End CreaterUpdater.
Module Patcher. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.Patcher"%go. End Patcher.
Module Watcher. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.Watcher"%go. End Watcher.
Module StandardStorage. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.StandardStorage"%go. End StandardStorage.
Module Redirector. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.Redirector"%go. End Redirector.
Module Responder. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.Responder"%go. End Responder.
Module Connecter. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.Connecter"%go. End Connecter.
Module ResourceStreamer. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.ResourceStreamer"%go. End ResourceStreamer.
Module StorageMetadata. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.StorageMetadata"%go. End StorageMetadata.
Module StorageVersionProvider. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.StorageVersionProvider"%go. End StorageVersionProvider.
Module ResetFieldsStrategy. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.ResetFieldsStrategy"%go. End ResetFieldsStrategy.
Module ResetFieldsFilterStrategy. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.ResetFieldsFilterStrategy"%go. End ResetFieldsFilterStrategy.
Module CreateUpdateResetFieldsStrategy. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.CreateUpdateResetFieldsStrategy"%go. End CreateUpdateResetFieldsStrategy.
Module UpdateResetFieldsStrategy. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.UpdateResetFieldsStrategy"%go. End UpdateResetFieldsStrategy.
Module CorruptObjectDeleterProvider. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.CorruptObjectDeleterProvider"%go. End CorruptObjectDeleterProvider.
Module defaultTableConvertor. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.defaultTableConvertor"%go. End defaultTableConvertor.
Module errNotAcceptable. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.errNotAcceptable"%go. End errNotAcceptable.
Module RESTUpdateStrategy. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.RESTUpdateStrategy"%go. End RESTUpdateStrategy.
Module TransformFunc. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.TransformFunc"%go. End TransformFunc.
Module defaultUpdatedObjectInfo. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.defaultUpdatedObjectInfo"%go. End defaultUpdatedObjectInfo.
Module wrappedUpdatedObjectInfo. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.wrappedUpdatedObjectInfo"%go. End wrappedUpdatedObjectInfo.
Module ValidationConfig. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.ValidationConfig"%go. End ValidationConfig.
Module validationConfigOption. Definition id : go_string := "k8s.io/apiserver/pkg/registry/rest.validationConfigOption"%go. End validationConfigOption.

Section code.
Context `{ffi_syntax}.


Axiom RESTCreateStrategy : go_type.

Definition BeforeCreate : go_string := "k8s.io/apiserver/pkg/registry/rest.BeforeCreate"%go.

Definition CheckGeneratedNameError : go_string := "k8s.io/apiserver/pkg/registry/rest.CheckGeneratedNameError"%go.

Definition objectMetaAndKind : go_string := "k8s.io/apiserver/pkg/registry/rest.objectMetaAndKind"%go.

Axiom NamespaceScopedStrategy : go_type.

Definition AdmissionToValidateObjectFunc : go_string := "k8s.io/apiserver/pkg/registry/rest.AdmissionToValidateObjectFunc"%go.

Axiom RESTCreateUpdateStrategy : go_type.

Axiom RESTDeleteStrategy : go_type.

Axiom GarbageCollectionPolicy : go_type.

Axiom DeleteDependents : val.

Axiom OrphanDependents : val.

Axiom Unsupported : val.

Axiom GarbageCollectionDeleteStrategy : go_type.

Axiom RESTGracefulDeleteStrategy : go_type.

Definition BeforeDelete : go_string := "k8s.io/apiserver/pkg/registry/rest.BeforeDelete"%go.

Definition AdmissionToValidateObjectDeleteFunc : go_string := "k8s.io/apiserver/pkg/registry/rest.AdmissionToValidateObjectDeleteFunc"%go.

Definition metav1Now : go_string := "k8s.io/apiserver/pkg/registry/rest.metav1Now"%go.

Axiom metav1Now'init : val.

Definition WipeObjectMetaSystemFields : go_string := "k8s.io/apiserver/pkg/registry/rest.WipeObjectMetaSystemFields"%go.

Definition FillObjectMetaSystemFields : go_string := "k8s.io/apiserver/pkg/registry/rest.FillObjectMetaSystemFields"%go.

Definition EnsureObjectNamespaceMatchesRequestNamespace : go_string := "k8s.io/apiserver/pkg/registry/rest.EnsureObjectNamespaceMatchesRequestNamespace"%go.

Definition ExpectedNamespaceForScope : go_string := "k8s.io/apiserver/pkg/registry/rest.ExpectedNamespaceForScope"%go.

Definition ExpectedNamespaceForResource : go_string := "k8s.io/apiserver/pkg/registry/rest.ExpectedNamespaceForResource"%go.

Axiom Storage : go_type.

Axiom StorageWithReadiness : go_type.

Axiom Scoper : go_type.

Axiom KindProvider : go_type.

Axiom ShortNamesProvider : go_type.

Axiom CategoriesProvider : go_type.

Axiom SingularNameProvider : go_type.

Axiom GroupVersionKindProvider : go_type.

Axiom GroupVersionAcceptor : go_type.

Axiom Lister : go_type.

Axiom Getter : go_type.

Axiom GetterWithOptions : go_type.

Axiom TableConvertor : go_type.

Axiom GracefulDeleter : go_type.

Axiom MayReturnFullObjectDeleter : go_type.

Axiom CollectionDeleter : go_type.

Axiom Creater : go_type.

Axiom NamedCreater : go_type.

Axiom SubresourceObjectMetaPreserver : go_type.

Axiom UpdatedObjectInfo : go_type.

Axiom ValidateObjectFunc : go_type.

Definition ValidateAllObjectFunc : go_string := "k8s.io/apiserver/pkg/registry/rest.ValidateAllObjectFunc"%go.

Axiom ValidateObjectUpdateFunc : go_type.

Definition ValidateAllObjectUpdateFunc : go_string := "k8s.io/apiserver/pkg/registry/rest.ValidateAllObjectUpdateFunc"%go.

Axiom Updater : go_type.

Axiom CreaterUpdater : go_type.

Axiom Patcher : go_type.

Axiom Watcher : go_type.

Axiom StandardStorage : go_type.

Axiom Redirector : go_type.

Axiom Responder : go_type.

Axiom Connecter : go_type.

Axiom ResourceStreamer : go_type.

Axiom StorageMetadata : go_type.

Axiom StorageVersionProvider : go_type.

Axiom ResetFieldsStrategy : go_type.

Axiom ResetFieldsFilterStrategy : go_type.

Axiom CreateUpdateResetFieldsStrategy : go_type.

Axiom UpdateResetFieldsStrategy : go_type.

Axiom CorruptObjectDeleterProvider : go_type.

Axiom defaultTableConvertor : go_type.

Definition NewDefaultTableConvertor : go_string := "k8s.io/apiserver/pkg/registry/rest.NewDefaultTableConvertor"%go.

Definition swaggerMetadataDescriptions : go_string := "k8s.io/apiserver/pkg/registry/rest.swaggerMetadataDescriptions"%go.

Axiom swaggerMetadataDescriptions'init : val.

Axiom errNotAcceptable : go_type.

Axiom RESTUpdateStrategy : go_type.

Definition validateCommonFields : go_string := "k8s.io/apiserver/pkg/registry/rest.validateCommonFields"%go.

Definition BeforeUpdate : go_string := "k8s.io/apiserver/pkg/registry/rest.BeforeUpdate"%go.

Axiom TransformFunc : go_type.

Axiom defaultUpdatedObjectInfo : go_type.

Definition DefaultUpdatedObjectInfo : go_string := "k8s.io/apiserver/pkg/registry/rest.DefaultUpdatedObjectInfo"%go.

Axiom wrappedUpdatedObjectInfo : go_type.

Definition WrapUpdatedObjectInfo : go_string := "k8s.io/apiserver/pkg/registry/rest.WrapUpdatedObjectInfo"%go.

Definition AdmissionToValidateObjectUpdateFunc : go_string := "k8s.io/apiserver/pkg/registry/rest.AdmissionToValidateObjectUpdateFunc"%go.

Axiom ValidationConfig : go_type.

Definition WithOptions : go_string := "k8s.io/apiserver/pkg/registry/rest.WithOptions"%go.

Definition WithTakeover : go_string := "k8s.io/apiserver/pkg/registry/rest.WithTakeover"%go.

Definition WithSubresourceMapper : go_string := "k8s.io/apiserver/pkg/registry/rest.WithSubresourceMapper"%go.

Axiom validationConfigOption : go_type.

Definition ValidateDeclaratively : go_string := "k8s.io/apiserver/pkg/registry/rest.ValidateDeclaratively"%go.

Definition ValidateUpdateDeclaratively : go_string := "k8s.io/apiserver/pkg/registry/rest.ValidateUpdateDeclaratively"%go.

Definition validateDeclaratively : go_string := "k8s.io/apiserver/pkg/registry/rest.validateDeclaratively"%go.

Definition requestInfo : go_string := "k8s.io/apiserver/pkg/registry/rest.requestInfo"%go.

Definition parseSubresourcePath : go_string := "k8s.io/apiserver/pkg/registry/rest.parseSubresourcePath"%go.

Definition CompareDeclarativeErrorsAndEmitMismatches : go_string := "k8s.io/apiserver/pkg/registry/rest.CompareDeclarativeErrorsAndEmitMismatches"%go.

Definition gatherDeclarativeValidationMismatches : go_string := "k8s.io/apiserver/pkg/registry/rest.gatherDeclarativeValidationMismatches"%go.

Definition createDeclarativeValidationPanicHandler : go_string := "k8s.io/apiserver/pkg/registry/rest.createDeclarativeValidationPanicHandler"%go.

Definition panicSafeValidateFunc : go_string := "k8s.io/apiserver/pkg/registry/rest.panicSafeValidateFunc"%go.

Definition vars' : list (go_string * go_type) := [].

Axiom BeforeCreateⁱᵐᵖˡ : val.

Axiom CheckGeneratedNameErrorⁱᵐᵖˡ : val.

Axiom objectMetaAndKindⁱᵐᵖˡ : val.

Axiom AdmissionToValidateObjectFuncⁱᵐᵖˡ : val.

Axiom BeforeDeleteⁱᵐᵖˡ : val.

Axiom AdmissionToValidateObjectDeleteFuncⁱᵐᵖˡ : val.

Axiom WipeObjectMetaSystemFieldsⁱᵐᵖˡ : val.

Axiom FillObjectMetaSystemFieldsⁱᵐᵖˡ : val.

Axiom EnsureObjectNamespaceMatchesRequestNamespaceⁱᵐᵖˡ : val.

Axiom ExpectedNamespaceForScopeⁱᵐᵖˡ : val.

Axiom ExpectedNamespaceForResourceⁱᵐᵖˡ : val.

Axiom ValidateAllObjectFuncⁱᵐᵖˡ : val.

Axiom ValidateAllObjectUpdateFuncⁱᵐᵖˡ : val.

Axiom NewDefaultTableConvertorⁱᵐᵖˡ : val.

Axiom validateCommonFieldsⁱᵐᵖˡ : val.

Axiom BeforeUpdateⁱᵐᵖˡ : val.

Axiom DefaultUpdatedObjectInfoⁱᵐᵖˡ : val.

Axiom WrapUpdatedObjectInfoⁱᵐᵖˡ : val.

Axiom AdmissionToValidateObjectUpdateFuncⁱᵐᵖˡ : val.

Axiom WithOptionsⁱᵐᵖˡ : val.

Axiom WithTakeoverⁱᵐᵖˡ : val.

Axiom WithSubresourceMapperⁱᵐᵖˡ : val.

Axiom ValidateDeclarativelyⁱᵐᵖˡ : val.

Axiom ValidateUpdateDeclarativelyⁱᵐᵖˡ : val.

Axiom validateDeclarativelyⁱᵐᵖˡ : val.

Axiom requestInfoⁱᵐᵖˡ : val.

Axiom parseSubresourcePathⁱᵐᵖˡ : val.

Axiom CompareDeclarativeErrorsAndEmitMismatchesⁱᵐᵖˡ : val.

Axiom gatherDeclarativeValidationMismatchesⁱᵐᵖˡ : val.

Axiom createDeclarativeValidationPanicHandlerⁱᵐᵖˡ : val.

Axiom panicSafeValidateFuncⁱᵐᵖˡ : val.

Definition functions' : list (go_string * val) := [(BeforeCreate, BeforeCreateⁱᵐᵖˡ); (CheckGeneratedNameError, CheckGeneratedNameErrorⁱᵐᵖˡ); (objectMetaAndKind, objectMetaAndKindⁱᵐᵖˡ); (AdmissionToValidateObjectFunc, AdmissionToValidateObjectFuncⁱᵐᵖˡ); (BeforeDelete, BeforeDeleteⁱᵐᵖˡ); (AdmissionToValidateObjectDeleteFunc, AdmissionToValidateObjectDeleteFuncⁱᵐᵖˡ); (WipeObjectMetaSystemFields, WipeObjectMetaSystemFieldsⁱᵐᵖˡ); (FillObjectMetaSystemFields, FillObjectMetaSystemFieldsⁱᵐᵖˡ); (EnsureObjectNamespaceMatchesRequestNamespace, EnsureObjectNamespaceMatchesRequestNamespaceⁱᵐᵖˡ); (ExpectedNamespaceForScope, ExpectedNamespaceForScopeⁱᵐᵖˡ); (ExpectedNamespaceForResource, ExpectedNamespaceForResourceⁱᵐᵖˡ); (ValidateAllObjectFunc, ValidateAllObjectFuncⁱᵐᵖˡ); (ValidateAllObjectUpdateFunc, ValidateAllObjectUpdateFuncⁱᵐᵖˡ); (NewDefaultTableConvertor, NewDefaultTableConvertorⁱᵐᵖˡ); (validateCommonFields, validateCommonFieldsⁱᵐᵖˡ); (BeforeUpdate, BeforeUpdateⁱᵐᵖˡ); (DefaultUpdatedObjectInfo, DefaultUpdatedObjectInfoⁱᵐᵖˡ); (WrapUpdatedObjectInfo, WrapUpdatedObjectInfoⁱᵐᵖˡ); (AdmissionToValidateObjectUpdateFunc, AdmissionToValidateObjectUpdateFuncⁱᵐᵖˡ); (WithOptions, WithOptionsⁱᵐᵖˡ); (WithTakeover, WithTakeoverⁱᵐᵖˡ); (WithSubresourceMapper, WithSubresourceMapperⁱᵐᵖˡ); (ValidateDeclaratively, ValidateDeclarativelyⁱᵐᵖˡ); (ValidateUpdateDeclaratively, ValidateUpdateDeclarativelyⁱᵐᵖˡ); (validateDeclaratively, validateDeclarativelyⁱᵐᵖˡ); (requestInfo, requestInfoⁱᵐᵖˡ); (parseSubresourcePath, parseSubresourcePathⁱᵐᵖˡ); (CompareDeclarativeErrorsAndEmitMismatches, CompareDeclarativeErrorsAndEmitMismatchesⁱᵐᵖˡ); (gatherDeclarativeValidationMismatches, gatherDeclarativeValidationMismatchesⁱᵐᵖˡ); (createDeclarativeValidationPanicHandler, createDeclarativeValidationPanicHandlerⁱᵐᵖˡ); (panicSafeValidateFunc, panicSafeValidateFuncⁱᵐᵖˡ)].

Axiom defaultTableConvertor__ConvertToTableⁱᵐᵖˡ : val.

Axiom errNotAcceptable__Errorⁱᵐᵖˡ : val.

Axiom errNotAcceptable__Statusⁱᵐᵖˡ : val.

Axiom defaultUpdatedObjectInfo__Preconditionsⁱᵐᵖˡ : val.

Axiom defaultUpdatedObjectInfo__UpdatedObjectⁱᵐᵖˡ : val.

Axiom wrappedUpdatedObjectInfo__Preconditionsⁱᵐᵖˡ : val.

Axiom wrappedUpdatedObjectInfo__UpdatedObjectⁱᵐᵖˡ : val.

Definition msets' : list (go_string * (list (go_string * val))) := [(GarbageCollectionPolicy.id, []); (ptrT.id GarbageCollectionPolicy.id, []); (ValidateObjectFunc.id, []); (ptrT.id ValidateObjectFunc.id, []); (ValidateObjectUpdateFunc.id, []); (ptrT.id ValidateObjectUpdateFunc.id, []); (defaultTableConvertor.id, [("ConvertToTable"%go, defaultTableConvertor__ConvertToTableⁱᵐᵖˡ)]); (ptrT.id defaultTableConvertor.id, [("ConvertToTable"%go, defaultTableConvertor__ConvertToTableⁱᵐᵖˡ)]); (errNotAcceptable.id, [("Error"%go, errNotAcceptable__Errorⁱᵐᵖˡ); ("Status"%go, errNotAcceptable__Statusⁱᵐᵖˡ)]); (ptrT.id errNotAcceptable.id, [("Error"%go, errNotAcceptable__Errorⁱᵐᵖˡ); ("Status"%go, errNotAcceptable__Statusⁱᵐᵖˡ)]); (TransformFunc.id, []); (ptrT.id TransformFunc.id, []); (defaultUpdatedObjectInfo.id, []); (ptrT.id defaultUpdatedObjectInfo.id, [("Preconditions"%go, defaultUpdatedObjectInfo__Preconditionsⁱᵐᵖˡ); ("UpdatedObject"%go, defaultUpdatedObjectInfo__UpdatedObjectⁱᵐᵖˡ)]); (wrappedUpdatedObjectInfo.id, []); (ptrT.id wrappedUpdatedObjectInfo.id, [("Preconditions"%go, wrappedUpdatedObjectInfo__Preconditionsⁱᵐᵖˡ); ("UpdatedObject"%go, wrappedUpdatedObjectInfo__UpdatedObjectⁱᵐᵖˡ)]); (ValidationConfig.id, []); (ptrT.id ValidationConfig.id, []); (validationConfigOption.id, []); (ptrT.id validationConfigOption.id, [])].

#[global] Instance info' : PkgInfo rest.rest :=
  {|
    pkg_vars := vars';
    pkg_functions := functions';
    pkg_msets := msets';
    pkg_imported_pkgs := [];
  |}.

Axiom _'init : val.

Definition initialize' : val :=
  λ: <>,
    package.init #rest.rest (λ: <>,
      exception_do (do:  (package.alloc rest.rest #());;;
      do:  (_'init #());;;
      do:  (_'init #());;;
      do:  (metav1Now'init #());;;
      do:  (_'init #());;;
      do:  (swaggerMetadataDescriptions'init #()))
      ).

End code.
End rest.
