(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.golang.theory.

Require Export New.code.k8s_io.kubernetes.pkg.controller.replicaset.config.

Set Default Proof Using "Type".

Module config.

(* type config.ReplicaSetControllerConfiguration *)
Module ReplicaSetControllerConfiguration.
Section def.
Context `{ffi_syntax}.
Record t := mk {
  ConcurrentRSSyncs' : w32;
}.
End def.
End ReplicaSetControllerConfiguration.

Section instances.
Context `{ffi_syntax}.

Global Instance settable_ReplicaSetControllerConfiguration : Settable ReplicaSetControllerConfiguration.t :=
  settable! ReplicaSetControllerConfiguration.mk < ReplicaSetControllerConfiguration.ConcurrentRSSyncs' >.
Global Instance into_val_ReplicaSetControllerConfiguration : IntoVal ReplicaSetControllerConfiguration.t :=
  {| to_val_def v :=
    struct.val_aux config.ReplicaSetControllerConfiguration [
    "ConcurrentRSSyncs" ::= #(ReplicaSetControllerConfiguration.ConcurrentRSSyncs' v)
    ]%struct
  |}.

Global Program Instance into_val_typed_ReplicaSetControllerConfiguration : IntoValTyped ReplicaSetControllerConfiguration.t config.ReplicaSetControllerConfiguration :=
{|
  default_val := ReplicaSetControllerConfiguration.mk (default_val _);
|}.
Next Obligation. solve_to_val_type. Qed.
Next Obligation. solve_zero_val. Qed.
Next Obligation. solve_to_val_inj. Qed.
Final Obligation. solve_decision. Qed.

Global Instance into_val_struct_field_ReplicaSetControllerConfiguration_ConcurrentRSSyncs : IntoValStructField "ConcurrentRSSyncs" config.ReplicaSetControllerConfiguration ReplicaSetControllerConfiguration.ConcurrentRSSyncs'.
Proof. solve_into_val_struct_field. Qed.


Context `{!ffi_model, !ffi_semantics _ _, !ffi_interp _, !heapGS Σ}.
Global Instance wp_struct_make_ReplicaSetControllerConfiguration ConcurrentRSSyncs':
  PureWp True
    (struct.make #config.ReplicaSetControllerConfiguration (alist_val [
      "ConcurrentRSSyncs" ::= #ConcurrentRSSyncs'
    ]))%struct
    #(ReplicaSetControllerConfiguration.mk ConcurrentRSSyncs').
Proof. solve_struct_make_pure_wp. Qed.


Global Instance ReplicaSetControllerConfiguration_struct_fields_split dq l (v : ReplicaSetControllerConfiguration.t) :
  StructFieldsSplit dq l v (
    "HConcurrentRSSyncs" ∷ l ↦s[config.ReplicaSetControllerConfiguration :: "ConcurrentRSSyncs"]{dq} v.(ReplicaSetControllerConfiguration.ConcurrentRSSyncs')
  ).
Proof.
  rewrite /named.
  apply struct_fields_split_intro.
  unfold_typed_pointsto; split_pointsto_app.

  rewrite -!/(typed_pointsto_def _ _ _) -!typed_pointsto_unseal.

  solve_field_ref_f.
Qed.

End instances.

Section names.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context `{!globalsGS Σ}.
Context {go_ctx : GoContext}.
#[local] Transparent is_pkg_defined is_pkg_defined_pure.

Global Instance is_pkg_defined_pure_config : IsPkgDefinedPure config :=
  {|
    is_pkg_defined_pure_def go_ctx :=
      is_pkg_defined_pure_single config;
  |}.

#[local] Transparent is_pkg_defined_single is_pkg_defined_pure_single.
Global Program Instance is_pkg_defined_config : IsPkgDefined config :=
  {|
    is_pkg_defined_def go_ctx :=
      (is_pkg_defined_single config)%I
  |}.
Final Obligation. iIntros. iFrame "#%". Qed.
#[local] Opaque is_pkg_defined_single is_pkg_defined_pure_single.

Global Instance wp_method_call_ReplicaSetControllerConfiguration'ptr_DeepCopy :
  WpMethodCall (ptrT.id config.ReplicaSetControllerConfiguration.id) "DeepCopy" _ (is_pkg_defined config) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_ReplicaSetControllerConfiguration'ptr_DeepCopyInto :
  WpMethodCall (ptrT.id config.ReplicaSetControllerConfiguration.id) "DeepCopyInto" _ (is_pkg_defined config) :=
  ltac:(solve_wp_method_call).

End names.
End config.
