(* autogenerated from k8s.io/client-go/applyconfigurations/apps/v1 *)
From New.golang Require Import defn.
Module pkg_id.
Definition v1 : go_string := "k8s.io/client-go/applyconfigurations/apps/v1".

End pkg_id.
Export pkg_id.
Module v1.

Definition ControllerRevisionApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.ControllerRevisionApplyConfiguration"%go [].

#[global] Opaque ControllerRevisionApplyConfiguration.

Definition DaemonSetApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.DaemonSetApplyConfiguration"%go [].

#[global] Opaque DaemonSetApplyConfiguration.

Definition DaemonSetConditionApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.DaemonSetConditionApplyConfiguration"%go [].

#[global] Opaque DaemonSetConditionApplyConfiguration.

Definition DaemonSetSpecApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.DaemonSetSpecApplyConfiguration"%go [].

#[global] Opaque DaemonSetSpecApplyConfiguration.

Definition DaemonSetStatusApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.DaemonSetStatusApplyConfiguration"%go [].

#[global] Opaque DaemonSetStatusApplyConfiguration.

Definition DaemonSetUpdateStrategyApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.DaemonSetUpdateStrategyApplyConfiguration"%go [].

#[global] Opaque DaemonSetUpdateStrategyApplyConfiguration.

Definition DeploymentApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.DeploymentApplyConfiguration"%go [].

#[global] Opaque DeploymentApplyConfiguration.

Definition DeploymentConditionApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.DeploymentConditionApplyConfiguration"%go [].

#[global] Opaque DeploymentConditionApplyConfiguration.

Definition DeploymentSpecApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.DeploymentSpecApplyConfiguration"%go [].

#[global] Opaque DeploymentSpecApplyConfiguration.

Definition DeploymentStatusApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.DeploymentStatusApplyConfiguration"%go [].

#[global] Opaque DeploymentStatusApplyConfiguration.

Definition DeploymentStrategyApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.DeploymentStrategyApplyConfiguration"%go [].

#[global] Opaque DeploymentStrategyApplyConfiguration.

Definition ReplicaSetApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.ReplicaSetApplyConfiguration"%go [].

#[global] Opaque ReplicaSetApplyConfiguration.

Definition ReplicaSetConditionApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.ReplicaSetConditionApplyConfiguration"%go [].

#[global] Opaque ReplicaSetConditionApplyConfiguration.

Definition ReplicaSetSpecApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.ReplicaSetSpecApplyConfiguration"%go [].

#[global] Opaque ReplicaSetSpecApplyConfiguration.

Definition ReplicaSetStatusApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.ReplicaSetStatusApplyConfiguration"%go [].

#[global] Opaque ReplicaSetStatusApplyConfiguration.

Definition RollingUpdateDaemonSetApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.RollingUpdateDaemonSetApplyConfiguration"%go [].

#[global] Opaque RollingUpdateDaemonSetApplyConfiguration.

Definition RollingUpdateDeploymentApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.RollingUpdateDeploymentApplyConfiguration"%go [].

#[global] Opaque RollingUpdateDeploymentApplyConfiguration.

Definition RollingUpdateStatefulSetStrategyApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.RollingUpdateStatefulSetStrategyApplyConfiguration"%go [].

#[global] Opaque RollingUpdateStatefulSetStrategyApplyConfiguration.

Definition StatefulSetApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.StatefulSetApplyConfiguration"%go [].

#[global] Opaque StatefulSetApplyConfiguration.

Definition StatefulSetConditionApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.StatefulSetConditionApplyConfiguration"%go [].

#[global] Opaque StatefulSetConditionApplyConfiguration.

Definition StatefulSetOrdinalsApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.StatefulSetOrdinalsApplyConfiguration"%go [].

#[global] Opaque StatefulSetOrdinalsApplyConfiguration.

Definition StatefulSetPersistentVolumeClaimRetentionPolicyApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.StatefulSetPersistentVolumeClaimRetentionPolicyApplyConfiguration"%go [].

#[global] Opaque StatefulSetPersistentVolumeClaimRetentionPolicyApplyConfiguration.

Definition StatefulSetSpecApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.StatefulSetSpecApplyConfiguration"%go [].

#[global] Opaque StatefulSetSpecApplyConfiguration.

Definition StatefulSetStatusApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.StatefulSetStatusApplyConfiguration"%go [].

#[global] Opaque StatefulSetStatusApplyConfiguration.

Definition StatefulSetUpdateStrategyApplyConfiguration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/applyconfigurations/apps/v1.StatefulSetUpdateStrategyApplyConfiguration"%go [].

#[global] Opaque StatefulSetUpdateStrategyApplyConfiguration.

Axiom ControllerRevisionApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom DaemonSetApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom DaemonSetConditionApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom DaemonSetSpecApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom DaemonSetStatusApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom DaemonSetUpdateStrategyApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom DeploymentApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom DeploymentConditionApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom DeploymentSpecApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom DeploymentStatusApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom DeploymentStrategyApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom ReplicaSetApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom ReplicaSetConditionApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom ReplicaSetSpecApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom ReplicaSetStatusApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom RollingUpdateDaemonSetApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom RollingUpdateDeploymentApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom RollingUpdateStatefulSetStrategyApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom StatefulSetApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom StatefulSetConditionApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom StatefulSetOrdinalsApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom StatefulSetPersistentVolumeClaimRetentionPolicyApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom StatefulSetSpecApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom StatefulSetStatusApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom StatefulSetUpdateStrategyApplyConfigurationⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Definition ControllerRevision {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.ControllerRevision"%go.

Definition ExtractControllerRevision {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.ExtractControllerRevision"%go.

Definition ExtractControllerRevisionStatus {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.ExtractControllerRevisionStatus"%go.

Definition extractControllerRevision {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.extractControllerRevision"%go.

Definition DaemonSet {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.DaemonSet"%go.

Definition ExtractDaemonSet {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.ExtractDaemonSet"%go.

Definition ExtractDaemonSetStatus {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.ExtractDaemonSetStatus"%go.

Definition extractDaemonSet {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.extractDaemonSet"%go.

Definition DaemonSetCondition {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.DaemonSetCondition"%go.

Definition DaemonSetSpec {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.DaemonSetSpec"%go.

Definition DaemonSetStatus {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.DaemonSetStatus"%go.

Definition DaemonSetUpdateStrategy {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.DaemonSetUpdateStrategy"%go.

Definition Deployment {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.Deployment"%go.

Definition ExtractDeployment {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.ExtractDeployment"%go.

Definition ExtractDeploymentStatus {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.ExtractDeploymentStatus"%go.

Definition extractDeployment {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.extractDeployment"%go.

Definition DeploymentCondition {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.DeploymentCondition"%go.

Definition DeploymentSpec {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.DeploymentSpec"%go.

Definition DeploymentStatus {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.DeploymentStatus"%go.

Definition DeploymentStrategy {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.DeploymentStrategy"%go.

Definition ReplicaSet {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.ReplicaSet"%go.

Definition ExtractReplicaSet {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.ExtractReplicaSet"%go.

Definition ExtractReplicaSetStatus {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.ExtractReplicaSetStatus"%go.

Definition extractReplicaSet {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.extractReplicaSet"%go.

Definition ReplicaSetCondition {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.ReplicaSetCondition"%go.

Definition ReplicaSetSpec {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.ReplicaSetSpec"%go.

Definition ReplicaSetStatus {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.ReplicaSetStatus"%go.

Definition RollingUpdateDaemonSet {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.RollingUpdateDaemonSet"%go.

Definition RollingUpdateDeployment {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.RollingUpdateDeployment"%go.

Definition RollingUpdateStatefulSetStrategy {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.RollingUpdateStatefulSetStrategy"%go.

Definition StatefulSet {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.StatefulSet"%go.

Definition ExtractStatefulSet {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.ExtractStatefulSet"%go.

Definition ExtractStatefulSetStatus {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.ExtractStatefulSetStatus"%go.

Definition extractStatefulSet {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.extractStatefulSet"%go.

Definition StatefulSetCondition {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.StatefulSetCondition"%go.

Definition StatefulSetOrdinals {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.StatefulSetOrdinals"%go.

Definition StatefulSetPersistentVolumeClaimRetentionPolicy {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.StatefulSetPersistentVolumeClaimRetentionPolicy"%go.

Definition StatefulSetSpec {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.StatefulSetSpec"%go.

Definition StatefulSetStatus {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.StatefulSetStatus"%go.

Definition StatefulSetUpdateStrategy {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/applyconfigurations/apps/v1.StatefulSetUpdateStrategy"%go.

#[global] Instance info' : PkgInfo pkg_id.v1 :=
{|
  pkg_imported_pkgs := []
|}.

Axiom _'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.v1 (λ: <>,
      exception_do (do:  #())
      ).

Module ControllerRevisionApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End ControllerRevisionApplyConfiguration.

Class ControllerRevisionApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] ControllerRevisionApplyConfiguration_type_repr  :: go.TypeReprUnderlying ControllerRevisionApplyConfigurationⁱᵐᵖˡ ControllerRevisionApplyConfiguration.t;
  #[global] ControllerRevisionApplyConfiguration_underlying :: (ControllerRevisionApplyConfiguration) <u (ControllerRevisionApplyConfigurationⁱᵐᵖˡ);
  #[global] ControllerRevisionApplyConfigurationⁱᵐᵖˡ_underlying :: (ControllerRevisionApplyConfigurationⁱᵐᵖˡ) ↓u (ControllerRevisionApplyConfigurationⁱᵐᵖˡ);
}.

Module DaemonSetApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End DaemonSetApplyConfiguration.

Class DaemonSetApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] DaemonSetApplyConfiguration_type_repr  :: go.TypeReprUnderlying DaemonSetApplyConfigurationⁱᵐᵖˡ DaemonSetApplyConfiguration.t;
  #[global] DaemonSetApplyConfiguration_underlying :: (DaemonSetApplyConfiguration) <u (DaemonSetApplyConfigurationⁱᵐᵖˡ);
  #[global] DaemonSetApplyConfigurationⁱᵐᵖˡ_underlying :: (DaemonSetApplyConfigurationⁱᵐᵖˡ) ↓u (DaemonSetApplyConfigurationⁱᵐᵖˡ);
}.

Module DaemonSetConditionApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End DaemonSetConditionApplyConfiguration.

Class DaemonSetConditionApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] DaemonSetConditionApplyConfiguration_type_repr  :: go.TypeReprUnderlying DaemonSetConditionApplyConfigurationⁱᵐᵖˡ DaemonSetConditionApplyConfiguration.t;
  #[global] DaemonSetConditionApplyConfiguration_underlying :: (DaemonSetConditionApplyConfiguration) <u (DaemonSetConditionApplyConfigurationⁱᵐᵖˡ);
  #[global] DaemonSetConditionApplyConfigurationⁱᵐᵖˡ_underlying :: (DaemonSetConditionApplyConfigurationⁱᵐᵖˡ) ↓u (DaemonSetConditionApplyConfigurationⁱᵐᵖˡ);
}.

Module DaemonSetSpecApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End DaemonSetSpecApplyConfiguration.

Class DaemonSetSpecApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] DaemonSetSpecApplyConfiguration_type_repr  :: go.TypeReprUnderlying DaemonSetSpecApplyConfigurationⁱᵐᵖˡ DaemonSetSpecApplyConfiguration.t;
  #[global] DaemonSetSpecApplyConfiguration_underlying :: (DaemonSetSpecApplyConfiguration) <u (DaemonSetSpecApplyConfigurationⁱᵐᵖˡ);
  #[global] DaemonSetSpecApplyConfigurationⁱᵐᵖˡ_underlying :: (DaemonSetSpecApplyConfigurationⁱᵐᵖˡ) ↓u (DaemonSetSpecApplyConfigurationⁱᵐᵖˡ);
}.

Module DaemonSetStatusApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End DaemonSetStatusApplyConfiguration.

Class DaemonSetStatusApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] DaemonSetStatusApplyConfiguration_type_repr  :: go.TypeReprUnderlying DaemonSetStatusApplyConfigurationⁱᵐᵖˡ DaemonSetStatusApplyConfiguration.t;
  #[global] DaemonSetStatusApplyConfiguration_underlying :: (DaemonSetStatusApplyConfiguration) <u (DaemonSetStatusApplyConfigurationⁱᵐᵖˡ);
  #[global] DaemonSetStatusApplyConfigurationⁱᵐᵖˡ_underlying :: (DaemonSetStatusApplyConfigurationⁱᵐᵖˡ) ↓u (DaemonSetStatusApplyConfigurationⁱᵐᵖˡ);
}.

Module DaemonSetUpdateStrategyApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End DaemonSetUpdateStrategyApplyConfiguration.

Class DaemonSetUpdateStrategyApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] DaemonSetUpdateStrategyApplyConfiguration_type_repr  :: go.TypeReprUnderlying DaemonSetUpdateStrategyApplyConfigurationⁱᵐᵖˡ DaemonSetUpdateStrategyApplyConfiguration.t;
  #[global] DaemonSetUpdateStrategyApplyConfiguration_underlying :: (DaemonSetUpdateStrategyApplyConfiguration) <u (DaemonSetUpdateStrategyApplyConfigurationⁱᵐᵖˡ);
  #[global] DaemonSetUpdateStrategyApplyConfigurationⁱᵐᵖˡ_underlying :: (DaemonSetUpdateStrategyApplyConfigurationⁱᵐᵖˡ) ↓u (DaemonSetUpdateStrategyApplyConfigurationⁱᵐᵖˡ);
}.

Module DeploymentApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End DeploymentApplyConfiguration.

Class DeploymentApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] DeploymentApplyConfiguration_type_repr  :: go.TypeReprUnderlying DeploymentApplyConfigurationⁱᵐᵖˡ DeploymentApplyConfiguration.t;
  #[global] DeploymentApplyConfiguration_underlying :: (DeploymentApplyConfiguration) <u (DeploymentApplyConfigurationⁱᵐᵖˡ);
  #[global] DeploymentApplyConfigurationⁱᵐᵖˡ_underlying :: (DeploymentApplyConfigurationⁱᵐᵖˡ) ↓u (DeploymentApplyConfigurationⁱᵐᵖˡ);
}.

Module DeploymentConditionApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End DeploymentConditionApplyConfiguration.

Class DeploymentConditionApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] DeploymentConditionApplyConfiguration_type_repr  :: go.TypeReprUnderlying DeploymentConditionApplyConfigurationⁱᵐᵖˡ DeploymentConditionApplyConfiguration.t;
  #[global] DeploymentConditionApplyConfiguration_underlying :: (DeploymentConditionApplyConfiguration) <u (DeploymentConditionApplyConfigurationⁱᵐᵖˡ);
  #[global] DeploymentConditionApplyConfigurationⁱᵐᵖˡ_underlying :: (DeploymentConditionApplyConfigurationⁱᵐᵖˡ) ↓u (DeploymentConditionApplyConfigurationⁱᵐᵖˡ);
}.

Module DeploymentSpecApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End DeploymentSpecApplyConfiguration.

Class DeploymentSpecApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] DeploymentSpecApplyConfiguration_type_repr  :: go.TypeReprUnderlying DeploymentSpecApplyConfigurationⁱᵐᵖˡ DeploymentSpecApplyConfiguration.t;
  #[global] DeploymentSpecApplyConfiguration_underlying :: (DeploymentSpecApplyConfiguration) <u (DeploymentSpecApplyConfigurationⁱᵐᵖˡ);
  #[global] DeploymentSpecApplyConfigurationⁱᵐᵖˡ_underlying :: (DeploymentSpecApplyConfigurationⁱᵐᵖˡ) ↓u (DeploymentSpecApplyConfigurationⁱᵐᵖˡ);
}.

Module DeploymentStatusApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End DeploymentStatusApplyConfiguration.

Class DeploymentStatusApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] DeploymentStatusApplyConfiguration_type_repr  :: go.TypeReprUnderlying DeploymentStatusApplyConfigurationⁱᵐᵖˡ DeploymentStatusApplyConfiguration.t;
  #[global] DeploymentStatusApplyConfiguration_underlying :: (DeploymentStatusApplyConfiguration) <u (DeploymentStatusApplyConfigurationⁱᵐᵖˡ);
  #[global] DeploymentStatusApplyConfigurationⁱᵐᵖˡ_underlying :: (DeploymentStatusApplyConfigurationⁱᵐᵖˡ) ↓u (DeploymentStatusApplyConfigurationⁱᵐᵖˡ);
}.

Module DeploymentStrategyApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End DeploymentStrategyApplyConfiguration.

Class DeploymentStrategyApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] DeploymentStrategyApplyConfiguration_type_repr  :: go.TypeReprUnderlying DeploymentStrategyApplyConfigurationⁱᵐᵖˡ DeploymentStrategyApplyConfiguration.t;
  #[global] DeploymentStrategyApplyConfiguration_underlying :: (DeploymentStrategyApplyConfiguration) <u (DeploymentStrategyApplyConfigurationⁱᵐᵖˡ);
  #[global] DeploymentStrategyApplyConfigurationⁱᵐᵖˡ_underlying :: (DeploymentStrategyApplyConfigurationⁱᵐᵖˡ) ↓u (DeploymentStrategyApplyConfigurationⁱᵐᵖˡ);
}.

Module ReplicaSetApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End ReplicaSetApplyConfiguration.

Class ReplicaSetApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] ReplicaSetApplyConfiguration_type_repr  :: go.TypeReprUnderlying ReplicaSetApplyConfigurationⁱᵐᵖˡ ReplicaSetApplyConfiguration.t;
  #[global] ReplicaSetApplyConfiguration_underlying :: (ReplicaSetApplyConfiguration) <u (ReplicaSetApplyConfigurationⁱᵐᵖˡ);
  #[global] ReplicaSetApplyConfigurationⁱᵐᵖˡ_underlying :: (ReplicaSetApplyConfigurationⁱᵐᵖˡ) ↓u (ReplicaSetApplyConfigurationⁱᵐᵖˡ);
}.

Module ReplicaSetConditionApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End ReplicaSetConditionApplyConfiguration.

Class ReplicaSetConditionApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] ReplicaSetConditionApplyConfiguration_type_repr  :: go.TypeReprUnderlying ReplicaSetConditionApplyConfigurationⁱᵐᵖˡ ReplicaSetConditionApplyConfiguration.t;
  #[global] ReplicaSetConditionApplyConfiguration_underlying :: (ReplicaSetConditionApplyConfiguration) <u (ReplicaSetConditionApplyConfigurationⁱᵐᵖˡ);
  #[global] ReplicaSetConditionApplyConfigurationⁱᵐᵖˡ_underlying :: (ReplicaSetConditionApplyConfigurationⁱᵐᵖˡ) ↓u (ReplicaSetConditionApplyConfigurationⁱᵐᵖˡ);
}.

Module ReplicaSetSpecApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End ReplicaSetSpecApplyConfiguration.

Class ReplicaSetSpecApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] ReplicaSetSpecApplyConfiguration_type_repr  :: go.TypeReprUnderlying ReplicaSetSpecApplyConfigurationⁱᵐᵖˡ ReplicaSetSpecApplyConfiguration.t;
  #[global] ReplicaSetSpecApplyConfiguration_underlying :: (ReplicaSetSpecApplyConfiguration) <u (ReplicaSetSpecApplyConfigurationⁱᵐᵖˡ);
  #[global] ReplicaSetSpecApplyConfigurationⁱᵐᵖˡ_underlying :: (ReplicaSetSpecApplyConfigurationⁱᵐᵖˡ) ↓u (ReplicaSetSpecApplyConfigurationⁱᵐᵖˡ);
}.

Module ReplicaSetStatusApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End ReplicaSetStatusApplyConfiguration.

Class ReplicaSetStatusApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] ReplicaSetStatusApplyConfiguration_type_repr  :: go.TypeReprUnderlying ReplicaSetStatusApplyConfigurationⁱᵐᵖˡ ReplicaSetStatusApplyConfiguration.t;
  #[global] ReplicaSetStatusApplyConfiguration_underlying :: (ReplicaSetStatusApplyConfiguration) <u (ReplicaSetStatusApplyConfigurationⁱᵐᵖˡ);
  #[global] ReplicaSetStatusApplyConfigurationⁱᵐᵖˡ_underlying :: (ReplicaSetStatusApplyConfigurationⁱᵐᵖˡ) ↓u (ReplicaSetStatusApplyConfigurationⁱᵐᵖˡ);
}.

Module RollingUpdateDaemonSetApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End RollingUpdateDaemonSetApplyConfiguration.

Class RollingUpdateDaemonSetApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] RollingUpdateDaemonSetApplyConfiguration_type_repr  :: go.TypeReprUnderlying RollingUpdateDaemonSetApplyConfigurationⁱᵐᵖˡ RollingUpdateDaemonSetApplyConfiguration.t;
  #[global] RollingUpdateDaemonSetApplyConfiguration_underlying :: (RollingUpdateDaemonSetApplyConfiguration) <u (RollingUpdateDaemonSetApplyConfigurationⁱᵐᵖˡ);
  #[global] RollingUpdateDaemonSetApplyConfigurationⁱᵐᵖˡ_underlying :: (RollingUpdateDaemonSetApplyConfigurationⁱᵐᵖˡ) ↓u (RollingUpdateDaemonSetApplyConfigurationⁱᵐᵖˡ);
}.

Module RollingUpdateDeploymentApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End RollingUpdateDeploymentApplyConfiguration.

Class RollingUpdateDeploymentApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] RollingUpdateDeploymentApplyConfiguration_type_repr  :: go.TypeReprUnderlying RollingUpdateDeploymentApplyConfigurationⁱᵐᵖˡ RollingUpdateDeploymentApplyConfiguration.t;
  #[global] RollingUpdateDeploymentApplyConfiguration_underlying :: (RollingUpdateDeploymentApplyConfiguration) <u (RollingUpdateDeploymentApplyConfigurationⁱᵐᵖˡ);
  #[global] RollingUpdateDeploymentApplyConfigurationⁱᵐᵖˡ_underlying :: (RollingUpdateDeploymentApplyConfigurationⁱᵐᵖˡ) ↓u (RollingUpdateDeploymentApplyConfigurationⁱᵐᵖˡ);
}.

Module RollingUpdateStatefulSetStrategyApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End RollingUpdateStatefulSetStrategyApplyConfiguration.

Class RollingUpdateStatefulSetStrategyApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] RollingUpdateStatefulSetStrategyApplyConfiguration_type_repr  :: go.TypeReprUnderlying RollingUpdateStatefulSetStrategyApplyConfigurationⁱᵐᵖˡ RollingUpdateStatefulSetStrategyApplyConfiguration.t;
  #[global] RollingUpdateStatefulSetStrategyApplyConfiguration_underlying :: (RollingUpdateStatefulSetStrategyApplyConfiguration) <u (RollingUpdateStatefulSetStrategyApplyConfigurationⁱᵐᵖˡ);
  #[global] RollingUpdateStatefulSetStrategyApplyConfigurationⁱᵐᵖˡ_underlying :: (RollingUpdateStatefulSetStrategyApplyConfigurationⁱᵐᵖˡ) ↓u (RollingUpdateStatefulSetStrategyApplyConfigurationⁱᵐᵖˡ);
}.

Module StatefulSetApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End StatefulSetApplyConfiguration.

Class StatefulSetApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] StatefulSetApplyConfiguration_type_repr  :: go.TypeReprUnderlying StatefulSetApplyConfigurationⁱᵐᵖˡ StatefulSetApplyConfiguration.t;
  #[global] StatefulSetApplyConfiguration_underlying :: (StatefulSetApplyConfiguration) <u (StatefulSetApplyConfigurationⁱᵐᵖˡ);
  #[global] StatefulSetApplyConfigurationⁱᵐᵖˡ_underlying :: (StatefulSetApplyConfigurationⁱᵐᵖˡ) ↓u (StatefulSetApplyConfigurationⁱᵐᵖˡ);
}.

Module StatefulSetConditionApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End StatefulSetConditionApplyConfiguration.

Class StatefulSetConditionApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] StatefulSetConditionApplyConfiguration_type_repr  :: go.TypeReprUnderlying StatefulSetConditionApplyConfigurationⁱᵐᵖˡ StatefulSetConditionApplyConfiguration.t;
  #[global] StatefulSetConditionApplyConfiguration_underlying :: (StatefulSetConditionApplyConfiguration) <u (StatefulSetConditionApplyConfigurationⁱᵐᵖˡ);
  #[global] StatefulSetConditionApplyConfigurationⁱᵐᵖˡ_underlying :: (StatefulSetConditionApplyConfigurationⁱᵐᵖˡ) ↓u (StatefulSetConditionApplyConfigurationⁱᵐᵖˡ);
}.

Module StatefulSetOrdinalsApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End StatefulSetOrdinalsApplyConfiguration.

Class StatefulSetOrdinalsApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] StatefulSetOrdinalsApplyConfiguration_type_repr  :: go.TypeReprUnderlying StatefulSetOrdinalsApplyConfigurationⁱᵐᵖˡ StatefulSetOrdinalsApplyConfiguration.t;
  #[global] StatefulSetOrdinalsApplyConfiguration_underlying :: (StatefulSetOrdinalsApplyConfiguration) <u (StatefulSetOrdinalsApplyConfigurationⁱᵐᵖˡ);
  #[global] StatefulSetOrdinalsApplyConfigurationⁱᵐᵖˡ_underlying :: (StatefulSetOrdinalsApplyConfigurationⁱᵐᵖˡ) ↓u (StatefulSetOrdinalsApplyConfigurationⁱᵐᵖˡ);
}.

Module StatefulSetPersistentVolumeClaimRetentionPolicyApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End StatefulSetPersistentVolumeClaimRetentionPolicyApplyConfiguration.

Class StatefulSetPersistentVolumeClaimRetentionPolicyApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] StatefulSetPersistentVolumeClaimRetentionPolicyApplyConfiguration_type_repr  :: go.TypeReprUnderlying StatefulSetPersistentVolumeClaimRetentionPolicyApplyConfigurationⁱᵐᵖˡ StatefulSetPersistentVolumeClaimRetentionPolicyApplyConfiguration.t;
  #[global] StatefulSetPersistentVolumeClaimRetentionPolicyApplyConfiguration_underlying :: (StatefulSetPersistentVolumeClaimRetentionPolicyApplyConfiguration) <u (StatefulSetPersistentVolumeClaimRetentionPolicyApplyConfigurationⁱᵐᵖˡ);
  #[global] StatefulSetPersistentVolumeClaimRetentionPolicyApplyConfigurationⁱᵐᵖˡ_underlying :: (StatefulSetPersistentVolumeClaimRetentionPolicyApplyConfigurationⁱᵐᵖˡ) ↓u (StatefulSetPersistentVolumeClaimRetentionPolicyApplyConfigurationⁱᵐᵖˡ);
}.

Module StatefulSetSpecApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End StatefulSetSpecApplyConfiguration.

Class StatefulSetSpecApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] StatefulSetSpecApplyConfiguration_type_repr  :: go.TypeReprUnderlying StatefulSetSpecApplyConfigurationⁱᵐᵖˡ StatefulSetSpecApplyConfiguration.t;
  #[global] StatefulSetSpecApplyConfiguration_underlying :: (StatefulSetSpecApplyConfiguration) <u (StatefulSetSpecApplyConfigurationⁱᵐᵖˡ);
  #[global] StatefulSetSpecApplyConfigurationⁱᵐᵖˡ_underlying :: (StatefulSetSpecApplyConfigurationⁱᵐᵖˡ) ↓u (StatefulSetSpecApplyConfigurationⁱᵐᵖˡ);
}.

Module StatefulSetStatusApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End StatefulSetStatusApplyConfiguration.

Class StatefulSetStatusApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] StatefulSetStatusApplyConfiguration_type_repr  :: go.TypeReprUnderlying StatefulSetStatusApplyConfigurationⁱᵐᵖˡ StatefulSetStatusApplyConfiguration.t;
  #[global] StatefulSetStatusApplyConfiguration_underlying :: (StatefulSetStatusApplyConfiguration) <u (StatefulSetStatusApplyConfigurationⁱᵐᵖˡ);
  #[global] StatefulSetStatusApplyConfigurationⁱᵐᵖˡ_underlying :: (StatefulSetStatusApplyConfigurationⁱᵐᵖˡ) ↓u (StatefulSetStatusApplyConfigurationⁱᵐᵖˡ);
}.

Module StatefulSetUpdateStrategyApplyConfiguration.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End StatefulSetUpdateStrategyApplyConfiguration.

Class StatefulSetUpdateStrategyApplyConfiguration_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] StatefulSetUpdateStrategyApplyConfiguration_type_repr  :: go.TypeReprUnderlying StatefulSetUpdateStrategyApplyConfigurationⁱᵐᵖˡ StatefulSetUpdateStrategyApplyConfiguration.t;
  #[global] StatefulSetUpdateStrategyApplyConfiguration_underlying :: (StatefulSetUpdateStrategyApplyConfiguration) <u (StatefulSetUpdateStrategyApplyConfigurationⁱᵐᵖˡ);
  #[global] StatefulSetUpdateStrategyApplyConfigurationⁱᵐᵖˡ_underlying :: (StatefulSetUpdateStrategyApplyConfigurationⁱᵐᵖˡ) ↓u (StatefulSetUpdateStrategyApplyConfigurationⁱᵐᵖˡ);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] ControllerRevisionApplyConfiguration_instance :: ControllerRevisionApplyConfiguration_Assumptions;
  #[global] DaemonSetApplyConfiguration_instance :: DaemonSetApplyConfiguration_Assumptions;
  #[global] DaemonSetConditionApplyConfiguration_instance :: DaemonSetConditionApplyConfiguration_Assumptions;
  #[global] DaemonSetSpecApplyConfiguration_instance :: DaemonSetSpecApplyConfiguration_Assumptions;
  #[global] DaemonSetStatusApplyConfiguration_instance :: DaemonSetStatusApplyConfiguration_Assumptions;
  #[global] DaemonSetUpdateStrategyApplyConfiguration_instance :: DaemonSetUpdateStrategyApplyConfiguration_Assumptions;
  #[global] DeploymentApplyConfiguration_instance :: DeploymentApplyConfiguration_Assumptions;
  #[global] DeploymentConditionApplyConfiguration_instance :: DeploymentConditionApplyConfiguration_Assumptions;
  #[global] DeploymentSpecApplyConfiguration_instance :: DeploymentSpecApplyConfiguration_Assumptions;
  #[global] DeploymentStatusApplyConfiguration_instance :: DeploymentStatusApplyConfiguration_Assumptions;
  #[global] DeploymentStrategyApplyConfiguration_instance :: DeploymentStrategyApplyConfiguration_Assumptions;
  #[global] ReplicaSetApplyConfiguration_instance :: ReplicaSetApplyConfiguration_Assumptions;
  #[global] ReplicaSetConditionApplyConfiguration_instance :: ReplicaSetConditionApplyConfiguration_Assumptions;
  #[global] ReplicaSetSpecApplyConfiguration_instance :: ReplicaSetSpecApplyConfiguration_Assumptions;
  #[global] ReplicaSetStatusApplyConfiguration_instance :: ReplicaSetStatusApplyConfiguration_Assumptions;
  #[global] RollingUpdateDaemonSetApplyConfiguration_instance :: RollingUpdateDaemonSetApplyConfiguration_Assumptions;
  #[global] RollingUpdateDeploymentApplyConfiguration_instance :: RollingUpdateDeploymentApplyConfiguration_Assumptions;
  #[global] RollingUpdateStatefulSetStrategyApplyConfiguration_instance :: RollingUpdateStatefulSetStrategyApplyConfiguration_Assumptions;
  #[global] StatefulSetApplyConfiguration_instance :: StatefulSetApplyConfiguration_Assumptions;
  #[global] StatefulSetConditionApplyConfiguration_instance :: StatefulSetConditionApplyConfiguration_Assumptions;
  #[global] StatefulSetOrdinalsApplyConfiguration_instance :: StatefulSetOrdinalsApplyConfiguration_Assumptions;
  #[global] StatefulSetPersistentVolumeClaimRetentionPolicyApplyConfiguration_instance :: StatefulSetPersistentVolumeClaimRetentionPolicyApplyConfiguration_Assumptions;
  #[global] StatefulSetSpecApplyConfiguration_instance :: StatefulSetSpecApplyConfiguration_Assumptions;
  #[global] StatefulSetStatusApplyConfiguration_instance :: StatefulSetStatusApplyConfiguration_Assumptions;
  #[global] StatefulSetUpdateStrategyApplyConfiguration_instance :: StatefulSetUpdateStrategyApplyConfiguration_Assumptions;
}.
End v1.
