(* autogenerated from k8s.io/apiserver/pkg/registry/generic/registry *)
From New.golang Require Import defn.
Module pkg_id.
Definition registry : go_string := "k8s.io/apiserver/pkg/registry/generic/registry".

End pkg_id.
Export pkg_id.
Module registry.

Definition corruptObjectDeleter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apiserver/pkg/registry/generic/registry.corruptObjectDeleter"%go [].

#[global] Opaque corruptObjectDeleter.

Definition decoratedWatcher {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apiserver/pkg/registry/generic/registry.decoratedWatcher"%go [].

#[global] Opaque decoratedWatcher.

Definition DryRunnableStorage {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apiserver/pkg/registry/generic/registry.DryRunnableStorage"%go [].

#[global] Opaque DryRunnableStorage.

Definition FinishFunc {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apiserver/pkg/registry/generic/registry.FinishFunc"%go [].

#[global] Opaque FinishFunc.

Definition AfterDeleteFunc {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apiserver/pkg/registry/generic/registry.AfterDeleteFunc"%go [].

#[global] Opaque AfterDeleteFunc.

Definition BeginCreateFunc {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apiserver/pkg/registry/generic/registry.BeginCreateFunc"%go [].

#[global] Opaque BeginCreateFunc.

Definition AfterCreateFunc {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apiserver/pkg/registry/generic/registry.AfterCreateFunc"%go [].

#[global] Opaque AfterCreateFunc.

Definition BeginUpdateFunc {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apiserver/pkg/registry/generic/registry.BeginUpdateFunc"%go [].

#[global] Opaque BeginUpdateFunc.

Definition AfterUpdateFunc {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apiserver/pkg/registry/generic/registry.AfterUpdateFunc"%go [].

#[global] Opaque AfterUpdateFunc.

Definition GenericStore {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apiserver/pkg/registry/generic/registry.GenericStore"%go [].

#[global] Opaque GenericStore.

Definition Store {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apiserver/pkg/registry/generic/registry.Store"%go [].

#[global] Opaque Store.

Axiom corruptObjectDeleterⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom decoratedWatcherⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom DryRunnableStorageⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom FinishFuncⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom AfterDeleteFuncⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom BeginCreateFuncⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom AfterCreateFuncⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom BeginUpdateFuncⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom AfterUpdateFuncⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom GenericStoreⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Storeⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom OptimisticLockErrorMsg : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom resourceCountPollPeriodJitter : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom maxNameGenerationCreateAttempts : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition errAlreadyDeleting {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.errAlreadyDeleting"%go.

Axiom errAlreadyDeleting'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition errDeleteNow {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.errDeleteNow"%go.

Axiom errDeleteNow'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition errEmptiedFinalizers {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.errEmptiedFinalizers"%go.

Axiom errEmptiedFinalizers'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition deleteCollectionPageSize {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.deleteCollectionPageSize"%go.

Axiom deleteCollectionPageSize'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition NewCorruptObjectDeleter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.NewCorruptObjectDeleter"%go.

Definition newDecoratedWatcher {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.newDecoratedWatcher"%go.

Definition StorageWithCacher {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.StorageWithCacher"%go.

Definition objectTypeToArgs {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.objectTypeToArgs"%go.

Definition NamespaceKeyRootFunc {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.NamespaceKeyRootFunc"%go.

Definition NamespaceKeyFunc {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.NamespaceKeyFunc"%go.

Definition NoNamespaceKeyFunc {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.NoNamespaceKeyFunc"%go.

Definition finishNothing {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.finishNothing"%go.

Definition needsNameGeneration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.needsNameGeneration"%go.

Definition ShouldDeleteDuringUpdate {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.ShouldDeleteDuringUpdate"%go.

Definition newCreateOptionsFromUpdateOptions {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.newCreateOptionsFromUpdateOptions"%go.

Definition newDeleteOptionsFromUpdateOptions {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.newDeleteOptionsFromUpdateOptions"%go.

Definition shouldOrphanDependents {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.shouldOrphanDependents"%go.

Definition shouldDeleteDependents {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.shouldDeleteDependents"%go.

Definition deletionFinalizersForGarbageCollection {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.deletionFinalizersForGarbageCollection"%go.

Definition markAsDeleting {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.markAsDeleting"%go.

Definition validateIndexers {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/apiserver/pkg/registry/generic/registry.validateIndexers"%go.

#[global] Instance info' : PkgInfo pkg_id.registry :=
{|
  pkg_imported_pkgs := []
|}.

Axiom _'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.registry (λ: <>,
      exception_do (do:  (_'init #());;;
      do:  (_'init #());;;
      do:  (_'init #());;;
      do:  (_'init #());;;
      do:  (_'init #());;;
      do:  (_'init #());;;
      do:  (_'init #());;;
      do:  (errAlreadyDeleting'init #());;;
      do:  (errDeleteNow'init #());;;
      do:  (errEmptiedFinalizers'init #());;;
      do:  (deleteCollectionPageSize'init #()))
      ).

Module corruptObjectDeleter.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End corruptObjectDeleter.

Class corruptObjectDeleter_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] corruptObjectDeleter_type_repr  :: go.TypeReprUnderlying corruptObjectDeleterⁱᵐᵖˡ corruptObjectDeleter.t;
  #[global] corruptObjectDeleter_underlying :: (corruptObjectDeleter) <u (corruptObjectDeleterⁱᵐᵖˡ);
  #[global] corruptObjectDeleterⁱᵐᵖˡ_underlying :: (corruptObjectDeleterⁱᵐᵖˡ) ↓u (corruptObjectDeleterⁱᵐᵖˡ);
}.

Module decoratedWatcher.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End decoratedWatcher.

Class decoratedWatcher_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] decoratedWatcher_type_repr  :: go.TypeReprUnderlying decoratedWatcherⁱᵐᵖˡ decoratedWatcher.t;
  #[global] decoratedWatcher_underlying :: (decoratedWatcher) <u (decoratedWatcherⁱᵐᵖˡ);
  #[global] decoratedWatcherⁱᵐᵖˡ_underlying :: (decoratedWatcherⁱᵐᵖˡ) ↓u (decoratedWatcherⁱᵐᵖˡ);
}.

Module DryRunnableStorage.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End DryRunnableStorage.

Class DryRunnableStorage_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] DryRunnableStorage_type_repr  :: go.TypeReprUnderlying DryRunnableStorageⁱᵐᵖˡ DryRunnableStorage.t;
  #[global] DryRunnableStorage_underlying :: (DryRunnableStorage) <u (DryRunnableStorageⁱᵐᵖˡ);
  #[global] DryRunnableStorageⁱᵐᵖˡ_underlying :: (DryRunnableStorageⁱᵐᵖˡ) ↓u (DryRunnableStorageⁱᵐᵖˡ);
}.

Module FinishFunc.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End FinishFunc.

Class FinishFunc_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] FinishFunc_type_repr  :: go.TypeReprUnderlying FinishFuncⁱᵐᵖˡ FinishFunc.t;
  #[global] FinishFunc_underlying :: (FinishFunc) <u (FinishFuncⁱᵐᵖˡ);
  #[global] FinishFuncⁱᵐᵖˡ_underlying :: (FinishFuncⁱᵐᵖˡ) ↓u (FinishFuncⁱᵐᵖˡ);
}.

Module AfterDeleteFunc.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End AfterDeleteFunc.

Class AfterDeleteFunc_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] AfterDeleteFunc_type_repr  :: go.TypeReprUnderlying AfterDeleteFuncⁱᵐᵖˡ AfterDeleteFunc.t;
  #[global] AfterDeleteFunc_underlying :: (AfterDeleteFunc) <u (AfterDeleteFuncⁱᵐᵖˡ);
  #[global] AfterDeleteFuncⁱᵐᵖˡ_underlying :: (AfterDeleteFuncⁱᵐᵖˡ) ↓u (AfterDeleteFuncⁱᵐᵖˡ);
}.

Module BeginCreateFunc.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End BeginCreateFunc.

Class BeginCreateFunc_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] BeginCreateFunc_type_repr  :: go.TypeReprUnderlying BeginCreateFuncⁱᵐᵖˡ BeginCreateFunc.t;
  #[global] BeginCreateFunc_underlying :: (BeginCreateFunc) <u (BeginCreateFuncⁱᵐᵖˡ);
  #[global] BeginCreateFuncⁱᵐᵖˡ_underlying :: (BeginCreateFuncⁱᵐᵖˡ) ↓u (BeginCreateFuncⁱᵐᵖˡ);
}.

Module AfterCreateFunc.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End AfterCreateFunc.

Class AfterCreateFunc_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] AfterCreateFunc_type_repr  :: go.TypeReprUnderlying AfterCreateFuncⁱᵐᵖˡ AfterCreateFunc.t;
  #[global] AfterCreateFunc_underlying :: (AfterCreateFunc) <u (AfterCreateFuncⁱᵐᵖˡ);
  #[global] AfterCreateFuncⁱᵐᵖˡ_underlying :: (AfterCreateFuncⁱᵐᵖˡ) ↓u (AfterCreateFuncⁱᵐᵖˡ);
}.

Module BeginUpdateFunc.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End BeginUpdateFunc.

Class BeginUpdateFunc_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] BeginUpdateFunc_type_repr  :: go.TypeReprUnderlying BeginUpdateFuncⁱᵐᵖˡ BeginUpdateFunc.t;
  #[global] BeginUpdateFunc_underlying :: (BeginUpdateFunc) <u (BeginUpdateFuncⁱᵐᵖˡ);
  #[global] BeginUpdateFuncⁱᵐᵖˡ_underlying :: (BeginUpdateFuncⁱᵐᵖˡ) ↓u (BeginUpdateFuncⁱᵐᵖˡ);
}.

Module AfterUpdateFunc.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End AfterUpdateFunc.

Class AfterUpdateFunc_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] AfterUpdateFunc_type_repr  :: go.TypeReprUnderlying AfterUpdateFuncⁱᵐᵖˡ AfterUpdateFunc.t;
  #[global] AfterUpdateFunc_underlying :: (AfterUpdateFunc) <u (AfterUpdateFuncⁱᵐᵖˡ);
  #[global] AfterUpdateFuncⁱᵐᵖˡ_underlying :: (AfterUpdateFuncⁱᵐᵖˡ) ↓u (AfterUpdateFuncⁱᵐᵖˡ);
}.

Module GenericStore.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End GenericStore.

Class GenericStore_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] GenericStore_type_repr  :: go.TypeReprUnderlying GenericStoreⁱᵐᵖˡ GenericStore.t;
  #[global] GenericStore_underlying :: (GenericStore) <u (GenericStoreⁱᵐᵖˡ);
  #[global] GenericStoreⁱᵐᵖˡ_underlying :: (GenericStoreⁱᵐᵖˡ) ↓u (GenericStoreⁱᵐᵖˡ);
}.

Module Store.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Store.

Class Store_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Store_type_repr  :: go.TypeReprUnderlying Storeⁱᵐᵖˡ Store.t;
  #[global] Store_underlying :: (Store) <u (Storeⁱᵐᵖˡ);
  #[global] Storeⁱᵐᵖˡ_underlying :: (Storeⁱᵐᵖˡ) ↓u (Storeⁱᵐᵖˡ);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] corruptObjectDeleter_instance :: corruptObjectDeleter_Assumptions;
  #[global] decoratedWatcher_instance :: decoratedWatcher_Assumptions;
  #[global] DryRunnableStorage_instance :: DryRunnableStorage_Assumptions;
  #[global] FinishFunc_instance :: FinishFunc_Assumptions;
  #[global] AfterDeleteFunc_instance :: AfterDeleteFunc_Assumptions;
  #[global] BeginCreateFunc_instance :: BeginCreateFunc_Assumptions;
  #[global] AfterCreateFunc_instance :: AfterCreateFunc_Assumptions;
  #[global] BeginUpdateFunc_instance :: BeginUpdateFunc_Assumptions;
  #[global] AfterUpdateFunc_instance :: AfterUpdateFunc_Assumptions;
  #[global] GenericStore_instance :: GenericStore_Assumptions;
  #[global] Store_instance :: Store_Assumptions;
}.
End registry.
