(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.context.
Require Export New.generatedproof.fmt.
Require Export New.generatedproof.sort.
Require Export New.generatedproof.sync.
Require Export New.generatedproof.k8s_io.api.apps.v1.
Require Export New.generatedproof.k8s_io.api.core.v1.
Require Export New.generatedproof.k8s_io.apimachinery.pkg.api.errors.
Require Export New.generatedproof.k8s_io.apimachinery.pkg.apis.meta.v1.
Require Export New.generatedproof.k8s_io.apimachinery.pkg.labels.
Require Export New.generatedproof.k8s_io.apimachinery.pkg.runtime.schema.
Require Export New.generatedproof.k8s_io.apimachinery.pkg.types.
Require Export New.generatedproof.k8s_io.apimachinery.pkg.util.runtime.
Require Export New.generatedproof.k8s_io.client_go.listers.apps.v1.
Require Export New.generatedproof.k8s_io.client_go.listers.core.v1.
Require Export New.generatedproof.k8s_io.client_go.tools.cache.
Require Export New.generatedproof.k8s_io.klog.v2.
Require Export New.generatedproof.k8s_io.kubernetes.pkg.controller.
Require Export New.golang.theory.

Require Export New.code.kubernetes_model.simplereplicaset.

Set Default Proof Using "Type".

Module simplereplicaset.

(* type simplereplicaset.ReplicaSetController *)
Module ReplicaSetController.
Section def.
Context `{ffi_syntax}.
Record t := mk {
  GroupVersionKind' : schema.GroupVersionKind.t;
  podControl' : controller.PodControlInterface.t;
  podIndexer' : cache.Indexer.t;
  burstReplicas' : w64;
  syncHandler' : func.t;
  expectations' : loc;
  rsLister' : v1.ReplicaSetLister.t;
  rsIndexer' : cache.Indexer.t;
  podLister' : v1.PodLister.t;
}.
End def.
End ReplicaSetController.

Section instances.
Context `{ffi_syntax}.
#[local] Transparent simplereplicaset.ReplicaSetController.
#[local] Typeclasses Transparent simplereplicaset.ReplicaSetController.

Global Instance ReplicaSetController_wf : struct.Wf simplereplicaset.ReplicaSetController.
Proof. apply _. Qed.

Global Instance settable_ReplicaSetController : Settable ReplicaSetController.t :=
  settable! ReplicaSetController.mk < ReplicaSetController.GroupVersionKind'; ReplicaSetController.podControl'; ReplicaSetController.podIndexer'; ReplicaSetController.burstReplicas'; ReplicaSetController.syncHandler'; ReplicaSetController.expectations'; ReplicaSetController.rsLister'; ReplicaSetController.rsIndexer'; ReplicaSetController.podLister' >.
Global Instance into_val_ReplicaSetController : IntoVal ReplicaSetController.t :=
  {| to_val_def v :=
    struct.val_aux simplereplicaset.ReplicaSetController [
    "GroupVersionKind" ::= #(ReplicaSetController.GroupVersionKind' v);
    "podControl" ::= #(ReplicaSetController.podControl' v);
    "podIndexer" ::= #(ReplicaSetController.podIndexer' v);
    "burstReplicas" ::= #(ReplicaSetController.burstReplicas' v);
    "syncHandler" ::= #(ReplicaSetController.syncHandler' v);
    "expectations" ::= #(ReplicaSetController.expectations' v);
    "rsLister" ::= #(ReplicaSetController.rsLister' v);
    "rsIndexer" ::= #(ReplicaSetController.rsIndexer' v);
    "podLister" ::= #(ReplicaSetController.podLister' v)
    ]%struct
  |}.

Global Program Instance into_val_typed_ReplicaSetController : IntoValTyped ReplicaSetController.t simplereplicaset.ReplicaSetController :=
{|
  default_val := ReplicaSetController.mk (default_val _) (default_val _) (default_val _) (default_val _) (default_val _) (default_val _) (default_val _) (default_val _) (default_val _);
|}.
Next Obligation. solve_to_val_type. Qed.
Next Obligation. solve_zero_val. Qed.
Next Obligation. solve_to_val_inj. Qed.
Final Obligation. solve_decision. Qed.

Global Instance into_val_struct_field_ReplicaSetController_GroupVersionKind : IntoValStructField "GroupVersionKind" simplereplicaset.ReplicaSetController ReplicaSetController.GroupVersionKind'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_ReplicaSetController_podControl : IntoValStructField "podControl" simplereplicaset.ReplicaSetController ReplicaSetController.podControl'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_ReplicaSetController_podIndexer : IntoValStructField "podIndexer" simplereplicaset.ReplicaSetController ReplicaSetController.podIndexer'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_ReplicaSetController_burstReplicas : IntoValStructField "burstReplicas" simplereplicaset.ReplicaSetController ReplicaSetController.burstReplicas'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_ReplicaSetController_syncHandler : IntoValStructField "syncHandler" simplereplicaset.ReplicaSetController ReplicaSetController.syncHandler'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_ReplicaSetController_expectations : IntoValStructField "expectations" simplereplicaset.ReplicaSetController ReplicaSetController.expectations'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_ReplicaSetController_rsLister : IntoValStructField "rsLister" simplereplicaset.ReplicaSetController ReplicaSetController.rsLister'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_ReplicaSetController_rsIndexer : IntoValStructField "rsIndexer" simplereplicaset.ReplicaSetController ReplicaSetController.rsIndexer'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_ReplicaSetController_podLister : IntoValStructField "podLister" simplereplicaset.ReplicaSetController ReplicaSetController.podLister'.
Proof. solve_into_val_struct_field. Qed.


Context `{!ffi_model, !ffi_semantics _ _, !ffi_interp _, !heapGS Σ}.
Global Instance wp_struct_make_ReplicaSetController GroupVersionKind' podControl' podIndexer' burstReplicas' syncHandler' expectations' rsLister' rsIndexer' podLister':
  PureWp True
    (struct.make #simplereplicaset.ReplicaSetController (alist_val [
      "GroupVersionKind" ::= #GroupVersionKind';
      "podControl" ::= #podControl';
      "podIndexer" ::= #podIndexer';
      "burstReplicas" ::= #burstReplicas';
      "syncHandler" ::= #syncHandler';
      "expectations" ::= #expectations';
      "rsLister" ::= #rsLister';
      "rsIndexer" ::= #rsIndexer';
      "podLister" ::= #podLister'
    ]))%struct
    #(ReplicaSetController.mk GroupVersionKind' podControl' podIndexer' burstReplicas' syncHandler' expectations' rsLister' rsIndexer' podLister').
Proof. solve_struct_make_pure_wp. Qed.


Global Instance ReplicaSetController_struct_fields_split dq l (v : ReplicaSetController.t) :
  StructFieldsSplit dq l v (
    "HGroupVersionKind" ∷ l ↦s[simplereplicaset.ReplicaSetController :: "GroupVersionKind"]{dq} v.(ReplicaSetController.GroupVersionKind') ∗
    "HpodControl" ∷ l ↦s[simplereplicaset.ReplicaSetController :: "podControl"]{dq} v.(ReplicaSetController.podControl') ∗
    "HpodIndexer" ∷ l ↦s[simplereplicaset.ReplicaSetController :: "podIndexer"]{dq} v.(ReplicaSetController.podIndexer') ∗
    "HburstReplicas" ∷ l ↦s[simplereplicaset.ReplicaSetController :: "burstReplicas"]{dq} v.(ReplicaSetController.burstReplicas') ∗
    "HsyncHandler" ∷ l ↦s[simplereplicaset.ReplicaSetController :: "syncHandler"]{dq} v.(ReplicaSetController.syncHandler') ∗
    "Hexpectations" ∷ l ↦s[simplereplicaset.ReplicaSetController :: "expectations"]{dq} v.(ReplicaSetController.expectations') ∗
    "HrsLister" ∷ l ↦s[simplereplicaset.ReplicaSetController :: "rsLister"]{dq} v.(ReplicaSetController.rsLister') ∗
    "HrsIndexer" ∷ l ↦s[simplereplicaset.ReplicaSetController :: "rsIndexer"]{dq} v.(ReplicaSetController.rsIndexer') ∗
    "HpodLister" ∷ l ↦s[simplereplicaset.ReplicaSetController :: "podLister"]{dq} v.(ReplicaSetController.podLister')
  ).
Proof.
  rewrite /named.
  apply struct_fields_split_intro.
  unfold_typed_pointsto; split_pointsto_app.

  rewrite -!/(typed_pointsto_def _ _ _) -!typed_pointsto_unseal.
  simpl_one_flatten_struct (# (ReplicaSetController.GroupVersionKind' v)) (simplereplicaset.ReplicaSetController) "GroupVersionKind"%go.
  simpl_one_flatten_struct (# (ReplicaSetController.podControl' v)) (simplereplicaset.ReplicaSetController) "podControl"%go.
  simpl_one_flatten_struct (# (ReplicaSetController.podIndexer' v)) (simplereplicaset.ReplicaSetController) "podIndexer"%go.
  simpl_one_flatten_struct (# (ReplicaSetController.burstReplicas' v)) (simplereplicaset.ReplicaSetController) "burstReplicas"%go.
  simpl_one_flatten_struct (# (ReplicaSetController.syncHandler' v)) (simplereplicaset.ReplicaSetController) "syncHandler"%go.
  simpl_one_flatten_struct (# (ReplicaSetController.expectations' v)) (simplereplicaset.ReplicaSetController) "expectations"%go.
  simpl_one_flatten_struct (# (ReplicaSetController.rsLister' v)) (simplereplicaset.ReplicaSetController) "rsLister"%go.
  simpl_one_flatten_struct (# (ReplicaSetController.rsIndexer' v)) (simplereplicaset.ReplicaSetController) "rsIndexer"%go.

  solve_field_ref_f.
Qed.

End instances.

Section names.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context `{!globalsGS Σ}.
Context {go_ctx : GoContext}.
#[local] Transparent is_pkg_defined is_pkg_defined_pure.

Global Instance is_pkg_defined_pure_simplereplicaset : IsPkgDefinedPure simplereplicaset :=
  {|
    is_pkg_defined_pure_def go_ctx :=
      is_pkg_defined_pure_single simplereplicaset ∧
      is_pkg_defined_pure code.context.context ∧
      is_pkg_defined_pure code.fmt.fmt ∧
      is_pkg_defined_pure code.sort.sort ∧
      is_pkg_defined_pure code.sync.sync ∧
      is_pkg_defined_pure code.k8s_io.api.apps.v1.v1 ∧
      is_pkg_defined_pure code.k8s_io.api.core.v1.v1 ∧
      is_pkg_defined_pure code.k8s_io.apimachinery.pkg.api.errors.errors ∧
      is_pkg_defined_pure code.k8s_io.apimachinery.pkg.apis.meta.v1.v1 ∧
      is_pkg_defined_pure code.k8s_io.apimachinery.pkg.labels.labels ∧
      is_pkg_defined_pure code.k8s_io.apimachinery.pkg.runtime.schema.schema ∧
      is_pkg_defined_pure code.k8s_io.apimachinery.pkg.types.types ∧
      is_pkg_defined_pure code.k8s_io.apimachinery.pkg.util.runtime.runtime ∧
      is_pkg_defined_pure code.k8s_io.client_go.listers.apps.v1.v1 ∧
      is_pkg_defined_pure code.k8s_io.client_go.listers.core.v1.v1 ∧
      is_pkg_defined_pure code.k8s_io.client_go.tools.cache.cache ∧
      is_pkg_defined_pure code.k8s_io.klog.v2.klog ∧
      is_pkg_defined_pure code.k8s_io.kubernetes.pkg.controller.controller;
  |}.

#[local] Transparent is_pkg_defined_single is_pkg_defined_pure_single.
Global Program Instance is_pkg_defined_simplereplicaset : IsPkgDefined simplereplicaset :=
  {|
    is_pkg_defined_def go_ctx :=
      (is_pkg_defined_single simplereplicaset ∗
       is_pkg_defined code.context.context ∗
       is_pkg_defined code.fmt.fmt ∗
       is_pkg_defined code.sort.sort ∗
       is_pkg_defined code.sync.sync ∗
       is_pkg_defined code.k8s_io.api.apps.v1.v1 ∗
       is_pkg_defined code.k8s_io.api.core.v1.v1 ∗
       is_pkg_defined code.k8s_io.apimachinery.pkg.api.errors.errors ∗
       is_pkg_defined code.k8s_io.apimachinery.pkg.apis.meta.v1.v1 ∗
       is_pkg_defined code.k8s_io.apimachinery.pkg.labels.labels ∗
       is_pkg_defined code.k8s_io.apimachinery.pkg.runtime.schema.schema ∗
       is_pkg_defined code.k8s_io.apimachinery.pkg.types.types ∗
       is_pkg_defined code.k8s_io.apimachinery.pkg.util.runtime.runtime ∗
       is_pkg_defined code.k8s_io.client_go.listers.apps.v1.v1 ∗
       is_pkg_defined code.k8s_io.client_go.listers.core.v1.v1 ∗
       is_pkg_defined code.k8s_io.client_go.tools.cache.cache ∗
       is_pkg_defined code.k8s_io.klog.v2.klog ∗
       is_pkg_defined code.k8s_io.kubernetes.pkg.controller.controller)%I
  |}.
Final Obligation. iIntros. iFrame "#%". Qed.
#[local] Opaque is_pkg_defined_single is_pkg_defined_pure_single.

Global Instance wp_func_call_min :
  WpFuncCall simplereplicaset.min _ (is_pkg_defined simplereplicaset) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_slowStartBatch :
  WpFuncCall simplereplicaset.slowStartBatch _ (is_pkg_defined simplereplicaset) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_getPodsRankedByRelatedPodsOnSameNode :
  WpFuncCall simplereplicaset.getPodsRankedByRelatedPodsOnSameNode _ (is_pkg_defined simplereplicaset) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_getPodsToDelete :
  WpFuncCall simplereplicaset.getPodsToDelete _ (is_pkg_defined simplereplicaset) :=
  ltac:(solve_wp_func_call).

Global Instance wp_method_call_ReplicaSetController_Empty :
  WpMethodCall simplereplicaset.ReplicaSetController.id "Empty" _ (is_pkg_defined simplereplicaset) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_ReplicaSetController_GroupKind :
  WpMethodCall simplereplicaset.ReplicaSetController.id "GroupKind" _ (is_pkg_defined simplereplicaset) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_ReplicaSetController_GroupVersion :
  WpMethodCall simplereplicaset.ReplicaSetController.id "GroupVersion" _ (is_pkg_defined simplereplicaset) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_ReplicaSetController_String :
  WpMethodCall simplereplicaset.ReplicaSetController.id "String" _ (is_pkg_defined simplereplicaset) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_ReplicaSetController_ToAPIVersionAndKind :
  WpMethodCall simplereplicaset.ReplicaSetController.id "ToAPIVersionAndKind" _ (is_pkg_defined simplereplicaset) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_ReplicaSetController'ptr_Empty :
  WpMethodCall (ptrT.id simplereplicaset.ReplicaSetController.id) "Empty" _ (is_pkg_defined simplereplicaset) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_ReplicaSetController'ptr_GroupKind :
  WpMethodCall (ptrT.id simplereplicaset.ReplicaSetController.id) "GroupKind" _ (is_pkg_defined simplereplicaset) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_ReplicaSetController'ptr_GroupVersion :
  WpMethodCall (ptrT.id simplereplicaset.ReplicaSetController.id) "GroupVersion" _ (is_pkg_defined simplereplicaset) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_ReplicaSetController'ptr_String :
  WpMethodCall (ptrT.id simplereplicaset.ReplicaSetController.id) "String" _ (is_pkg_defined simplereplicaset) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_ReplicaSetController'ptr_ToAPIVersionAndKind :
  WpMethodCall (ptrT.id simplereplicaset.ReplicaSetController.id) "ToAPIVersionAndKind" _ (is_pkg_defined simplereplicaset) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_ReplicaSetController'ptr_getIndirectlyRelatedPods :
  WpMethodCall (ptrT.id simplereplicaset.ReplicaSetController.id) "getIndirectlyRelatedPods" _ (is_pkg_defined simplereplicaset) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_ReplicaSetController'ptr_getReplicaSetsWithSameController :
  WpMethodCall (ptrT.id simplereplicaset.ReplicaSetController.id) "getReplicaSetsWithSameController" _ (is_pkg_defined simplereplicaset) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_ReplicaSetController'ptr_manageReplicas :
  WpMethodCall (ptrT.id simplereplicaset.ReplicaSetController.id) "manageReplicas" _ (is_pkg_defined simplereplicaset) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_ReplicaSetController'ptr_syncReplicaSet :
  WpMethodCall (ptrT.id simplereplicaset.ReplicaSetController.id) "syncReplicaSet" _ (is_pkg_defined simplereplicaset) :=
  ltac:(solve_wp_method_call).

End names.
End simplereplicaset.
