(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.golang.theory.
Require Export New.code.github_com.go_logr.logr.

Set Default Proof Using "Type".

Module logr.
Module contextKey.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Local Set Default Proof Using "All".

#[global] Instance contextKey_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (logr.contextKey.t). Admitted.

#[global] Instance contextKey_into_val_typed
   :
  IntoValTypedUnderlying (logr.contextKey.t) (logr.contextKeyⁱᵐᵖˡ).
Proof. Admitted.

End def.
End contextKey.

Module notFoundError.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Local Set Default Proof Using "All".

#[global] Instance notFoundError_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (logr.notFoundError.t). Admitted.

#[global] Instance notFoundError_into_val_typed
   :
  IntoValTypedUnderlying (logr.notFoundError.t) (logr.notFoundErrorⁱᵐᵖˡ).
Proof. Admitted.

End def.
End notFoundError.

Module Logger.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Local Set Default Proof Using "All".

#[global] Instance Logger_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (logr.Logger.t). Admitted.

#[global] Instance Logger_into_val_typed
   :
  IntoValTypedUnderlying (logr.Logger.t) (logr.Loggerⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Logger.

Module RuntimeInfo.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Local Set Default Proof Using "All".

#[global] Instance RuntimeInfo_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (logr.RuntimeInfo.t). Admitted.

#[global] Instance RuntimeInfo_into_val_typed
   :
  IntoValTypedUnderlying (logr.RuntimeInfo.t) (logr.RuntimeInfoⁱᵐᵖˡ).
Proof. Admitted.

End def.
End RuntimeInfo.

Module LogSink.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Local Set Default Proof Using "All".

#[global] Instance LogSink_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (logr.LogSink.t). Admitted.

#[global] Instance LogSink_into_val_typed
   :
  IntoValTypedUnderlying (logr.LogSink.t) (logr.LogSinkⁱᵐᵖˡ).
Proof. Admitted.

End def.
End LogSink.

Module CallDepthLogSink.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Local Set Default Proof Using "All".

#[global] Instance CallDepthLogSink_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (logr.CallDepthLogSink.t). Admitted.

#[global] Instance CallDepthLogSink_into_val_typed
   :
  IntoValTypedUnderlying (logr.CallDepthLogSink.t) (logr.CallDepthLogSinkⁱᵐᵖˡ).
Proof. Admitted.

End def.
End CallDepthLogSink.

Module CallStackHelperLogSink.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Local Set Default Proof Using "All".

#[global] Instance CallStackHelperLogSink_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (logr.CallStackHelperLogSink.t). Admitted.

#[global] Instance CallStackHelperLogSink_into_val_typed
   :
  IntoValTypedUnderlying (logr.CallStackHelperLogSink.t) (logr.CallStackHelperLogSinkⁱᵐᵖˡ).
Proof. Admitted.

End def.
End CallStackHelperLogSink.

Module Marshaler.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Local Set Default Proof Using "All".

#[global] Instance Marshaler_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (logr.Marshaler.t). Admitted.

#[global] Instance Marshaler_into_val_typed
   :
  IntoValTypedUnderlying (logr.Marshaler.t) (logr.Marshalerⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Marshaler.

Module slogHandler.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Local Set Default Proof Using "All".

#[global] Instance slogHandler_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (logr.slogHandler.t). Admitted.

#[global] Instance slogHandler_into_val_typed
   :
  IntoValTypedUnderlying (logr.slogHandler.t) (logr.slogHandlerⁱᵐᵖˡ).
Proof. Admitted.

End def.
End slogHandler.

Module SlogSink.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Local Set Default Proof Using "All".

#[global] Instance SlogSink_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (logr.SlogSink.t). Admitted.

#[global] Instance SlogSink_into_val_typed
   :
  IntoValTypedUnderlying (logr.SlogSink.t) (logr.SlogSinkⁱᵐᵖˡ).
Proof. Admitted.

End def.
End SlogSink.

Module Underlier.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Local Set Default Proof Using "All".

#[global] Instance Underlier_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (logr.Underlier.t). Admitted.

#[global] Instance Underlier_into_val_typed
   :
  IntoValTypedUnderlying (logr.Underlier.t) (logr.Underlierⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Underlier.

Module slogSink.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Local Set Default Proof Using "All".

#[global] Instance slogSink_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (logr.slogSink.t). Admitted.

#[global] Instance slogSink_into_val_typed
   :
  IntoValTypedUnderlying (logr.slogSink.t) (logr.slogSinkⁱᵐᵖˡ).
Proof. Admitted.

End def.
End slogSink.

End logr.
