(* autogenerated from k8s.io/kubernetes/pkg/apis/apps/install *)
From New.golang Require Import defn.
Module pkg_id.
Definition install : go_string := "k8s.io/kubernetes/pkg/apis/apps/install".

End pkg_id.
Export pkg_id.
Module install.

Definition Install {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/kubernetes/pkg/apis/apps/install.Install"%go.

#[global] Instance info' : PkgInfo pkg_id.install :=
{|
  pkg_imported_pkgs := []
|}.

Axiom _'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.install (λ: <>,
      exception_do (do:  #())
      ).

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
}.
End install.
