(* autogenerated from controllers/replicaset *)
Require Export New.code.controllers.common.
Require Export New.code.k8s_io.api.apps.v1.
Require Export New.code.k8s_io.api.core.v1.
Require Export New.code.k8s_io.apimachinery.pkg.api.errors.
Require Export New.code.k8s_io.apimachinery.pkg.apis.meta.v1.
Require Export New.code.k8s_io.kubernetes.pkg.controller.

From New.golang Require Import defn.
Definition replicaset : go_string := "controllers/replicaset".

Module replicaset.

Section code.
Context `{ffi_syntax}.


Definition CreatePod : go_string := "controllers/replicaset.CreatePod"%go.

(* go: replica_set.go:19:6 *)
Definition CreatePodⁱᵐᵖˡ : val :=
  λ: "namespace" "template" "controllerObject" "controllerRef",
    exception_do (let: "controllerRef" := (mem.alloc "controllerRef") in
    let: "controllerObject" := (mem.alloc "controllerObject") in
    let: "template" := (mem.alloc "template") in
    let: "namespace" := (mem.alloc "namespace") in
    let: "err" := (mem.alloc (type.zero_val #error)) in
    let: "pod" := (mem.alloc (type.zero_val #ptrT)) in
    let: ("$ret0", "$ret1") := (let: "$a0" := (![#ptrT] "template") in
    let: "$a1" := (interface.make #(ptrT.id v1.ReplicaSet.id) (![#ptrT] "controllerObject")) in
    let: "$a2" := (![#ptrT] "controllerRef") in
    (func_call #controller.GetPodFromTemplate) "$a0" "$a1" "$a2") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("pod" <-[#ptrT] "$r0");;;
    do:  ("err" <-[#error] "$r1");;;
    (if: (~ (interface.eq (![#error] "err") #interface.nil))
    then return: (![#error] "err")
    else do:  #());;;
    let: ("$ret0", "$ret1") := (let: "$a0" := (![#stringT] "namespace") in
    let: "$a1" := (![#ptrT] "pod") in
    (method_call #(ptrT.id apimodel.State.id) #"PodCreate"%go (![#ptrT] (globals.get #common.State))) "$a0" "$a1") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  "$r0";;;
    do:  ("err" <-[#error] "$r1");;;
    return: (![#error] "err")).

Definition IsPodActive : go_string := "controllers/replicaset.IsPodActive"%go.

(* go: replica_set.go:28:6 *)
Definition IsPodActiveⁱᵐᵖˡ : val :=
  λ: "p",
    exception_do (let: "p" := (mem.alloc "p") in
    return: ((![#ptrT] (struct.field_ref #v1.ObjectMeta #"DeletionTimestamp"%go (struct.field_ref #v1.Pod #"ObjectMeta"%go (![#ptrT] "p")))) = #null)).

Definition FilterActivePods : go_string := "controllers/replicaset.FilterActivePods"%go.

(* go: replica_set.go:32:6 *)
Definition FilterActivePodsⁱᵐᵖˡ : val :=
  λ: "pods",
    exception_do (let: "pods" := (mem.alloc "pods") in
    let: "result" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$range" := (![#sliceT] "pods") in
    (let: "p" := (mem.alloc (type.zero_val #ptrT)) in
    slice.for_range #ptrT "$range" (λ: "$key" "$value",
      do:  ("p" <-[#ptrT] "$value");;;
      do:  "$key";;;
      (if: let: "$a0" := (![#ptrT] "p") in
      (func_call #IsPodActive) "$a0"
      then
        let: "$r0" := (let: "$a0" := (![#sliceT] "result") in
        let: "$a1" := ((let: "$sl0" := (![#ptrT] "p") in
        slice.literal #ptrT ["$sl0"])) in
        (slice.append #ptrT) "$a0" "$a1") in
        do:  ("result" <-[#sliceT] "$r0")
      else do:  #())));;;
    return: (![#sliceT] "result")).

Definition manageReplicas : go_string := "controllers/replicaset.manageReplicas"%go.

(* go: replica_set.go:42:6 *)
Definition manageReplicasⁱᵐᵖˡ : val :=
  λ: "activePods" "rs",
    exception_do (let: "rs" := (mem.alloc "rs") in
    let: "activePods" := (mem.alloc "activePods") in
    let: "diff" := (mem.alloc (type.zero_val #intT)) in
    let: "$r0" := ((let: "$a0" := (![#sliceT] "activePods") in
    slice.len "$a0") - (s_to_w64 (![#int32T] (![#ptrT] (struct.field_ref #v1.ReplicaSetSpec #"Replicas"%go (struct.field_ref #v1.ReplicaSet #"Spec"%go (![#ptrT] "rs"))))))) in
    do:  ("diff" <-[#intT] "$r0");;;
    (if: int_lt (![#intT] "diff") #(W64 0)
    then
      do:  ("diff" <-[#intT] ((![#intT] "diff") * #(W64 (- 1))));;;
      (let: "i" := (mem.alloc (type.zero_val #intT)) in
      let: "$r0" := #(W64 0) in
      do:  ("i" <-[#intT] "$r0");;;
      (for: (λ: <>, int_lt (![#intT] "i") (![#intT] "diff")); (λ: <>, do:  ("i" <-[#intT] ((![#intT] "i") + #(W64 1)))) := λ: <>,
        let: "err" := (mem.alloc (type.zero_val #error)) in
        let: "pod" := (mem.alloc (type.zero_val #ptrT)) in
        let: ("$ret0", "$ret1") := (let: "$a0" := (struct.field_ref #v1.ReplicaSetSpec #"Template"%go (struct.field_ref #v1.ReplicaSet #"Spec"%go (![#ptrT] "rs"))) in
        let: "$a1" := (interface.make #(ptrT.id v1.ReplicaSet.id) (![#ptrT] "rs")) in
        let: "$a2" := (let: "$a0" := (interface.make #(ptrT.id v1.ReplicaSet.id) (![#ptrT] "rs")) in
        let: "$a1" := (let: "$a0" := #"ReplicaSet"%go in
        (method_call #schema.GroupVersion.id #"WithKind"%go (![#schema.GroupVersion] (globals.get #v1.SchemeGroupVersion))) "$a0") in
        (func_call #v1.NewControllerRef) "$a0" "$a1") in
        (func_call #controller.GetPodFromTemplate) "$a0" "$a1" "$a2") in
        let: "$r0" := "$ret0" in
        let: "$r1" := "$ret1" in
        do:  ("pod" <-[#ptrT] "$r0");;;
        do:  ("err" <-[#error] "$r1");;;
        (if: (~ (interface.eq (![#error] "err") #interface.nil))
        then return: (![#error] "err")
        else do:  #());;;
        let: ("$ret0", "$ret1") := (let: "$a0" := (![#stringT] (struct.field_ref #v1.ObjectMeta #"Namespace"%go (struct.field_ref #v1.ReplicaSet #"ObjectMeta"%go (![#ptrT] "rs")))) in
        let: "$a1" := (![#ptrT] "pod") in
        (method_call #(ptrT.id apimodel.State.id) #"PodCreate"%go (![#ptrT] (globals.get #common.State))) "$a0" "$a1") in
        let: "$r0" := "$ret0" in
        let: "$r1" := "$ret1" in
        do:  "$r0";;;
        do:  ("err" <-[#error] "$r1");;;
        (if: (~ (interface.eq (![#error] "err") #interface.nil))
        then return: (![#error] "err")
        else do:  #())))
    else
      (if: int_gt (![#intT] "diff") #(W64 0)
      then
        let: "podsToDelete" := (mem.alloc (type.zero_val #sliceT)) in
        let: "$r0" := (let: "$s" := (![#sliceT] "activePods") in
        slice.slice #ptrT "$s" #(W64 0) (![#intT] "diff")) in
        do:  ("podsToDelete" <-[#sliceT] "$r0");;;
        let: "$range" := (![#sliceT] "podsToDelete") in
        (let: "pod" := (mem.alloc (type.zero_val #ptrT)) in
        slice.for_range #ptrT "$range" (λ: "$key" "$value",
          do:  ("pod" <-[#ptrT] "$value");;;
          do:  "$key";;;
          (let: "err" := (mem.alloc (type.zero_val #error)) in
          let: "$r0" := (let: "$a0" := (![#stringT] (struct.field_ref #v1.ObjectMeta #"Namespace"%go (struct.field_ref #v1.ReplicaSet #"ObjectMeta"%go (![#ptrT] "rs")))) in
          let: "$a1" := (![#stringT] (struct.field_ref #v1.ObjectMeta #"Name"%go (struct.field_ref #v1.Pod #"ObjectMeta"%go (![#ptrT] "pod")))) in
          let: "$a2" := (struct.make #v1.DeleteOptions [{
            "TypeMeta" ::= type.zero_val #v1.TypeMeta;
            "GracePeriodSeconds" ::= type.zero_val #ptrT;
            "Preconditions" ::= type.zero_val #ptrT;
            "OrphanDependents" ::= type.zero_val #ptrT;
            "PropagationPolicy" ::= type.zero_val #ptrT;
            "DryRun" ::= type.zero_val #sliceT;
            "IgnoreStoreReadErrorWithClusterBreakingPotential" ::= type.zero_val #ptrT
          }]) in
          (method_call #(ptrT.id apimodel.State.id) #"PodDelete"%go (![#ptrT] (globals.get #common.State))) "$a0" "$a1" "$a2") in
          do:  ("err" <-[#error] "$r0");;;
          (if: (~ (interface.eq (![#error] "err") #interface.nil))
          then
            (if: (~ (let: "$a0" := (![#error] "err") in
            (func_call #errors.IsNotFound) "$a0"))
            then return: (![#error] "err")
            else do:  #())
          else do:  #()))))
      else do:  #()));;;
    return: (#interface.nil)).

Definition syncReplicaSet : go_string := "controllers/replicaset.syncReplicaSet"%go.

(* go: replica_set.go:70:6 *)
Definition syncReplicaSetⁱᵐᵖˡ : val :=
  λ: "namespace" "name",
    exception_do (let: "name" := (mem.alloc "name") in
    let: "namespace" := (mem.alloc "namespace") in
    let: "err" := (mem.alloc (type.zero_val #error)) in
    let: "rs" := (mem.alloc (type.zero_val #ptrT)) in
    let: ("$ret0", "$ret1") := (let: "$a0" := (![#stringT] "namespace") in
    let: "$a1" := (![#stringT] "name") in
    (method_call #(ptrT.id apimodel.State.id) #"ReplicaSetGet"%go (![#ptrT] (globals.get #common.State))) "$a0" "$a1") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("rs" <-[#ptrT] "$r0");;;
    do:  ("err" <-[#error] "$r1");;;
    (if: let: "$a0" := (![#error] "err") in
    (func_call #errors.IsNotFound) "$a0"
    then return: (#interface.nil)
    else do:  #());;;
    (if: (~ (interface.eq (![#error] "err") #interface.nil))
    then return: (![#error] "err")
    else do:  #());;;
    let: "allRSPods" := (mem.alloc (type.zero_val #sliceT)) in
    let: ("$ret0", "$ret1") := (let: "$a0" := (struct.field_ref #v1.ReplicaSet #"ObjectMeta"%go (![#ptrT] "rs")) in
    let: "$a1" := #"ReplicaSet"%go in
    (func_call #common.FilterPodsByOwner) "$a0" "$a1") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("allRSPods" <-[#sliceT] "$r0");;;
    do:  ("err" <-[#error] "$r1");;;
    (if: (~ (interface.eq (![#error] "err") #interface.nil))
    then return: (![#error] "err")
    else do:  #());;;
    let: "allActivePods" := (mem.alloc (type.zero_val #sliceT)) in
    let: "$r0" := (let: "$a0" := (![#sliceT] "allRSPods") in
    (func_call #FilterActivePods) "$a0") in
    do:  ("allActivePods" <-[#sliceT] "$r0");;;
    let: "manageReplicasErr" := (mem.alloc (type.zero_val #error)) in
    (if: (![#ptrT] (struct.field_ref #v1.ObjectMeta #"DeletionTimestamp"%go (struct.field_ref #v1.ReplicaSet #"ObjectMeta"%go (![#ptrT] "rs")))) = #null
    then
      let: "$r0" := (let: "$a0" := (![#sliceT] "allActivePods") in
      let: "$a1" := (![#ptrT] "rs") in
      (func_call #manageReplicas) "$a0" "$a1") in
      do:  ("manageReplicasErr" <-[#error] "$r0")
    else do:  #());;;
    return: (![#error] "manageReplicasErr")).

Definition vars' : list (go_string * go_type) := [].

Definition functions' : list (go_string * val) := [(CreatePod, CreatePodⁱᵐᵖˡ); (IsPodActive, IsPodActiveⁱᵐᵖˡ); (FilterActivePods, FilterActivePodsⁱᵐᵖˡ); (manageReplicas, manageReplicasⁱᵐᵖˡ); (syncReplicaSet, syncReplicaSetⁱᵐᵖˡ)].

Definition msets' : list (go_string * (list (go_string * val))) := [].

#[global] Instance info' : PkgInfo replicaset.replicaset :=
  {|
    pkg_vars := vars';
    pkg_functions := functions';
    pkg_msets := msets';
    pkg_imported_pkgs := [code.controllers.common.common; code.k8s_io.api.apps.v1.v1; code.k8s_io.api.core.v1.v1; code.k8s_io.apimachinery.pkg.api.errors.errors; code.k8s_io.apimachinery.pkg.apis.meta.v1.v1; code.k8s_io.kubernetes.pkg.controller.controller];
  |}.

Definition initialize' : val :=
  λ: <>,
    package.init #replicaset.replicaset (λ: <>,
      exception_do (do:  (controller.initialize' #());;;
      do:  (v1.initialize' #());;;
      do:  (errors.initialize' #());;;
      do:  (v1.initialize' #());;;
      do:  (v1.initialize' #());;;
      do:  (common.initialize' #());;;
      do:  (package.alloc replicaset.replicaset #()))
      ).

End code.
End replicaset.
