(* autogenerated from controllers/statefulset *)
Require Export New.code.controllers.common.
Require Export New.code.kubernetes_model.apimodel.
Require Export New.code.reflect.
Require Export New.code.strconv.
Require Export New.code.strings.
Require Export New.code.k8s_io.api.apps.v1.
Require Export New.code.k8s_io.api.core.v1.
Require Export New.code.k8s_io.apimachinery.pkg.api.errors.
Require Export New.code.k8s_io.apimachinery.pkg.apis.meta.v1.
Require Export New.code.k8s_io.kubernetes.pkg.controller.
Module apps_v1 := code.k8s_io.api.apps.v1.v1.
Module core_v1 := code.k8s_io.api.core.v1.v1.
Module meta_v1 := code.k8s_io.apimachinery.pkg.apis.meta.v1.v1.
From New.golang Require Import defn.
Module pkg_id.
Definition statefulset : go_string := "controllers/statefulset".

End pkg_id.
Export pkg_id.
Module statefulset.

Definition controllerKind {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.controllerKind"%go.

Definition replicasOf {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.replicasOf"%go.

Definition endOrdinalOf {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.endOrdinalOf"%go.

Definition podName {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.podName"%go.

Definition claimName {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.claimName"%go.

Definition parentNameAndOrdinal {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.parentNameAndOrdinal"%go.

Definition ordinalOf {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.ordinalOf"%go.

Definition isMemberOf {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.isMemberOf"%go.

Definition filterPodsForStatefulSet {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.filterPodsForStatefulSet"%go.

Definition podInOrdinalRange {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.podInOrdinalRange"%go.

Definition updateIdentity {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.updateIdentity"%go.

Definition hasVolumeClaimTemplate {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.hasVolumeClaimTemplate"%go.

Definition updateStorage {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.updateStorage"%go.

Definition newStatefulSetPod {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.newStatefulSetPod"%go.

Definition newPersistentVolumeClaim {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.newPersistentVolumeClaim"%go.

Definition createPersistentVolumeClaims {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.createPersistentVolumeClaims"%go.

Definition createStatefulPod {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.createStatefulPod"%go.

Definition updateStatefulPod {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.updateStatefulPod"%go.

Definition deletePod {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.deletePod"%go.

Definition findPodByOrdinal {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.findPodByOrdinal"%go.

Definition firstCondemnedPod {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.firstCondemnedPod"%go.

Definition withoutStatefulSetFields {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.withoutStatefulSetFields"%go.

Definition podSpecMatches {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.podSpecMatches"%go.

Definition largestOutdatedPod {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.largestOutdatedPod"%go.

Definition samePod {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.samePod"%go.

Definition withoutPod {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.withoutPod"%go.

Definition reconcileReplicas {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.reconcileReplicas"%go.

Definition syncStatefulSet {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "controllers/statefulset.syncStatefulSet"%go.

(* go: stateful_set.go:26:6 *)
Definition replicasOfⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "set",
    exception_do (let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) "set") in
    (if: Convert go.untyped_bool go.bool ((![go.PointerType go.int32] (StructFieldRef apps_v1.StatefulSetSpec "Replicas"%go (StructFieldRef apps_v1.StatefulSet "Spec"%go (![go.PointerType apps_v1.StatefulSet] "set")))) =⟨go.PointerType go.int32⟩ (Convert go.untyped_nil (go.PointerType go.int32) UntypedNil))
    then return: (#(W64 1))
    else do:  #());;;
    return: (Convert go.int32 go.int (![go.int32] (![go.PointerType go.int32] (StructFieldRef apps_v1.StatefulSetSpec "Replicas"%go (StructFieldRef apps_v1.StatefulSet "Spec"%go (![go.PointerType apps_v1.StatefulSet] "set"))))))).

(* go: stateful_set.go:33:6 *)
Definition endOrdinalOfⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "set",
    exception_do (let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) "set") in
    return: ((let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
     (FuncResolve replicasOf [] #()) "$a0") -⟨go.int⟩ #(W64 1))).

(* go: stateful_set.go:37:6 *)
Definition podNameⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "set" "ordinal",
    exception_do (let: "ordinal" := (GoAlloc go.int "ordinal") in
    let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) "set") in
    return: (((![go.string] (StructFieldRef meta_v1.ObjectMeta "Name"%go (StructFieldRef apps_v1.StatefulSet "ObjectMeta"%go (![go.PointerType apps_v1.StatefulSet] "set")))) +⟨go.string⟩ #"-"%go) +⟨go.string⟩ (let: "$a0" := (![go.int] "ordinal") in
     (FuncResolve strconv.Itoa [] #()) "$a0"))).

(* go: stateful_set.go:41:6 *)
Definition claimNameⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "set" "claim" "ordinal",
    exception_do (let: "ordinal" := (GoAlloc go.int "ordinal") in
    let: "claim" := (GoAlloc (go.PointerType core_v1.PersistentVolumeClaim) "claim") in
    let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) "set") in
    return: (((((![go.string] (StructFieldRef meta_v1.ObjectMeta "Name"%go (StructFieldRef core_v1.PersistentVolumeClaim "ObjectMeta"%go (![go.PointerType core_v1.PersistentVolumeClaim] "claim")))) +⟨go.string⟩ #"-"%go) +⟨go.string⟩ (![go.string] (StructFieldRef meta_v1.ObjectMeta "Name"%go (StructFieldRef apps_v1.StatefulSet "ObjectMeta"%go (![go.PointerType apps_v1.StatefulSet] "set"))))) +⟨go.string⟩ #"-"%go) +⟨go.string⟩ (let: "$a0" := (![go.int] "ordinal") in
     (FuncResolve strconv.Itoa [] #()) "$a0"))).

(* go: stateful_set.go:45:6 *)
Definition parentNameAndOrdinalⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "pod",
    exception_do (let: "pod" := (GoAlloc (go.PointerType core_v1.Pod) "pod") in
    let: "idx" := (GoAlloc go.int (GoZeroVal go.int #())) in
    let: "$r0" := (let: "$a0" := (![go.string] (StructFieldRef meta_v1.ObjectMeta "Name"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "pod")))) in
    let: "$a1" := #"-"%go in
    (FuncResolve strings.LastIndex [] #()) "$a0" "$a1") in
    do:  ("idx" <-[go.int] "$r0");;;
    (if: Convert go.untyped_bool go.bool ((![go.int] "idx") <⟨go.int⟩ #(W64 0))
    then return: (#""%go, Convert go.untyped_int go.int (⟨go.untyped_int⟩- #1))
    else do:  #());;;
    let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
    let: "ordinal" := (GoAlloc go.int (GoZeroVal go.int #())) in
    let: ("$ret0", "$ret1") := (let: "$a0" := (let: "$s" := (![go.string] (StructFieldRef meta_v1.ObjectMeta "Name"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "pod")))) in
    Slice go.string ("$s", (![go.int] "idx") +⟨go.int⟩ #(W64 1), FuncResolve go.len [go.string] #() (![go.string] (StructFieldRef meta_v1.ObjectMeta "Name"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "pod")))))) in
    (FuncResolve strconv.Atoi [] #()) "$a0") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("ordinal" <-[go.int] "$r0");;;
    do:  ("err" <-[go.error] "$r1");;;
    (if: Convert go.untyped_bool go.bool ((![go.error] "err") ≠⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))
    then return: (#""%go, Convert go.untyped_int go.int (⟨go.untyped_int⟩- #1))
    else do:  #());;;
    return: (let: "$s" := (![go.string] (StructFieldRef meta_v1.ObjectMeta "Name"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "pod")))) in
     Slice go.string ("$s", #(W64 0), ![go.int] "idx"), ![go.int] "ordinal")).

(* go: stateful_set.go:57:6 *)
Definition ordinalOfⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "pod",
    exception_do (let: "pod" := (GoAlloc (go.PointerType core_v1.Pod) "pod") in
    let: "ordinal" := (GoAlloc go.int (GoZeroVal go.int #())) in
    let: ("$ret0", "$ret1") := (let: "$a0" := (![go.PointerType core_v1.Pod] "pod") in
    (FuncResolve parentNameAndOrdinal [] #()) "$a0") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  "$r0";;;
    do:  ("ordinal" <-[go.int] "$r1");;;
    return: (![go.int] "ordinal")).

(* go: stateful_set.go:62:6 *)
Definition isMemberOfⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "set" "pod",
    exception_do (let: "pod" := (GoAlloc (go.PointerType core_v1.Pod) "pod") in
    let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) "set") in
    let: "ordinal" := (GoAlloc go.int (GoZeroVal go.int #())) in
    let: "parent" := (GoAlloc go.string (GoZeroVal go.string #())) in
    let: ("$ret0", "$ret1") := (let: "$a0" := (![go.PointerType core_v1.Pod] "pod") in
    (FuncResolve parentNameAndOrdinal [] #()) "$a0") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("parent" <-[go.string] "$r0");;;
    do:  ("ordinal" <-[go.int] "$r1");;;
    return: (((![go.string] "parent") =⟨go.string⟩ (![go.string] (StructFieldRef meta_v1.ObjectMeta "Name"%go (StructFieldRef apps_v1.StatefulSet "ObjectMeta"%go (![go.PointerType apps_v1.StatefulSet] "set"))))) && ((![go.int] "ordinal") ≥⟨go.int⟩ #(W64 0)))).

(* go: stateful_set.go:67:6 *)
Definition filterPodsForStatefulSetⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "set" "pods",
    exception_do (let: "pods" := (GoAlloc (go.SliceType (go.PointerType core_v1.Pod)) "pods") in
    let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) "set") in
    let: "result" := (GoAlloc (go.SliceType (go.PointerType core_v1.Pod)) (GoZeroVal (go.SliceType (go.PointerType core_v1.Pod)) #())) in
    let: "$r0" := (CompositeLiteral (go.SliceType (go.PointerType core_v1.Pod)) (LiteralValue [])) in
    do:  ("result" <-[go.SliceType (go.PointerType core_v1.Pod)] "$r0");;;
    let: "$range" := (![go.SliceType (go.PointerType core_v1.Pod)] "pods") in
    (let: "pod" := (GoAlloc (go.PointerType core_v1.Pod) (GoZeroVal (go.PointerType core_v1.Pod) #())) in
    slice.for_range (go.PointerType core_v1.Pod) "$range" (λ: "$key" "$value",
      do:  ("pod" <-[go.PointerType core_v1.Pod] "$value");;;
      do:  "$key";;;
      (if: let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
      let: "$a1" := (![go.PointerType core_v1.Pod] "pod") in
      (FuncResolve isMemberOf [] #()) "$a0" "$a1"
      then
        let: "$r0" := (let: "$a0" := (![go.SliceType (go.PointerType core_v1.Pod)] "result") in
        let: "$a1" := ((let: "$sl0" := (![go.PointerType core_v1.Pod] "pod") in
        CompositeLiteral (go.SliceType (go.PointerType core_v1.Pod)) (LiteralValue [KeyedElement None (ElementExpression (go.PointerType core_v1.Pod) "$sl0")]))) in
        (FuncResolve go.append [go.SliceType (go.PointerType core_v1.Pod)] #()) "$a0" "$a1") in
        do:  ("result" <-[go.SliceType (go.PointerType core_v1.Pod)] "$r0")
      else do:  #())));;;
    return: (![go.SliceType (go.PointerType core_v1.Pod)] "result")).

(* go: stateful_set.go:77:6 *)
Definition podInOrdinalRangeⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "set" "pod",
    exception_do (let: "pod" := (GoAlloc (go.PointerType core_v1.Pod) "pod") in
    let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) "set") in
    let: "ordinal" := (GoAlloc go.int (GoZeroVal go.int #())) in
    let: "$r0" := (let: "$a0" := (![go.PointerType core_v1.Pod] "pod") in
    (FuncResolve ordinalOf [] #()) "$a0") in
    do:  ("ordinal" <-[go.int] "$r0");;;
    return: (((![go.int] "ordinal") ≥⟨go.int⟩ #(W64 0)) && ((![go.int] "ordinal") ≤⟨go.int⟩ (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
     (FuncResolve endOrdinalOf [] #()) "$a0")))).

(* go: stateful_set.go:82:6 *)
Definition updateIdentityⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "set" "pod",
    exception_do (let: "pod" := (GoAlloc (go.PointerType core_v1.Pod) "pod") in
    let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) "set") in
    let: "ordinal" := (GoAlloc go.int (GoZeroVal go.int #())) in
    let: "$r0" := (let: "$a0" := (![go.PointerType core_v1.Pod] "pod") in
    (FuncResolve ordinalOf [] #()) "$a0") in
    do:  ("ordinal" <-[go.int] "$r0");;;
    let: "$r0" := (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
    let: "$a1" := (![go.int] "ordinal") in
    (FuncResolve podName [] #()) "$a0" "$a1") in
    do:  ((StructFieldRef meta_v1.ObjectMeta "Name"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "pod"))) <-[go.string] "$r0");;;
    let: "$r0" := (![go.string] (StructFieldRef meta_v1.ObjectMeta "Namespace"%go (StructFieldRef apps_v1.StatefulSet "ObjectMeta"%go (![go.PointerType apps_v1.StatefulSet] "set")))) in
    do:  ((StructFieldRef meta_v1.ObjectMeta "Namespace"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "pod"))) <-[go.string] "$r0");;;
    let: "$r0" := (![go.string] (StructFieldRef meta_v1.ObjectMeta "Name"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "pod")))) in
    do:  ((StructFieldRef core_v1.PodSpec "Hostname"%go (StructFieldRef core_v1.Pod "Spec"%go (![go.PointerType core_v1.Pod] "pod"))) <-[go.string] "$r0");;;
    let: "$r0" := (![go.string] (StructFieldRef apps_v1.StatefulSetSpec "ServiceName"%go (StructFieldRef apps_v1.StatefulSet "Spec"%go (![go.PointerType apps_v1.StatefulSet] "set")))) in
    do:  ((StructFieldRef core_v1.PodSpec "Subdomain"%go (StructFieldRef core_v1.Pod "Spec"%go (![go.PointerType core_v1.Pod] "pod"))) <-[go.string] "$r0");;;
    (if: Convert go.untyped_bool go.bool ((![go.MapType go.string go.string] (StructFieldRef meta_v1.ObjectMeta "Labels"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "pod")))) =⟨go.MapType go.string go.string⟩ (Convert go.untyped_nil (go.MapType go.string go.string) UntypedNil))
    then
      let: "$r0" := (CompositeLiteral (go.MapType go.string go.string) (LiteralValue [])) in
      do:  ((StructFieldRef meta_v1.ObjectMeta "Labels"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "pod"))) <-[go.MapType go.string go.string] "$r0")
    else do:  #());;;
    let: "$r0" := (![go.string] (StructFieldRef meta_v1.ObjectMeta "Name"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "pod")))) in
    do:  (map.insert go.string (![go.MapType go.string go.string] (StructFieldRef meta_v1.ObjectMeta "Labels"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "pod")))) (Convert go.untyped_string go.string apps_v1.StatefulSetPodNameLabel) "$r0");;;
    let: "$r0" := (let: "$a0" := (![go.int] "ordinal") in
    (FuncResolve strconv.Itoa [] #()) "$a0") in
    do:  (map.insert go.string (![go.MapType go.string go.string] (StructFieldRef meta_v1.ObjectMeta "Labels"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "pod")))) (Convert go.untyped_string go.string apps_v1.PodIndexLabel) "$r0");;;
    return: #()).

(* go: stateful_set.go:95:6 *)
Definition hasVolumeClaimTemplateⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "set" "volumeName",
    exception_do (let: "volumeName" := (GoAlloc go.string "volumeName") in
    let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) "set") in
    let: "$range" := (![go.SliceType core_v1.PersistentVolumeClaim] (StructFieldRef apps_v1.StatefulSetSpec "VolumeClaimTemplates"%go (StructFieldRef apps_v1.StatefulSet "Spec"%go (![go.PointerType apps_v1.StatefulSet] "set")))) in
    (let: "claim" := (GoAlloc core_v1.PersistentVolumeClaim (GoZeroVal core_v1.PersistentVolumeClaim #())) in
    slice.for_range core_v1.PersistentVolumeClaim "$range" (λ: "$key" "$value",
      do:  ("claim" <-[core_v1.PersistentVolumeClaim] "$value");;;
      do:  "$key";;;
      (if: Convert go.untyped_bool go.bool ((![go.string] (StructFieldRef meta_v1.ObjectMeta "Name"%go (StructFieldRef core_v1.PersistentVolumeClaim "ObjectMeta"%go "claim"))) =⟨go.string⟩ (![go.string] "volumeName"))
      then return: (#true)
      else do:  #())));;;
    return: (#false)).

(* go: stateful_set.go:104:6 *)
Definition updateStorageⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "set" "pod",
    exception_do (let: "pod" := (GoAlloc (go.PointerType core_v1.Pod) "pod") in
    let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) "set") in
    let: "ordinal" := (GoAlloc go.int (GoZeroVal go.int #())) in
    let: "$r0" := (let: "$a0" := (![go.PointerType core_v1.Pod] "pod") in
    (FuncResolve ordinalOf [] #()) "$a0") in
    do:  ("ordinal" <-[go.int] "$r0");;;
    let: "currentVolumes" := (GoAlloc (go.SliceType core_v1.Volume) (GoZeroVal (go.SliceType core_v1.Volume) #())) in
    let: "$r0" := (![go.SliceType core_v1.Volume] (StructFieldRef core_v1.PodSpec "Volumes"%go (StructFieldRef core_v1.Pod "Spec"%go (![go.PointerType core_v1.Pod] "pod")))) in
    do:  ("currentVolumes" <-[go.SliceType core_v1.Volume] "$r0");;;
    let: "newVolumes" := (GoAlloc (go.SliceType core_v1.Volume) (GoZeroVal (go.SliceType core_v1.Volume) #())) in
    let: "$r0" := (CompositeLiteral (go.SliceType core_v1.Volume) (LiteralValue [])) in
    do:  ("newVolumes" <-[go.SliceType core_v1.Volume] "$r0");;;
    let: "$range" := (![go.SliceType core_v1.PersistentVolumeClaim] (StructFieldRef apps_v1.StatefulSetSpec "VolumeClaimTemplates"%go (StructFieldRef apps_v1.StatefulSet "Spec"%go (![go.PointerType apps_v1.StatefulSet] "set")))) in
    (let: "claim" := (GoAlloc core_v1.PersistentVolumeClaim (GoZeroVal core_v1.PersistentVolumeClaim #())) in
    slice.for_range core_v1.PersistentVolumeClaim "$range" (λ: "$key" "$value",
      do:  ("claim" <-[core_v1.PersistentVolumeClaim] "$value");;;
      do:  "$key";;;
      let: "$r0" := (let: "$a0" := (![go.SliceType core_v1.Volume] "newVolumes") in
      let: "$a1" := ((let: "$sl0" := (let: "$v0" := (![go.string] (StructFieldRef meta_v1.ObjectMeta "Name"%go (StructFieldRef core_v1.PersistentVolumeClaim "ObjectMeta"%go "claim"))) in
      let: "$v1" := (let: "$v0" := (GoAlloc core_v1.PersistentVolumeClaimVolumeSource (let: "$v0" := (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
      let: "$a1" := "claim" in
      let: "$a2" := (![go.int] "ordinal") in
      (FuncResolve claimName [] #()) "$a0" "$a1" "$a2") in
      CompositeLiteral core_v1.PersistentVolumeClaimVolumeSource (LiteralValue [KeyedElement (Some (KeyField "ClaimName"%go)) (ElementExpression go.string "$v0")]))) in
      CompositeLiteral core_v1.VolumeSource (LiteralValue [KeyedElement (Some (KeyField "PersistentVolumeClaim"%go)) (ElementExpression (go.PointerType core_v1.PersistentVolumeClaimVolumeSource) "$v0")])) in
      CompositeLiteral core_v1.Volume (LiteralValue [KeyedElement (Some (KeyField "Name"%go)) (ElementExpression go.string "$v0"); KeyedElement (Some (KeyField "VolumeSource"%go)) (ElementExpression core_v1.VolumeSource "$v1")])) in
      CompositeLiteral (go.SliceType core_v1.Volume) (LiteralValue [KeyedElement None (ElementExpression core_v1.Volume "$sl0")]))) in
      (FuncResolve go.append [go.SliceType core_v1.Volume] #()) "$a0" "$a1") in
      do:  ("newVolumes" <-[go.SliceType core_v1.Volume] "$r0")));;;
    let: "$range" := (![go.SliceType core_v1.Volume] "currentVolumes") in
    (let: "volume" := (GoAlloc core_v1.Volume (GoZeroVal core_v1.Volume #())) in
    slice.for_range core_v1.Volume "$range" (λ: "$key" "$value",
      do:  ("volume" <-[core_v1.Volume] "$value");;;
      do:  "$key";;;
      (if: (⟨go.bool⟩! (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
      let: "$a1" := (![go.string] (StructFieldRef core_v1.Volume "Name"%go "volume")) in
      (FuncResolve hasVolumeClaimTemplate [] #()) "$a0" "$a1"))
      then
        let: "$r0" := (let: "$a0" := (![go.SliceType core_v1.Volume] "newVolumes") in
        let: "$a1" := ((let: "$sl0" := (![core_v1.Volume] "volume") in
        CompositeLiteral (go.SliceType core_v1.Volume) (LiteralValue [KeyedElement None (ElementExpression core_v1.Volume "$sl0")]))) in
        (FuncResolve go.append [go.SliceType core_v1.Volume] #()) "$a0" "$a1") in
        do:  ("newVolumes" <-[go.SliceType core_v1.Volume] "$r0")
      else do:  #())));;;
    let: "$r0" := (![go.SliceType core_v1.Volume] "newVolumes") in
    do:  ((StructFieldRef core_v1.PodSpec "Volumes"%go (StructFieldRef core_v1.Pod "Spec"%go (![go.PointerType core_v1.Pod] "pod"))) <-[go.SliceType core_v1.Volume] "$r0");;;
    return: #()).

(* go: stateful_set.go:129:6 *)
Definition newStatefulSetPodⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "set" "ordinal",
    exception_do (let: "ordinal" := (GoAlloc go.int "ordinal") in
    let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) "set") in
    let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
    let: "pod" := (GoAlloc (go.PointerType core_v1.Pod) (GoZeroVal (go.PointerType core_v1.Pod) #())) in
    let: ("$ret0", "$ret1") := (let: "$a0" := (StructFieldRef apps_v1.StatefulSetSpec "Template"%go (StructFieldRef apps_v1.StatefulSet "Spec"%go (![go.PointerType apps_v1.StatefulSet] "set"))) in
    let: "$a1" := (Convert (go.PointerType apps_v1.StatefulSet) runtime.Object (![go.PointerType apps_v1.StatefulSet] "set")) in
    let: "$a2" := (let: "$a0" := (Convert (go.PointerType apps_v1.StatefulSet) meta_v1.Object (![go.PointerType apps_v1.StatefulSet] "set")) in
    let: "$a1" := (![schema.GroupVersionKind] (GlobalVarAddr controllerKind #())) in
    (FuncResolve meta_v1.NewControllerRef [] #()) "$a0" "$a1") in
    (FuncResolve controller.GetPodFromTemplate [] #()) "$a0" "$a1" "$a2") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("pod" <-[go.PointerType core_v1.Pod] "$r0");;;
    do:  ("err" <-[go.error] "$r1");;;
    (if: Convert go.untyped_bool go.bool ((![go.error] "err") ≠⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))
    then return: (Convert go.untyped_nil (go.PointerType core_v1.Pod) UntypedNil, ![go.error] "err")
    else do:  #());;;
    let: "$r0" := (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
    let: "$a1" := (![go.int] "ordinal") in
    (FuncResolve podName [] #()) "$a0" "$a1") in
    do:  ((StructFieldRef meta_v1.ObjectMeta "Name"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "pod"))) <-[go.string] "$r0");;;
    do:  (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
    let: "$a1" := (![go.PointerType core_v1.Pod] "pod") in
    (FuncResolve updateIdentity [] #()) "$a0" "$a1");;;
    do:  (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
    let: "$a1" := (![go.PointerType core_v1.Pod] "pod") in
    (FuncResolve updateStorage [] #()) "$a0" "$a1");;;
    return: (![go.PointerType core_v1.Pod] "pod", Convert go.untyped_nil go.error UntypedNil)).

(* go: stateful_set.go:140:6 *)
Definition newPersistentVolumeClaimⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "set" "pod" "claimTemplate",
    exception_do (let: "claimTemplate" := (GoAlloc (go.PointerType core_v1.PersistentVolumeClaim) "claimTemplate") in
    let: "pod" := (GoAlloc (go.PointerType core_v1.Pod) "pod") in
    let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) "set") in
    let: "claim" := (GoAlloc (go.PointerType core_v1.PersistentVolumeClaim) (GoZeroVal (go.PointerType core_v1.PersistentVolumeClaim) #())) in
    let: "$r0" := ((MethodResolve (go.PointerType core_v1.PersistentVolumeClaim) "DeepCopy"%go (![go.PointerType core_v1.PersistentVolumeClaim] "claimTemplate")) #()) in
    do:  ("claim" <-[go.PointerType core_v1.PersistentVolumeClaim] "$r0");;;
    let: "$r0" := (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
    let: "$a1" := (![go.PointerType core_v1.PersistentVolumeClaim] "claim") in
    let: "$a2" := (let: "$a0" := (![go.PointerType core_v1.Pod] "pod") in
    (FuncResolve ordinalOf [] #()) "$a0") in
    (FuncResolve claimName [] #()) "$a0" "$a1" "$a2") in
    do:  ((StructFieldRef meta_v1.ObjectMeta "Name"%go (StructFieldRef core_v1.PersistentVolumeClaim "ObjectMeta"%go (![go.PointerType core_v1.PersistentVolumeClaim] "claim"))) <-[go.string] "$r0");;;
    let: "$r0" := (![go.string] (StructFieldRef meta_v1.ObjectMeta "Namespace"%go (StructFieldRef apps_v1.StatefulSet "ObjectMeta"%go (![go.PointerType apps_v1.StatefulSet] "set")))) in
    do:  ((StructFieldRef meta_v1.ObjectMeta "Namespace"%go (StructFieldRef core_v1.PersistentVolumeClaim "ObjectMeta"%go (![go.PointerType core_v1.PersistentVolumeClaim] "claim"))) <-[go.string] "$r0");;;
    (if: Convert go.untyped_bool go.bool ((![go.MapType go.string go.string] (StructFieldRef meta_v1.ObjectMeta "Labels"%go (StructFieldRef core_v1.PersistentVolumeClaim "ObjectMeta"%go (![go.PointerType core_v1.PersistentVolumeClaim] "claim")))) =⟨go.MapType go.string go.string⟩ (Convert go.untyped_nil (go.MapType go.string go.string) UntypedNil))
    then
      let: "$r0" := (CompositeLiteral (go.MapType go.string go.string) (LiteralValue [])) in
      do:  ((StructFieldRef meta_v1.ObjectMeta "Labels"%go (StructFieldRef core_v1.PersistentVolumeClaim "ObjectMeta"%go (![go.PointerType core_v1.PersistentVolumeClaim] "claim"))) <-[go.MapType go.string go.string] "$r0")
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((![go.PointerType meta_v1.LabelSelector] (StructFieldRef apps_v1.StatefulSetSpec "Selector"%go (StructFieldRef apps_v1.StatefulSet "Spec"%go (![go.PointerType apps_v1.StatefulSet] "set")))) ≠⟨go.PointerType meta_v1.LabelSelector⟩ (Convert go.untyped_nil (go.PointerType meta_v1.LabelSelector) UntypedNil))
    then
      let: "$range" := (![go.MapType go.string go.string] (StructFieldRef meta_v1.LabelSelector "MatchLabels"%go (![go.PointerType meta_v1.LabelSelector] (StructFieldRef apps_v1.StatefulSetSpec "Selector"%go (StructFieldRef apps_v1.StatefulSet "Spec"%go (![go.PointerType apps_v1.StatefulSet] "set")))))) in
      (let: "value" := (GoAlloc go.string (GoZeroVal go.string #())) in
      let: "key" := (GoAlloc go.string (GoZeroVal go.string #())) in
      map.for_range go.string go.string "$range" (λ: "$key" "$value",
        do:  ("value" <-[go.string] "$value");;;
        do:  ("key" <-[go.string] "$key");;;
        let: "$r0" := (![go.string] "value") in
        do:  (map.insert go.string (![go.MapType go.string go.string] (StructFieldRef meta_v1.ObjectMeta "Labels"%go (StructFieldRef core_v1.PersistentVolumeClaim "ObjectMeta"%go (![go.PointerType core_v1.PersistentVolumeClaim] "claim")))) (![go.string] "key") "$r0")))
    else do:  #());;;
    return: (![go.PointerType core_v1.PersistentVolumeClaim] "claim")).

(* go: stateful_set.go:155:6 *)
Definition createPersistentVolumeClaimsⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "set" "pod",
    exception_do (let: "pod" := (GoAlloc (go.PointerType core_v1.Pod) "pod") in
    let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) "set") in
    let: "$range" := (![go.SliceType core_v1.PersistentVolumeClaim] (StructFieldRef apps_v1.StatefulSetSpec "VolumeClaimTemplates"%go (StructFieldRef apps_v1.StatefulSet "Spec"%go (![go.PointerType apps_v1.StatefulSet] "set")))) in
    (let: "claimTemplate" := (GoAlloc core_v1.PersistentVolumeClaim (GoZeroVal core_v1.PersistentVolumeClaim #())) in
    slice.for_range core_v1.PersistentVolumeClaim "$range" (λ: "$key" "$value",
      do:  ("claimTemplate" <-[core_v1.PersistentVolumeClaim] "$value");;;
      do:  "$key";;;
      let: "claim" := (GoAlloc (go.PointerType core_v1.PersistentVolumeClaim) (GoZeroVal (go.PointerType core_v1.PersistentVolumeClaim) #())) in
      let: "$r0" := (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
      let: "$a1" := (![go.PointerType core_v1.Pod] "pod") in
      let: "$a2" := "claimTemplate" in
      (FuncResolve newPersistentVolumeClaim [] #()) "$a0" "$a1" "$a2") in
      do:  ("claim" <-[go.PointerType core_v1.PersistentVolumeClaim] "$r0");;;
      let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
      let: ("$ret0", "$ret1") := (let: "$a0" := (![go.string] (StructFieldRef meta_v1.ObjectMeta "Namespace"%go (StructFieldRef core_v1.PersistentVolumeClaim "ObjectMeta"%go (![go.PointerType core_v1.PersistentVolumeClaim] "claim")))) in
      let: "$a1" := (![go.string] (StructFieldRef meta_v1.ObjectMeta "Name"%go (StructFieldRef core_v1.PersistentVolumeClaim "ObjectMeta"%go (![go.PointerType core_v1.PersistentVolumeClaim] "claim")))) in
      (MethodResolve (go.PointerType apimodel.State) "PersistentVolumeClaimGet"%go (![go.PointerType apimodel.State] (GlobalVarAddr apimodel.ModelState #()))) "$a0" "$a1") in
      let: "$r0" := "$ret0" in
      let: "$r1" := "$ret1" in
      do:  "$r0";;;
      do:  ("err" <-[go.error] "$r1");;;
      (if: let: "$a0" := (![go.error] "err") in
      (FuncResolve errors.IsNotFound [] #()) "$a0"
      then
        let: ("$ret0", "$ret1") := (let: "$a0" := (![go.string] (StructFieldRef meta_v1.ObjectMeta "Namespace"%go (StructFieldRef core_v1.PersistentVolumeClaim "ObjectMeta"%go (![go.PointerType core_v1.PersistentVolumeClaim] "claim")))) in
        let: "$a1" := (![go.PointerType core_v1.PersistentVolumeClaim] "claim") in
        (MethodResolve (go.PointerType apimodel.State) "PersistentVolumeClaimCreate"%go (![go.PointerType apimodel.State] (GlobalVarAddr apimodel.ModelState #()))) "$a0" "$a1") in
        let: "$r0" := "$ret0" in
        let: "$r1" := "$ret1" in
        do:  "$r0";;;
        do:  ("err" <-[go.error] "$r1");;;
        (if: ((![go.error] "err") ≠⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil)) && (⟨go.bool⟩! (let: "$a0" := (![go.error] "err") in
        (FuncResolve errors.IsAlreadyExists [] #()) "$a0"))
        then return: (![go.error] "err")
        else do:  #());;;
        continue: #()
      else do:  #());;;
      (if: Convert go.untyped_bool go.bool ((![go.error] "err") ≠⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))
      then return: (![go.error] "err")
      else do:  #())));;;
    return: (Convert go.untyped_nil go.error UntypedNil)).

(* go: stateful_set.go:173:6 *)
Definition createStatefulPodⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "set" "pod",
    exception_do (let: "pod" := (GoAlloc (go.PointerType core_v1.Pod) "pod") in
    let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) "set") in
    (let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
    let: "$r0" := (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
    let: "$a1" := (![go.PointerType core_v1.Pod] "pod") in
    (FuncResolve createPersistentVolumeClaims [] #()) "$a0" "$a1") in
    do:  ("err" <-[go.error] "$r0");;;
    (if: Convert go.untyped_bool go.bool ((![go.error] "err") ≠⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))
    then return: (![go.error] "err")
    else do:  #()));;;
    let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
    let: ("$ret0", "$ret1") := (let: "$a0" := (![go.string] (StructFieldRef meta_v1.ObjectMeta "Namespace"%go (StructFieldRef apps_v1.StatefulSet "ObjectMeta"%go (![go.PointerType apps_v1.StatefulSet] "set")))) in
    let: "$a1" := (![go.PointerType core_v1.Pod] "pod") in
    (MethodResolve (go.PointerType apimodel.State) "PodCreate"%go (![go.PointerType apimodel.State] (GlobalVarAddr apimodel.ModelState #()))) "$a0" "$a1") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  "$r0";;;
    do:  ("err" <-[go.error] "$r1");;;
    (if: let: "$a0" := (![go.error] "err") in
    (FuncResolve errors.IsAlreadyExists [] #()) "$a0"
    then return: (Convert go.untyped_nil go.error UntypedNil)
    else do:  #());;;
    return: (![go.error] "err")).

(* go: stateful_set.go:184:6 *)
Definition updateStatefulPodⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "set" "pod",
    exception_do (let: "pod" := (GoAlloc (go.PointerType core_v1.Pod) "pod") in
    let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) "set") in
    let: "updatedPod" := (GoAlloc (go.PointerType core_v1.Pod) (GoZeroVal (go.PointerType core_v1.Pod) #())) in
    let: "$r0" := ((MethodResolve (go.PointerType core_v1.Pod) "DeepCopy"%go (![go.PointerType core_v1.Pod] "pod")) #()) in
    do:  ("updatedPod" <-[go.PointerType core_v1.Pod] "$r0");;;
    do:  (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
    let: "$a1" := (![go.PointerType core_v1.Pod] "updatedPod") in
    (FuncResolve updateIdentity [] #()) "$a0" "$a1");;;
    do:  (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
    let: "$a1" := (![go.PointerType core_v1.Pod] "updatedPod") in
    (FuncResolve updateStorage [] #()) "$a0" "$a1");;;
    let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
    let: ("$ret0", "$ret1") := (let: "$a0" := (![go.string] (StructFieldRef meta_v1.ObjectMeta "Namespace"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "updatedPod")))) in
    let: "$a1" := (![go.PointerType core_v1.Pod] "updatedPod") in
    (MethodResolve (go.PointerType apimodel.State) "PodUpdate"%go (![go.PointerType apimodel.State] (GlobalVarAddr apimodel.ModelState #()))) "$a0" "$a1") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  "$r0";;;
    do:  ("err" <-[go.error] "$r1");;;
    return: (![go.error] "err")).

(* go: stateful_set.go:192:6 *)
Definition deletePodⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "pod",
    exception_do (let: "pod" := (GoAlloc (go.PointerType core_v1.Pod) "pod") in
    let: "uid" := (GoAlloc types.UID (GoZeroVal types.UID #())) in
    let: "$r0" := ((MethodResolve (go.PointerType meta_v1.ObjectMeta) "GetUID"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "pod"))) #()) in
    do:  ("uid" <-[types.UID] "$r0");;;
    let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
    let: "$r0" := (let: "$a0" := (![go.string] (StructFieldRef meta_v1.ObjectMeta "Namespace"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "pod")))) in
    let: "$a1" := (![go.string] (StructFieldRef meta_v1.ObjectMeta "Name"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "pod")))) in
    let: "$a2" := (let: "$a0" := (![types.UID] "uid") in
    (FuncResolve common.NewDeleteOptionsWithUID [] #()) "$a0") in
    (MethodResolve (go.PointerType apimodel.State) "PodDelete"%go (![go.PointerType apimodel.State] (GlobalVarAddr apimodel.ModelState #()))) "$a0" "$a1" "$a2") in
    do:  ("err" <-[go.error] "$r0");;;
    (if: ((![go.error] "err") ≠⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil)) && (⟨go.bool⟩! (let: "$a0" := (![go.error] "err") in
    (FuncResolve errors.IsNotFound [] #()) "$a0"))
    then return: (![go.error] "err")
    else do:  #());;;
    return: (Convert go.untyped_nil go.error UntypedNil)).

(* go: stateful_set.go:201:6 *)
Definition findPodByOrdinalⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "set" "pods" "ordinal",
    exception_do (let: "ordinal" := (GoAlloc go.int "ordinal") in
    let: "pods" := (GoAlloc (go.SliceType (go.PointerType core_v1.Pod)) "pods") in
    let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) "set") in
    let: "$range" := (![go.SliceType (go.PointerType core_v1.Pod)] "pods") in
    (let: "pod" := (GoAlloc (go.PointerType core_v1.Pod) (GoZeroVal (go.PointerType core_v1.Pod) #())) in
    slice.for_range (go.PointerType core_v1.Pod) "$range" (λ: "$key" "$value",
      do:  ("pod" <-[go.PointerType core_v1.Pod] "$value");;;
      do:  "$key";;;
      let: "podOrdinal" := (GoAlloc go.int (GoZeroVal go.int #())) in
      let: "parent" := (GoAlloc go.string (GoZeroVal go.string #())) in
      let: ("$ret0", "$ret1") := (let: "$a0" := (![go.PointerType core_v1.Pod] "pod") in
      (FuncResolve parentNameAndOrdinal [] #()) "$a0") in
      let: "$r0" := "$ret0" in
      let: "$r1" := "$ret1" in
      do:  ("parent" <-[go.string] "$r0");;;
      do:  ("podOrdinal" <-[go.int] "$r1");;;
      (if: Convert go.untyped_bool go.bool (((![go.string] "parent") =⟨go.string⟩ (![go.string] (StructFieldRef meta_v1.ObjectMeta "Name"%go (StructFieldRef apps_v1.StatefulSet "ObjectMeta"%go (![go.PointerType apps_v1.StatefulSet] "set"))))) && ((![go.int] "podOrdinal") =⟨go.int⟩ (![go.int] "ordinal")))
      then return: (![go.PointerType core_v1.Pod] "pod")
      else do:  #())));;;
    return: (Convert go.untyped_nil (go.PointerType core_v1.Pod) UntypedNil)).

(* go: stateful_set.go:211:6 *)
Definition firstCondemnedPodⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "set" "pods",
    exception_do (let: "pods" := (GoAlloc (go.SliceType (go.PointerType core_v1.Pod)) "pods") in
    let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) "set") in
    let: "condemned" := (GoAlloc (go.PointerType core_v1.Pod) (GoZeroVal (go.PointerType core_v1.Pod) #())) in
    let: "$range" := (![go.SliceType (go.PointerType core_v1.Pod)] "pods") in
    (let: "pod" := (GoAlloc (go.PointerType core_v1.Pod) (GoZeroVal (go.PointerType core_v1.Pod) #())) in
    slice.for_range (go.PointerType core_v1.Pod) "$range" (λ: "$key" "$value",
      do:  ("pod" <-[go.PointerType core_v1.Pod] "$value");;;
      do:  "$key";;;
      let: "ordinal" := (GoAlloc go.int (GoZeroVal go.int #())) in
      let: "$r0" := (let: "$a0" := (![go.PointerType core_v1.Pod] "pod") in
      (FuncResolve ordinalOf [] #()) "$a0") in
      do:  ("ordinal" <-[go.int] "$r0");;;
      (if: ((![go.int] "ordinal") <⟨go.int⟩ #(W64 0)) || (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
      let: "$a1" := (![go.PointerType core_v1.Pod] "pod") in
      (FuncResolve podInOrdinalRange [] #()) "$a0" "$a1")
      then continue: #()
      else do:  #());;;
      (if: Convert go.untyped_bool go.bool (((![go.PointerType core_v1.Pod] "condemned") =⟨go.PointerType core_v1.Pod⟩ (Convert go.untyped_nil (go.PointerType core_v1.Pod) UntypedNil)) || ((![go.int] "ordinal") >⟨go.int⟩ (let: "$a0" := (![go.PointerType core_v1.Pod] "condemned") in
      (FuncResolve ordinalOf [] #()) "$a0")))
      then
        let: "$r0" := (![go.PointerType core_v1.Pod] "pod") in
        do:  ("condemned" <-[go.PointerType core_v1.Pod] "$r0")
      else do:  #())));;;
    return: (![go.PointerType core_v1.Pod] "condemned")).

(* go: stateful_set.go:225:6 *)
Definition withoutStatefulSetFieldsⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "spec",
    exception_do (let: "spec" := (GoAlloc core_v1.PodSpec "spec") in
    let: "$r0" := (Convert go.untyped_nil (go.SliceType core_v1.Volume) UntypedNil) in
    do:  ((StructFieldRef core_v1.PodSpec "Volumes"%go "spec") <-[go.SliceType core_v1.Volume] "$r0");;;
    let: "$r0" := #""%go in
    do:  ((StructFieldRef core_v1.PodSpec "Hostname"%go "spec") <-[go.string] "$r0");;;
    let: "$r0" := #""%go in
    do:  ((StructFieldRef core_v1.PodSpec "Subdomain"%go "spec") <-[go.string] "$r0");;;
    return: (![core_v1.PodSpec] "spec")).

(* go: stateful_set.go:232:6 *)
Definition podSpecMatchesⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "set" "pod",
    exception_do (let: "pod" := (GoAlloc (go.PointerType core_v1.Pod) "pod") in
    let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) "set") in
    let: "podSpec" := (GoAlloc core_v1.PodSpec (GoZeroVal core_v1.PodSpec #())) in
    let: "$r0" := (let: "$a0" := (![core_v1.PodSpec] (StructFieldRef core_v1.Pod "Spec"%go (![go.PointerType core_v1.Pod] "pod"))) in
    (FuncResolve withoutStatefulSetFields [] #()) "$a0") in
    do:  ("podSpec" <-[core_v1.PodSpec] "$r0");;;
    let: "templateSpec" := (GoAlloc core_v1.PodSpec (GoZeroVal core_v1.PodSpec #())) in
    let: "$r0" := (let: "$a0" := (![core_v1.PodSpec] (StructFieldRef core_v1.PodTemplateSpec "Spec"%go (StructFieldRef apps_v1.StatefulSetSpec "Template"%go (StructFieldRef apps_v1.StatefulSet "Spec"%go (![go.PointerType apps_v1.StatefulSet] "set"))))) in
    (FuncResolve withoutStatefulSetFields [] #()) "$a0") in
    do:  ("templateSpec" <-[core_v1.PodSpec] "$r0");;;
    return: (let: "$a0" := (Convert core_v1.PodSpec go.any (![core_v1.PodSpec] "podSpec")) in
     let: "$a1" := (Convert core_v1.PodSpec go.any (![core_v1.PodSpec] "templateSpec")) in
     (FuncResolve reflect.DeepEqual [] #()) "$a0" "$a1")).

(* go: stateful_set.go:238:6 *)
Definition largestOutdatedPodⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "set" "pods",
    exception_do (let: "pods" := (GoAlloc (go.SliceType (go.PointerType core_v1.Pod)) "pods") in
    let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) "set") in
    (let: "ordinal" := (GoAlloc go.int (GoZeroVal go.int #())) in
    let: "$r0" := (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
    (FuncResolve endOrdinalOf [] #()) "$a0") in
    do:  ("ordinal" <-[go.int] "$r0");;;
    (for: (λ: <>, (![go.int] "ordinal") ≥⟨go.int⟩ #(W64 0)); (λ: <>, do:  ("ordinal" <-[go.int] ((![go.int] "ordinal") -⟨go.int⟩ #(W64 1)))) := λ: <>,
      let: "pod" := (GoAlloc (go.PointerType core_v1.Pod) (GoZeroVal (go.PointerType core_v1.Pod) #())) in
      let: "$r0" := (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
      let: "$a1" := (![go.SliceType (go.PointerType core_v1.Pod)] "pods") in
      let: "$a2" := (![go.int] "ordinal") in
      (FuncResolve findPodByOrdinal [] #()) "$a0" "$a1" "$a2") in
      do:  ("pod" <-[go.PointerType core_v1.Pod] "$r0");;;
      (if: ((![go.PointerType core_v1.Pod] "pod") ≠⟨go.PointerType core_v1.Pod⟩ (Convert go.untyped_nil (go.PointerType core_v1.Pod) UntypedNil)) && (⟨go.bool⟩! (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
      let: "$a1" := (![go.PointerType core_v1.Pod] "pod") in
      (FuncResolve podSpecMatches [] #()) "$a0" "$a1"))
      then return: (![go.PointerType core_v1.Pod] "pod")
      else do:  #())));;;
    return: (Convert go.untyped_nil (go.PointerType core_v1.Pod) UntypedNil)).

(* go: stateful_set.go:248:6 *)
Definition samePodⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "pod" "other",
    exception_do (let: "other" := (GoAlloc (go.PointerType core_v1.Pod) "other") in
    let: "pod" := (GoAlloc (go.PointerType core_v1.Pod) "pod") in
    return: ((((![go.PointerType core_v1.Pod] "other") ≠⟨go.PointerType core_v1.Pod⟩ (Convert go.untyped_nil (go.PointerType core_v1.Pod) UntypedNil)) && ((![go.string] (StructFieldRef meta_v1.ObjectMeta "Namespace"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "pod")))) =⟨go.string⟩ (![go.string] (StructFieldRef meta_v1.ObjectMeta "Namespace"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "other")))))) && ((![go.string] (StructFieldRef meta_v1.ObjectMeta "Name"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "pod")))) =⟨go.string⟩ (![go.string] (StructFieldRef meta_v1.ObjectMeta "Name"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "other"))))))).

(* go: stateful_set.go:252:6 *)
Definition withoutPodⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "pods" "target",
    exception_do (let: "target" := (GoAlloc (go.PointerType core_v1.Pod) "target") in
    let: "pods" := (GoAlloc (go.SliceType (go.PointerType core_v1.Pod)) "pods") in
    let: "result" := (GoAlloc (go.SliceType (go.PointerType core_v1.Pod)) (GoZeroVal (go.SliceType (go.PointerType core_v1.Pod)) #())) in
    let: "$r0" := (CompositeLiteral (go.SliceType (go.PointerType core_v1.Pod)) (LiteralValue [])) in
    do:  ("result" <-[go.SliceType (go.PointerType core_v1.Pod)] "$r0");;;
    let: "$range" := (![go.SliceType (go.PointerType core_v1.Pod)] "pods") in
    (let: "pod" := (GoAlloc (go.PointerType core_v1.Pod) (GoZeroVal (go.PointerType core_v1.Pod) #())) in
    slice.for_range (go.PointerType core_v1.Pod) "$range" (λ: "$key" "$value",
      do:  ("pod" <-[go.PointerType core_v1.Pod] "$value");;;
      do:  "$key";;;
      (if: let: "$a0" := (![go.PointerType core_v1.Pod] "pod") in
      let: "$a1" := (![go.PointerType core_v1.Pod] "target") in
      (FuncResolve samePod [] #()) "$a0" "$a1"
      then continue: #()
      else do:  #());;;
      let: "$r0" := (let: "$a0" := (![go.SliceType (go.PointerType core_v1.Pod)] "result") in
      let: "$a1" := ((let: "$sl0" := (![go.PointerType core_v1.Pod] "pod") in
      CompositeLiteral (go.SliceType (go.PointerType core_v1.Pod)) (LiteralValue [KeyedElement None (ElementExpression (go.PointerType core_v1.Pod) "$sl0")]))) in
      (FuncResolve go.append [go.SliceType (go.PointerType core_v1.Pod)] #()) "$a0" "$a1") in
      do:  ("result" <-[go.SliceType (go.PointerType core_v1.Pod)] "$r0")));;;
    return: (![go.SliceType (go.PointerType core_v1.Pod)] "result")).

(* go: stateful_set.go:263:6 *)
Definition reconcileReplicasⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "set" "pods",
    exception_do (let: "pods" := (GoAlloc (go.SliceType (go.PointerType core_v1.Pod)) "pods") in
    let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) "set") in
    let: "end" := (GoAlloc go.int (GoZeroVal go.int #())) in
    let: "$r0" := (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
    (FuncResolve endOrdinalOf [] #()) "$a0") in
    do:  ("end" <-[go.int] "$r0");;;
    (let: "ordinal" := (GoAlloc go.int (GoZeroVal go.int #())) in
    let: "$r0" := #(W64 0) in
    do:  ("ordinal" <-[go.int] "$r0");;;
    (for: (λ: <>, (![go.int] "ordinal") ≤⟨go.int⟩ (![go.int] "end")); (λ: <>, do:  ("ordinal" <-[go.int] ((![go.int] "ordinal") +⟨go.int⟩ #(W64 1)))) := λ: <>,
      let: "pod" := (GoAlloc (go.PointerType core_v1.Pod) (GoZeroVal (go.PointerType core_v1.Pod) #())) in
      let: "$r0" := (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
      let: "$a1" := (![go.SliceType (go.PointerType core_v1.Pod)] "pods") in
      let: "$a2" := (![go.int] "ordinal") in
      (FuncResolve findPodByOrdinal [] #()) "$a0" "$a1" "$a2") in
      do:  ("pod" <-[go.PointerType core_v1.Pod] "$r0");;;
      (if: Convert go.untyped_bool go.bool ((![go.PointerType core_v1.Pod] "pod") =⟨go.PointerType core_v1.Pod⟩ (Convert go.untyped_nil (go.PointerType core_v1.Pod) UntypedNil))
      then
        let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
        let: "newPod" := (GoAlloc (go.PointerType core_v1.Pod) (GoZeroVal (go.PointerType core_v1.Pod) #())) in
        let: ("$ret0", "$ret1") := (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
        let: "$a1" := (![go.int] "ordinal") in
        (FuncResolve newStatefulSetPod [] #()) "$a0" "$a1") in
        let: "$r0" := "$ret0" in
        let: "$r1" := "$ret1" in
        do:  ("newPod" <-[go.PointerType core_v1.Pod] "$r0");;;
        do:  ("err" <-[go.error] "$r1");;;
        (if: Convert go.untyped_bool go.bool ((![go.error] "err") ≠⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))
        then return: (![go.error] "err")
        else do:  #());;;
        (let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
        let: "$r0" := (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
        let: "$a1" := (![go.PointerType core_v1.Pod] "newPod") in
        (FuncResolve createStatefulPod [] #()) "$a0" "$a1") in
        do:  ("err" <-[go.error] "$r0");;;
        (if: Convert go.untyped_bool go.bool ((![go.error] "err") ≠⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))
        then return: (![go.error] "err")
        else do:  #()));;;
        continue: #()
      else do:  #());;;
      (let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
      let: "$r0" := (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
      let: "$a1" := (![go.PointerType core_v1.Pod] "pod") in
      (FuncResolve createPersistentVolumeClaims [] #()) "$a0" "$a1") in
      do:  ("err" <-[go.error] "$r0");;;
      (if: Convert go.untyped_bool go.bool ((![go.error] "err") ≠⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))
      then return: (![go.error] "err")
      else do:  #()));;;
      (let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
      let: "$r0" := (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
      let: "$a1" := (![go.PointerType core_v1.Pod] "pod") in
      (FuncResolve updateStatefulPod [] #()) "$a0" "$a1") in
      do:  ("err" <-[go.error] "$r0");;;
      (if: Convert go.untyped_bool go.bool ((![go.error] "err") ≠⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))
      then return: (![go.error] "err")
      else do:  #()))));;;
    (let: "condemned" := (GoAlloc (go.PointerType core_v1.Pod) (GoZeroVal (go.PointerType core_v1.Pod) #())) in
    let: "$r0" := (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
    let: "$a1" := (![go.SliceType (go.PointerType core_v1.Pod)] "pods") in
    (FuncResolve firstCondemnedPod [] #()) "$a0" "$a1") in
    do:  ("condemned" <-[go.PointerType core_v1.Pod] "$r0");;;
    (for: (λ: <>, (![go.PointerType core_v1.Pod] "condemned") ≠⟨go.PointerType core_v1.Pod⟩ (Convert go.untyped_nil (go.PointerType core_v1.Pod) UntypedNil)); (λ: <>, let: "$r0" := (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
    let: "$a1" := (![go.SliceType (go.PointerType core_v1.Pod)] "pods") in
    (FuncResolve firstCondemnedPod [] #()) "$a0" "$a1") in
    do:  ("condemned" <-[go.PointerType core_v1.Pod] "$r0")) := λ: <>,
      (if: Convert go.untyped_bool go.bool ((![go.PointerType meta_v1.Time] (StructFieldRef meta_v1.ObjectMeta "DeletionTimestamp"%go (StructFieldRef core_v1.Pod "ObjectMeta"%go (![go.PointerType core_v1.Pod] "condemned")))) ≠⟨go.PointerType meta_v1.Time⟩ (Convert go.untyped_nil (go.PointerType meta_v1.Time) UntypedNil))
      then
        let: "$r0" := (let: "$a0" := (![go.SliceType (go.PointerType core_v1.Pod)] "pods") in
        let: "$a1" := (![go.PointerType core_v1.Pod] "condemned") in
        (FuncResolve withoutPod [] #()) "$a0" "$a1") in
        do:  ("pods" <-[go.SliceType (go.PointerType core_v1.Pod)] "$r0");;;
        continue: #()
      else do:  #());;;
      (let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
      let: "$r0" := (let: "$a0" := (![go.PointerType core_v1.Pod] "condemned") in
      (FuncResolve deletePod [] #()) "$a0") in
      do:  ("err" <-[go.error] "$r0");;;
      (if: Convert go.untyped_bool go.bool ((![go.error] "err") ≠⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))
      then return: (![go.error] "err")
      else do:  #()));;;
      let: "$r0" := (let: "$a0" := (![go.SliceType (go.PointerType core_v1.Pod)] "pods") in
      let: "$a1" := (![go.PointerType core_v1.Pod] "condemned") in
      (FuncResolve withoutPod [] #()) "$a0" "$a1") in
      do:  ("pods" <-[go.SliceType (go.PointerType core_v1.Pod)] "$r0")));;;
    (let: "outdated" := (GoAlloc (go.PointerType core_v1.Pod) (GoZeroVal (go.PointerType core_v1.Pod) #())) in
    let: "$r0" := (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
    let: "$a1" := (![go.SliceType (go.PointerType core_v1.Pod)] "pods") in
    (FuncResolve largestOutdatedPod [] #()) "$a0" "$a1") in
    do:  ("outdated" <-[go.PointerType core_v1.Pod] "$r0");;;
    (if: Convert go.untyped_bool go.bool ((![go.PointerType core_v1.Pod] "outdated") ≠⟨go.PointerType core_v1.Pod⟩ (Convert go.untyped_nil (go.PointerType core_v1.Pod) UntypedNil))
    then
      return: (let: "$a0" := (![go.PointerType core_v1.Pod] "outdated") in
       (FuncResolve deletePod [] #()) "$a0")
    else do:  #()));;;
    return: (Convert go.untyped_nil go.error UntypedNil)).

(* go: stateful_set.go:306:6 *)
Definition syncStatefulSetⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "namespace" "name",
    exception_do (let: "name" := (GoAlloc go.string "name") in
    let: "namespace" := (GoAlloc go.string "namespace") in
    let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
    let: "set" := (GoAlloc (go.PointerType apps_v1.StatefulSet) (GoZeroVal (go.PointerType apps_v1.StatefulSet) #())) in
    let: ("$ret0", "$ret1") := (let: "$a0" := (![go.string] "namespace") in
    let: "$a1" := (![go.string] "name") in
    (MethodResolve (go.PointerType apimodel.State) "StatefulSetGet"%go (![go.PointerType apimodel.State] (GlobalVarAddr apimodel.ModelState #()))) "$a0" "$a1") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("set" <-[go.PointerType apps_v1.StatefulSet] "$r0");;;
    do:  ("err" <-[go.error] "$r1");;;
    (if: let: "$a0" := (![go.error] "err") in
    (FuncResolve errors.IsNotFound [] #()) "$a0"
    then return: (Convert go.untyped_nil go.error UntypedNil)
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((![go.error] "err") ≠⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))
    then return: (![go.error] "err")
    else do:  #());;;
    let: "allPods" := (GoAlloc (go.SliceType (go.PointerType core_v1.Pod)) (GoZeroVal (go.SliceType (go.PointerType core_v1.Pod)) #())) in
    let: ("$ret0", "$ret1") := (let: "$a0" := (StructFieldRef apps_v1.StatefulSet "ObjectMeta"%go (![go.PointerType apps_v1.StatefulSet] "set")) in
    let: "$a1" := #"StatefulSet"%go in
    (FuncResolve common.FilterPodsByOwner [] #()) "$a0" "$a1") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("allPods" <-[go.SliceType (go.PointerType core_v1.Pod)] "$r0");;;
    do:  ("err" <-[go.error] "$r1");;;
    (if: Convert go.untyped_bool go.bool ((![go.error] "err") ≠⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))
    then return: (![go.error] "err")
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((![go.PointerType meta_v1.Time] (StructFieldRef meta_v1.ObjectMeta "DeletionTimestamp"%go (StructFieldRef apps_v1.StatefulSet "ObjectMeta"%go (![go.PointerType apps_v1.StatefulSet] "set")))) ≠⟨go.PointerType meta_v1.Time⟩ (Convert go.untyped_nil (go.PointerType meta_v1.Time) UntypedNil))
    then return: (Convert go.untyped_nil go.error UntypedNil)
    else do:  #());;;
    return: (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
     let: "$a1" := (let: "$a0" := (![go.PointerType apps_v1.StatefulSet] "set") in
     let: "$a1" := (![go.SliceType (go.PointerType core_v1.Pod)] "allPods") in
     (FuncResolve filterPodsForStatefulSet [] #()) "$a0" "$a1") in
     (FuncResolve reconcileReplicas [] #()) "$a0" "$a1")).

#[global] Instance info' : PkgInfo pkg_id.statefulset :=
{|
  pkg_imported_pkgs := [code.controllers.common.pkg_id.common; code.kubernetes_model.apimodel.pkg_id.apimodel; code.reflect.pkg_id.reflect; code.strconv.pkg_id.strconv; code.strings.pkg_id.strings; code.k8s_io.api.apps.v1.pkg_id.v1; code.k8s_io.api.core.v1.pkg_id.v1; code.k8s_io.apimachinery.pkg.api.errors.pkg_id.errors; code.k8s_io.apimachinery.pkg.apis.meta.v1.pkg_id.v1; code.k8s_io.kubernetes.pkg.controller.pkg_id.controller]
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.statefulset (λ: <>,
      exception_do (do:  (go.GlobalAlloc controllerKind schema.GroupVersionKind #());;;
      do:  (controller.initialize' #());;;
      do:  (meta_v1.initialize' #());;;
      do:  (errors.initialize' #());;;
      do:  (core_v1.initialize' #());;;
      do:  (apps_v1.initialize' #());;;
      do:  (strings.initialize' #());;;
      do:  (strconv.initialize' #());;;
      do:  (reflect.initialize' #());;;
      do:  (apimodel.initialize' #());;;
      do:  (common.initialize' #());;;
      let: "$r0" := (let: "$a0" := #"StatefulSet"%go in
      (MethodResolve (go.PointerType schema.GroupVersion) "WithKind"%go (GlobalVarAddr apps_v1.SchemeGroupVersion #())) "$a0") in
      do:  ((GlobalVarAddr controllerKind #()) <-[schema.GroupVersionKind] "$r0"))
      ).

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] replicasOf_unfold :: FuncUnfold replicasOf [] (replicasOfⁱᵐᵖˡ);
  #[global] endOrdinalOf_unfold :: FuncUnfold endOrdinalOf [] (endOrdinalOfⁱᵐᵖˡ);
  #[global] podName_unfold :: FuncUnfold podName [] (podNameⁱᵐᵖˡ);
  #[global] claimName_unfold :: FuncUnfold claimName [] (claimNameⁱᵐᵖˡ);
  #[global] parentNameAndOrdinal_unfold :: FuncUnfold parentNameAndOrdinal [] (parentNameAndOrdinalⁱᵐᵖˡ);
  #[global] ordinalOf_unfold :: FuncUnfold ordinalOf [] (ordinalOfⁱᵐᵖˡ);
  #[global] isMemberOf_unfold :: FuncUnfold isMemberOf [] (isMemberOfⁱᵐᵖˡ);
  #[global] filterPodsForStatefulSet_unfold :: FuncUnfold filterPodsForStatefulSet [] (filterPodsForStatefulSetⁱᵐᵖˡ);
  #[global] podInOrdinalRange_unfold :: FuncUnfold podInOrdinalRange [] (podInOrdinalRangeⁱᵐᵖˡ);
  #[global] updateIdentity_unfold :: FuncUnfold updateIdentity [] (updateIdentityⁱᵐᵖˡ);
  #[global] hasVolumeClaimTemplate_unfold :: FuncUnfold hasVolumeClaimTemplate [] (hasVolumeClaimTemplateⁱᵐᵖˡ);
  #[global] updateStorage_unfold :: FuncUnfold updateStorage [] (updateStorageⁱᵐᵖˡ);
  #[global] newStatefulSetPod_unfold :: FuncUnfold newStatefulSetPod [] (newStatefulSetPodⁱᵐᵖˡ);
  #[global] newPersistentVolumeClaim_unfold :: FuncUnfold newPersistentVolumeClaim [] (newPersistentVolumeClaimⁱᵐᵖˡ);
  #[global] createPersistentVolumeClaims_unfold :: FuncUnfold createPersistentVolumeClaims [] (createPersistentVolumeClaimsⁱᵐᵖˡ);
  #[global] createStatefulPod_unfold :: FuncUnfold createStatefulPod [] (createStatefulPodⁱᵐᵖˡ);
  #[global] updateStatefulPod_unfold :: FuncUnfold updateStatefulPod [] (updateStatefulPodⁱᵐᵖˡ);
  #[global] deletePod_unfold :: FuncUnfold deletePod [] (deletePodⁱᵐᵖˡ);
  #[global] findPodByOrdinal_unfold :: FuncUnfold findPodByOrdinal [] (findPodByOrdinalⁱᵐᵖˡ);
  #[global] firstCondemnedPod_unfold :: FuncUnfold firstCondemnedPod [] (firstCondemnedPodⁱᵐᵖˡ);
  #[global] withoutStatefulSetFields_unfold :: FuncUnfold withoutStatefulSetFields [] (withoutStatefulSetFieldsⁱᵐᵖˡ);
  #[global] podSpecMatches_unfold :: FuncUnfold podSpecMatches [] (podSpecMatchesⁱᵐᵖˡ);
  #[global] largestOutdatedPod_unfold :: FuncUnfold largestOutdatedPod [] (largestOutdatedPodⁱᵐᵖˡ);
  #[global] samePod_unfold :: FuncUnfold samePod [] (samePodⁱᵐᵖˡ);
  #[global] withoutPod_unfold :: FuncUnfold withoutPod [] (withoutPodⁱᵐᵖˡ);
  #[global] reconcileReplicas_unfold :: FuncUnfold reconcileReplicas [] (reconcileReplicasⁱᵐᵖˡ);
  #[global] syncStatefulSet_unfold :: FuncUnfold syncStatefulSet [] (syncStatefulSetⁱᵐᵖˡ);
  #[global] import_common_Assumption :: common.Assumptions;
  #[global] import_apimodel_Assumption :: apimodel.Assumptions;
  #[global] import_reflect_Assumption :: reflect.Assumptions;
  #[global] import_strconv_Assumption :: strconv.Assumptions;
  #[global] import_strings_Assumption :: strings.Assumptions;
  #[global] import_apps_v1_Assumption :: apps_v1.Assumptions;
  #[global] import_core_v1_Assumption :: core_v1.Assumptions;
  #[global] import_errors_Assumption :: errors.Assumptions;
  #[global] import_meta_v1_Assumption :: meta_v1.Assumptions;
  #[global] import_controller_Assumption :: controller.Assumptions;
}.
End statefulset.
