(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.golang.theory.
Require Export New.code.k8s_io.client_go.util.flowcontrol.

Set Default Proof Using "Type".

Module flowcontrol.
Module backoffEntry.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : flowcontrol.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance backoffEntry_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (flowcontrol.backoffEntry.t). Admitted.

#[global] Instance backoffEntry_into_val_typed
   :
  IntoValTypedUnderlying (flowcontrol.backoffEntry.t) (flowcontrol.backoffEntryⁱᵐᵖˡ).
Proof. Admitted.

End def.
End backoffEntry.

Module Backoff.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : flowcontrol.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Backoff_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (flowcontrol.Backoff.t). Admitted.

#[global] Instance Backoff_into_val_typed
   :
  IntoValTypedUnderlying (flowcontrol.Backoff.t) (flowcontrol.Backoffⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Backoff.

Module PassiveRateLimiter.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : flowcontrol.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance PassiveRateLimiter_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (flowcontrol.PassiveRateLimiter.t). Admitted.

#[global] Instance PassiveRateLimiter_into_val_typed
   :
  IntoValTypedUnderlying (flowcontrol.PassiveRateLimiter.t) (flowcontrol.PassiveRateLimiterⁱᵐᵖˡ).
Proof. Admitted.

End def.
End PassiveRateLimiter.

Module RateLimiter.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : flowcontrol.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance RateLimiter_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (flowcontrol.RateLimiter.t). Admitted.

#[global] Instance RateLimiter_into_val_typed
   :
  IntoValTypedUnderlying (flowcontrol.RateLimiter.t) (flowcontrol.RateLimiterⁱᵐᵖˡ).
Proof. Admitted.

End def.
End RateLimiter.

Module tokenBucketPassiveRateLimiter.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : flowcontrol.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance tokenBucketPassiveRateLimiter_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (flowcontrol.tokenBucketPassiveRateLimiter.t). Admitted.

#[global] Instance tokenBucketPassiveRateLimiter_into_val_typed
   :
  IntoValTypedUnderlying (flowcontrol.tokenBucketPassiveRateLimiter.t) (flowcontrol.tokenBucketPassiveRateLimiterⁱᵐᵖˡ).
Proof. Admitted.

End def.
End tokenBucketPassiveRateLimiter.

Module tokenBucketRateLimiter.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : flowcontrol.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance tokenBucketRateLimiter_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (flowcontrol.tokenBucketRateLimiter.t). Admitted.

#[global] Instance tokenBucketRateLimiter_into_val_typed
   :
  IntoValTypedUnderlying (flowcontrol.tokenBucketRateLimiter.t) (flowcontrol.tokenBucketRateLimiterⁱᵐᵖˡ).
Proof. Admitted.

End def.
End tokenBucketRateLimiter.

Module Clock.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : flowcontrol.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance Clock_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (flowcontrol.Clock.t). Admitted.

#[global] Instance Clock_into_val_typed
   :
  IntoValTypedUnderlying (flowcontrol.Clock.t) (flowcontrol.Clockⁱᵐᵖˡ).
Proof. Admitted.

End def.
End Clock.

Module fakeAlwaysRateLimiter.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : flowcontrol.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance fakeAlwaysRateLimiter_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (flowcontrol.fakeAlwaysRateLimiter.t). Admitted.

#[global] Instance fakeAlwaysRateLimiter_into_val_typed
   :
  IntoValTypedUnderlying (flowcontrol.fakeAlwaysRateLimiter.t) (flowcontrol.fakeAlwaysRateLimiterⁱᵐᵖˡ).
Proof. Admitted.

End def.
End fakeAlwaysRateLimiter.

Module fakeNeverRateLimiter.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : flowcontrol.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance fakeNeverRateLimiter_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (flowcontrol.fakeNeverRateLimiter.t). Admitted.

#[global] Instance fakeNeverRateLimiter_into_val_typed
   :
  IntoValTypedUnderlying (flowcontrol.fakeNeverRateLimiter.t) (flowcontrol.fakeNeverRateLimiterⁱᵐᵖˡ).
Proof. Admitted.

End def.
End fakeNeverRateLimiter.

End flowcontrol.
