translate = [
    "Set",
    "Labels",
    "Selector",
    "Requirement",
    "internalSelector",
    "nothingSelector",
    "ByKey",
    "sharedEverythingSelector",
    "sharedNothingSelector",
    "Everything",
    "Nothing",
    "NewSelector",
    "NewRequirement",
    "validateLabelKey",
    "validateLabelValue",
    "Set.Get",
    "Set.Has",
    "Set.Lookup",
    "Requirement.hasValue",
    "Requirement.Matches",
    "internalSelector.DeepCopy",
    "internalSelector.DeepCopySelector",
    "internalSelector.Empty",
    "internalSelector.Add",
    "internalSelector.Matches",
    "internalSelector.Requirements",
    "internalSelector.String",
    "internalSelector.RequiresExactMatch",
    "nothingSelector.Add",
    "nothingSelector.DeepCopySelector",
    "nothingSelector.Empty",
    "nothingSelector.Matches",
    "nothingSelector.Requirements",
    "nothingSelector.String",
    "nothingSelector.RequiresExactMatch",
    "ByKey.Len",
    "ByKey.Less",
    "ByKey.Swap",
]

imports = [
    "errors",
    "sort",
    "strconv",
    "k8s.io/klog/v2",
    "k8s.io/apimachinery/pkg/selection",
    "k8s.io/apimachinery/pkg/util/validation",
    "k8s.io/apimachinery/pkg/util/validation/field",
]
