(* autogenerated from k8s.io/apimachinery/pkg/types *)
From New.golang Require Import defn.
Module pkg_id.
Definition types : go_string := "k8s.io/apimachinery/pkg/types".

End pkg_id.
Export pkg_id.
Module types.

Definition NamespacedName {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apimachinery/pkg/types.NamespacedName"%go [].

#[global] Opaque NamespacedName.

Definition NodeName {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apimachinery/pkg/types.NodeName"%go [].

#[global] Opaque NodeName.

Definition PatchType {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apimachinery/pkg/types.PatchType"%go [].

#[global] Opaque PatchType.

Definition UID {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/apimachinery/pkg/types.UID"%go [].

#[global] Opaque UID.

Axiom NamespacedNameⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom NodeNameⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom PatchTypeⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Separator : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom JSONPatchType : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom MergePatchType : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom StrategicMergePatchType : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom ApplyPatchType : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom ApplyYAMLPatchType : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Axiom ApplyCBORPatchType : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

#[global] Instance info' : PkgInfo pkg_id.types :=
{|
  pkg_imported_pkgs := []
|}.

Axiom _'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.types (λ: <>,
      exception_do (do:  #())
      ).

Module NamespacedName.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End NamespacedName.

Class NamespacedName_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] NamespacedName_type_repr  :: go.TypeReprUnderlying NamespacedNameⁱᵐᵖˡ NamespacedName.t;
  #[global] NamespacedName_underlying :: (NamespacedName) <u (NamespacedNameⁱᵐᵖˡ);
  #[global] NamespacedNameⁱᵐᵖˡ_underlying :: (NamespacedNameⁱᵐᵖˡ) ↓u (NamespacedNameⁱᵐᵖˡ);
}.

Module NodeName.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End NodeName.

Class NodeName_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] NodeName_type_repr  :: go.TypeReprUnderlying NodeNameⁱᵐᵖˡ NodeName.t;
  #[global] NodeName_underlying :: (NodeName) <u (NodeNameⁱᵐᵖˡ);
  #[global] NodeNameⁱᵐᵖˡ_underlying :: (NodeNameⁱᵐᵖˡ) ↓u (NodeNameⁱᵐᵖˡ);
}.

Module PatchType.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End PatchType.

Class PatchType_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] PatchType_type_repr  :: go.TypeReprUnderlying PatchTypeⁱᵐᵖˡ PatchType.t;
  #[global] PatchType_underlying :: (PatchType) <u (PatchTypeⁱᵐᵖˡ);
  #[global] PatchTypeⁱᵐᵖˡ_underlying :: (PatchTypeⁱᵐᵖˡ) ↓u (PatchTypeⁱᵐᵖˡ);
}.

Module UID.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Definition t : Type := go_string.
End def.
End UID.

Definition UIDⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.string.

Class UID_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] UID_underlying :: (UID) <u (UIDⁱᵐᵖˡ);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] NamespacedName_instance :: NamespacedName_Assumptions;
  #[global] NodeName_instance :: NodeName_Assumptions;
  #[global] PatchType_instance :: PatchType_Assumptions;
  #[global] UID_instance :: UID_Assumptions;
}.
End types.
