(* autogenerated from k8s.io/client-go/util/flowcontrol *)
From New.golang Require Import defn.
Module pkg_id.
Definition flowcontrol : go_string := "k8s.io/client-go/util/flowcontrol".

End pkg_id.
Export pkg_id.
Module flowcontrol.

Definition backoffEntry {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/util/flowcontrol.backoffEntry"%go [].

#[global] Opaque backoffEntry.

Definition Backoff {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/util/flowcontrol.Backoff"%go [].

#[global] Opaque Backoff.

Definition PassiveRateLimiter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/util/flowcontrol.PassiveRateLimiter"%go [].

#[global] Opaque PassiveRateLimiter.

Definition RateLimiter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/util/flowcontrol.RateLimiter"%go [].

#[global] Opaque RateLimiter.

Definition tokenBucketPassiveRateLimiter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/util/flowcontrol.tokenBucketPassiveRateLimiter"%go [].

#[global] Opaque tokenBucketPassiveRateLimiter.

Definition tokenBucketRateLimiter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/util/flowcontrol.tokenBucketRateLimiter"%go [].

#[global] Opaque tokenBucketRateLimiter.

Definition Clock {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/util/flowcontrol.Clock"%go [].

#[global] Opaque Clock.

Definition fakeAlwaysRateLimiter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/util/flowcontrol.fakeAlwaysRateLimiter"%go [].

#[global] Opaque fakeAlwaysRateLimiter.

Definition fakeNeverRateLimiter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "k8s.io/client-go/util/flowcontrol.fakeNeverRateLimiter"%go [].

#[global] Opaque fakeNeverRateLimiter.

Axiom backoffEntryⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Backoffⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom PassiveRateLimiterⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom RateLimiterⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom tokenBucketPassiveRateLimiterⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom tokenBucketRateLimiterⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom Clockⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom fakeAlwaysRateLimiterⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom fakeNeverRateLimiterⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Definition NewFakeBackOff {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/util/flowcontrol.NewFakeBackOff"%go.

Definition NewBackOff {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/util/flowcontrol.NewBackOff"%go.

Definition NewFakeBackOffWithJitter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/util/flowcontrol.NewFakeBackOffWithJitter"%go.

Definition NewBackOffWithJitter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/util/flowcontrol.NewBackOffWithJitter"%go.

Definition newBackoff {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/util/flowcontrol.newBackoff"%go.

Definition NewTokenBucketRateLimiter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/util/flowcontrol.NewTokenBucketRateLimiter"%go.

Definition NewTokenBucketPassiveRateLimiter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/util/flowcontrol.NewTokenBucketPassiveRateLimiter"%go.

Definition NewTokenBucketRateLimiterWithClock {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/util/flowcontrol.NewTokenBucketRateLimiterWithClock"%go.

Definition NewTokenBucketPassiveRateLimiterWithClock {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/util/flowcontrol.NewTokenBucketPassiveRateLimiterWithClock"%go.

Definition newTokenBucketRateLimiterWithClock {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/util/flowcontrol.newTokenBucketRateLimiterWithClock"%go.

Definition newTokenBucketRateLimiterWithPassiveClock {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/util/flowcontrol.newTokenBucketRateLimiterWithPassiveClock"%go.

Definition NewFakeAlwaysRateLimiter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/util/flowcontrol.NewFakeAlwaysRateLimiter"%go.

Definition NewFakeNeverRateLimiter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "k8s.io/client-go/util/flowcontrol.NewFakeNeverRateLimiter"%go.

#[global] Instance info' : PkgInfo pkg_id.flowcontrol :=
{|
  pkg_imported_pkgs := []
|}.

Axiom _'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.flowcontrol (λ: <>,
      exception_do (do:  (_'init #());;;
      do:  (_'init #());;;
      do:  (_'init #());;;
      do:  (_'init #());;;
      do:  (_'init #()))
      ).

Module backoffEntry.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End backoffEntry.

Class backoffEntry_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] backoffEntry_type_repr  :: go.TypeReprUnderlying backoffEntryⁱᵐᵖˡ backoffEntry.t;
  #[global] backoffEntry_underlying :: (backoffEntry) <u (backoffEntryⁱᵐᵖˡ);
  #[global] backoffEntryⁱᵐᵖˡ_underlying :: (backoffEntryⁱᵐᵖˡ) ↓u (backoffEntryⁱᵐᵖˡ);
}.

Module Backoff.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Backoff.

Class Backoff_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Backoff_type_repr  :: go.TypeReprUnderlying Backoffⁱᵐᵖˡ Backoff.t;
  #[global] Backoff_underlying :: (Backoff) <u (Backoffⁱᵐᵖˡ);
  #[global] Backoffⁱᵐᵖˡ_underlying :: (Backoffⁱᵐᵖˡ) ↓u (Backoffⁱᵐᵖˡ);
}.

Module PassiveRateLimiter.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End PassiveRateLimiter.

Class PassiveRateLimiter_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] PassiveRateLimiter_type_repr  :: go.TypeReprUnderlying PassiveRateLimiterⁱᵐᵖˡ PassiveRateLimiter.t;
  #[global] PassiveRateLimiter_underlying :: (PassiveRateLimiter) <u (PassiveRateLimiterⁱᵐᵖˡ);
  #[global] PassiveRateLimiterⁱᵐᵖˡ_underlying :: (PassiveRateLimiterⁱᵐᵖˡ) ↓u (PassiveRateLimiterⁱᵐᵖˡ);
}.

Module RateLimiter.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End RateLimiter.

Class RateLimiter_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] RateLimiter_type_repr  :: go.TypeReprUnderlying RateLimiterⁱᵐᵖˡ RateLimiter.t;
  #[global] RateLimiter_underlying :: (RateLimiter) <u (RateLimiterⁱᵐᵖˡ);
  #[global] RateLimiterⁱᵐᵖˡ_underlying :: (RateLimiterⁱᵐᵖˡ) ↓u (RateLimiterⁱᵐᵖˡ);
}.

Module tokenBucketPassiveRateLimiter.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End tokenBucketPassiveRateLimiter.

Class tokenBucketPassiveRateLimiter_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] tokenBucketPassiveRateLimiter_type_repr  :: go.TypeReprUnderlying tokenBucketPassiveRateLimiterⁱᵐᵖˡ tokenBucketPassiveRateLimiter.t;
  #[global] tokenBucketPassiveRateLimiter_underlying :: (tokenBucketPassiveRateLimiter) <u (tokenBucketPassiveRateLimiterⁱᵐᵖˡ);
  #[global] tokenBucketPassiveRateLimiterⁱᵐᵖˡ_underlying :: (tokenBucketPassiveRateLimiterⁱᵐᵖˡ) ↓u (tokenBucketPassiveRateLimiterⁱᵐᵖˡ);
}.

Module tokenBucketRateLimiter.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End tokenBucketRateLimiter.

Class tokenBucketRateLimiter_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] tokenBucketRateLimiter_type_repr  :: go.TypeReprUnderlying tokenBucketRateLimiterⁱᵐᵖˡ tokenBucketRateLimiter.t;
  #[global] tokenBucketRateLimiter_underlying :: (tokenBucketRateLimiter) <u (tokenBucketRateLimiterⁱᵐᵖˡ);
  #[global] tokenBucketRateLimiterⁱᵐᵖˡ_underlying :: (tokenBucketRateLimiterⁱᵐᵖˡ) ↓u (tokenBucketRateLimiterⁱᵐᵖˡ);
}.

Module Clock.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Clock.

Class Clock_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Clock_type_repr  :: go.TypeReprUnderlying Clockⁱᵐᵖˡ Clock.t;
  #[global] Clock_underlying :: (Clock) <u (Clockⁱᵐᵖˡ);
  #[global] Clockⁱᵐᵖˡ_underlying :: (Clockⁱᵐᵖˡ) ↓u (Clockⁱᵐᵖˡ);
}.

Module fakeAlwaysRateLimiter.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End fakeAlwaysRateLimiter.

Class fakeAlwaysRateLimiter_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] fakeAlwaysRateLimiter_type_repr  :: go.TypeReprUnderlying fakeAlwaysRateLimiterⁱᵐᵖˡ fakeAlwaysRateLimiter.t;
  #[global] fakeAlwaysRateLimiter_underlying :: (fakeAlwaysRateLimiter) <u (fakeAlwaysRateLimiterⁱᵐᵖˡ);
  #[global] fakeAlwaysRateLimiterⁱᵐᵖˡ_underlying :: (fakeAlwaysRateLimiterⁱᵐᵖˡ) ↓u (fakeAlwaysRateLimiterⁱᵐᵖˡ);
}.

Module fakeNeverRateLimiter.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End fakeNeverRateLimiter.

Class fakeNeverRateLimiter_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] fakeNeverRateLimiter_type_repr  :: go.TypeReprUnderlying fakeNeverRateLimiterⁱᵐᵖˡ fakeNeverRateLimiter.t;
  #[global] fakeNeverRateLimiter_underlying :: (fakeNeverRateLimiter) <u (fakeNeverRateLimiterⁱᵐᵖˡ);
  #[global] fakeNeverRateLimiterⁱᵐᵖˡ_underlying :: (fakeNeverRateLimiterⁱᵐᵖˡ) ↓u (fakeNeverRateLimiterⁱᵐᵖˡ);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] backoffEntry_instance :: backoffEntry_Assumptions;
  #[global] Backoff_instance :: Backoff_Assumptions;
  #[global] PassiveRateLimiter_instance :: PassiveRateLimiter_Assumptions;
  #[global] RateLimiter_instance :: RateLimiter_Assumptions;
  #[global] tokenBucketPassiveRateLimiter_instance :: tokenBucketPassiveRateLimiter_Assumptions;
  #[global] tokenBucketRateLimiter_instance :: tokenBucketRateLimiter_Assumptions;
  #[global] Clock_instance :: Clock_Assumptions;
  #[global] fakeAlwaysRateLimiter_instance :: fakeAlwaysRateLimiter_Assumptions;
  #[global] fakeNeverRateLimiter_instance :: fakeNeverRateLimiter_Assumptions;
}.
End flowcontrol.
