name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-rocq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: coq-community/docker-coq-action@v1
        with:
          coq_version: "9.0"
          ocaml_version: "default"
          install: ""
          # for permissions issue, see: https://github.com/coq-community/docker-coq-action#permissions.
          before_script: |
            sudo chown -R 1000:1000 .
          script: |
            startGroup Build
              make -j4 -k vok
            endGroup
          uninstall: |
            make clean
      - name: Revert permissions
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .

